/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
          "on-tertiary-fixed-variant": "#6c3832",
          "on-primary-fixed": "#281800",
          "on-surface": "#e2e2eb",
          "on-tertiary-fixed": "#360e0a",
          "surface-tint": "#ffba44",
          "primary-container": "#f0a500",
          "error": "#ffb4ab",
          "outline": "#9f8e79",
          "secondary-fixed": "#5ffbd6",
          "inverse-surface": "#e2e2eb",
          "surface-bright": "#373940",
          "tertiary": "#ffc1b9",
          "surface-variant": "#33343b",
          "surface-dim": "#111319",
          "tertiary-fixed-dim": "#ffb4ab",
          "secondary-fixed-dim": "#38deba",
          "on-secondary-fixed": "#002019",
          "primary": "#ffc56c",
          "secondary-container": "#05caa8",
          "on-tertiary-container": "#6b3731",
          "on-surface-variant": "#d6c4ac",
          "primary-fixed-dim": "#ffba44",
          "surface-container-low": "#191b22",
          "surface-container": "#1d1f26",
          "on-error": "#690005",
          "on-secondary": "#00382d",
          "on-primary-fixed-variant": "#614000",
          "inverse-primary": "#805600",
          "surface-container-highest": "#33343b",
          "surface": "#111319",
          "surface-container-lowest": "#0c0e14",
          "on-background": "#e2e2eb",
          "on-error-container": "#ffdad6",
          "on-secondary-fixed-variant": "#005142",
          "tertiary-container": "#eaa299",
          "secondary": "#41e4c0",
          "tertiary-fixed": "#ffdad5",
          "background": "#111319",
          "surface-container-high": "#282a30",
          "on-secondary-container": "#004f40",
          "on-primary": "#442c00",
          "outline-variant": "#514533",
          "on-tertiary": "#51221d",
          "error-container": "#93000a",
          "inverse-on-surface": "#2e3037",
          "primary-fixed": "#ffddaf",
          "on-primary-container": "#5f3f00"
      },
      fontFamily: {
          "headline": ["Newsreader", "serif"],
          "body": ["Manrope", "sans-serif"],
          "label": ["Space Grotesk", "monospace"]
      },
      borderRadius: {
          "DEFAULT": "0px",
          "lg": "0px",
          "xl": "0px",
          "full": "9999px"
      },
    },
  },
  plugins: [],
}
