/**
 * TypeForge UI Locale Store
 *
 * Single source of truth for the active UI language.
 * - Reads from user DB preference (authenticated) or localStorage (anonymous)
 * - Org members inherit the org's default if they haven't set a personal override
 * - Wraps Paraglide's setLocale / getLocale
 */

import { browser } from '$app/environment';

// Paraglide runtime — generated by the build plugin from project.inlang
// The import is aliased so it resolves after the first build
let _paraglide: typeof import('./paraglide/runtime') | null = null;

async function getParaglide() {
  if (!_paraglide) {
    _paraglide = await import('./paraglide/runtime');
  }
  return _paraglide;
}

const STORAGE_KEY = 'tf_ui_locale';
const SUPPORTED = ['en', 'es', 'fr', 'de', 'pt'] as const;
export type UiLocale = (typeof SUPPORTED)[number];

export const UI_LOCALES: { code: UiLocale; nativeName: string; englishName: string }[] = [
  { code: 'en', nativeName: 'English',    englishName: 'English'    },
  { code: 'es', nativeName: 'Español',    englishName: 'Spanish'    },
  { code: 'fr', nativeName: 'Français',   englishName: 'French'     },
  { code: 'de', nativeName: 'Deutsch',    englishName: 'German'     },
  { code: 'pt', nativeName: 'Português',  englishName: 'Portuguese' },
];

function isSupported(code: string): code is UiLocale {
  return SUPPORTED.includes(code as UiLocale);
}

/** Read persisted locale from localStorage (browser only). */
export function getPersistedLocale(): UiLocale {
  if (!browser) return 'en';
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored && isSupported(stored)) return stored;
  } catch {}
  // Fall back to browser language matching
  for (const lang of navigator.languages ?? []) {
    const code = lang.split('-')[0]!.toLowerCase();
    if (isSupported(code)) return code;
  }
  return 'en';
}

/** Apply a locale: updates Paraglide, localStorage, and <html lang>. */
export async function setUiLocale(code: UiLocale) {
  if (!browser) return;
  try {
    localStorage.setItem(STORAGE_KEY, code);
  } catch {}
  // Set <html lang>
  document.documentElement.lang = code;
  // Update Paraglide runtime
  const pg = await getParaglide();
  pg.setLocale(code);
}

/**
 * Initialise locale on app boot.
 * Priority: DB preference → localStorage → browser language → 'en'
 *
 * @param dbLocale  Locale from the user's DB profile (pass null if unauthenticated or not yet fetched)
 * @param orgLocale Default locale set by the user's organisation (used if no personal preference)
 */
export async function initLocale(
  dbLocale: string | null = null,
  orgLocale: string | null = null
) {
  let resolved: UiLocale = 'en';

  // 1. DB personal preference takes highest priority
  if (dbLocale && isSupported(dbLocale)) {
    resolved = dbLocale;
  }
  // 2. Org default — only if no personal preference stored
  else if (orgLocale && isSupported(orgLocale) && !localStorage.getItem(STORAGE_KEY)) {
    resolved = orgLocale;
  }
  // 3. localStorage / browser language
  else {
    resolved = getPersistedLocale();
  }

  await setUiLocale(resolved);
  return resolved;
}

/**
 * Persist the locale to the user's DB profile via PATCH /users/me/locale.
 * Fire-and-forget — non-critical.
 */
export async function saveLocaleToApi(code: UiLocale, token: string | null) {
  if (!token) return;
  try {
    await fetch('/api/v1/users/me/locale', {
      method: 'PATCH',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${token}`,
      },
      body: JSON.stringify({ locale: code }),
    });
  } catch {}
}
