/**
 * Arabic wordlist with 200+ common words organized by difficulty
 * Includes Arabic-specific contextual letter forms and Arabic-Indic numerals
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Arabic wordlist - 200+ common words
 * Difficulty 1: Basic particles, pronouns, common words
 * Difficulty 2: Intermediate vocabulary with varied letter forms
 * Difficulty 3: Advanced words demonstrating contextual Arabic letter forms
 */
export const arabicWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'في', difficulty: 1, tags: ['preposition', 'basic', 'particle'] },
  { word: 'من', difficulty: 1, tags: ['preposition', 'basic', 'particle'] },
  { word: 'على', difficulty: 1, tags: ['preposition', 'basic', 'particle'] },
  { word: 'أن', difficulty: 1, tags: ['particle', 'basic'] },
  { word: 'هذا', difficulty: 1, tags: ['demonstrative', 'basic', 'masculine'] },
  { word: 'هذه', difficulty: 1, tags: ['demonstrative', 'basic', 'feminine'] },
  { word: 'هي', difficulty: 1, tags: ['pronoun', 'basic', 'feminine'] },
  { word: 'هو', difficulty: 1, tags: ['pronoun', 'basic', 'masculine'] },
  { word: 'أنا', difficulty: 1, tags: ['pronoun', 'basic', 'first-person'] },
  { word: 'نحن', difficulty: 1, tags: ['pronoun', 'basic', 'plural'] },
  { word: 'إلى', difficulty: 1, tags: ['preposition', 'basic', 'particle'] },
  { word: 'عن', difficulty: 1, tags: ['preposition', 'basic', 'particle'] },
  { word: 'مع', difficulty: 1, tags: ['preposition', 'basic', 'particle'] },
  { word: 'لا', difficulty: 1, tags: ['negation', 'basic', 'particle'] },
  { word: 'ما', difficulty: 1, tags: ['interrogative', 'basic', 'particle'] },
  { word: 'لم', difficulty: 1, tags: ['negation', 'basic', 'particle'] },
  { word: 'قد', difficulty: 1, tags: ['particle', 'basic'] },
  { word: 'كل', difficulty: 1, tags: ['quantifier', 'basic'] },
  { word: 'بعد', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'قبل', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'بين', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'تحت', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'فوق', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'خلف', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'أمام', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'يوم', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'شهر', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'سنة', difficulty: 1, tags: ['noun', 'basic', 'time', 'feminine'] },
  { word: 'وقت', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'حين', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'صباح', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'مساء', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'ليل', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'أمس', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'غد', difficulty: 1, tags: ['noun', 'basic', 'time'] },
  { word: 'الآن', difficulty: 1, tags: ['adverb', 'basic', 'time'] },
  { word: 'ثم', difficulty: 1, tags: ['adverb', 'basic', 'sequence'] },
  { word: 'أيضا', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'جدا', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'هنا', difficulty: 1, tags: ['adverb', 'basic', 'place'] },
  { word: 'هناك', difficulty: 1, tags: ['adverb', 'basic', 'place'] },
  { word: 'نعم', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'بلى', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'مرحبا', difficulty: 1, tags: ['greeting', 'basic'] },
  { word: 'سلام', difficulty: 1, tags: ['greeting', 'basic'] },
  { word: 'شكرا', difficulty: 1, tags: ['courtesy', 'basic'] },
  { word: 'عفوا', difficulty: 1, tags: ['courtesy', 'basic'] },
  { word: 'ماء', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'نار', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'هواء', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'أرض', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'شمس', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'قمر', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'نجم', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'سماء', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'بحر', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'نهر', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'جبل', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'بيت', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'باب', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'كتاب', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'قلم', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'طاولة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'كرسي', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'سرير', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'نافذة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'غرفة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'مطبخ', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'حمام', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'طعام', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'شراب', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'خبز', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'حليب', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'شاي', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'قهوة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'تفاح', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'موز', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'برتقال', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'رجل', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'امرأة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'ولد', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'بنت', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'طفل', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'صديق', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'صديقة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'أب', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'أم', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'أخ', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'أخت', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'ابن', difficulty: 1, tags: ['noun', 'basic', 'masculine'] },
  { word: 'ابنة', difficulty: 1, tags: ['noun', 'basic', 'feminine'] },
  { word: 'جيد', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'جيدة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'كبير', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'كبيرة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'صغير', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'صغيرة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'جميل', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'جميلة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'جديد', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'جديدة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'قديم', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'قديمة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'طويل', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'طويلة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'قصير', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'قصيرة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'قليل', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'كثير', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'أول', difficulty: 1, tags: ['ordinal', 'basic', 'masculine'] },
  { word: 'أخير', difficulty: 1, tags: ['adjective', 'basic', 'masculine'] },
  { word: 'أخيرة', difficulty: 1, tags: ['adjective', 'basic', 'feminine'] },
  { word: 'أحمر', difficulty: 1, tags: ['adjective', 'basic', 'masculine', 'color'] },
  { word: 'حمراء', difficulty: 1, tags: ['adjective', 'basic', 'feminine', 'color'] },
  { word: 'أزرق', difficulty: 1, tags: ['adjective', 'basic', 'masculine', 'color'] },
  { word: 'زرقاء', difficulty: 1, tags: ['adjective', 'basic', 'feminine', 'color'] },
  { word: 'أخضر', difficulty: 1, tags: ['adjective', 'basic', 'masculine', 'color'] },
  { word: 'خضراء', difficulty: 1, tags: ['adjective', 'basic', 'feminine', 'color'] },
  { word: 'أصفر', difficulty: 1, tags: ['adjective', 'basic', 'masculine', 'color'] },
  { word: 'صفراء', difficulty: 1, tags: ['adjective', 'basic', 'feminine', 'color'] },
  { word: 'أبيض', difficulty: 1, tags: ['adjective', 'basic', 'masculine', 'color'] },
  { word: 'بيضاء', difficulty: 1, tags: ['adjective', 'basic', 'feminine', 'color'] },
  { word: 'أسود', difficulty: 1, tags: ['adjective', 'basic', 'masculine', 'color'] },
  { word: 'سوداء', difficulty: 1, tags: ['adjective', 'basic', 'feminine', 'color'] },

  // === Difficulty 2: Intermediate (Longer words with varied letter forms) ===
  { word: 'مدرسة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'education'] },
  { word: 'جامعة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'education'] },
  { word: 'مكتبة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'education'] },
  { word: 'معلم', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'education'] },
  { word: 'معلمة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'education'] },
  { word: 'طالب', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'education'] },
  { word: 'طالبة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'education'] },
  { word: 'درس', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'education'] },
  { word: 'مادة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'education'] },
  { word: 'امتحان', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'education'] },
  { word: 'واجب', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'education'] },
  { word: 'لغة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'عربية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'إنجليزية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'فرنسية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'ألمانية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'إسبانية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'صينية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'يابانية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'كورية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'روسية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'إيطالية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'برتغالية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'هندية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'تركية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'عبرية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'فارسية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'أوردية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'إندونيسية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'ماليزية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'تايلندية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'فيتنامية', difficulty: 2, tags: ['adjective', 'feminine', 'intermediate'] },
  { word: 'عمل', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'شركة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'business'] },
  { word: 'مكتب', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'business'] },
  { word: 'اجتماع', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'business'] },
  { word: 'موعد', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'ساعة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'time'] },
  { word: 'دقيقة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'time'] },
  { word: 'ثانية', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'time'] },
  { word: 'أسبوع', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'عام', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'قرن', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'عصر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'فجر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'ظهر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'مغرب', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'عشاء', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'time'] },
  { word: 'فطور', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'غداء', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'أرز', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'لحم', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'دجاج', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'سمك', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'خضار', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'فاكهة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'food'] },
  { word: 'تفاحة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'food'] },
  { word: 'برتقالة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'food'] },
  { word: 'عنب', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'تمر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'زيتون', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'جبن', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'عسل', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'سكر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'ملح', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'فلفل', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'food'] },
  { word: 'بهارات', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'food'] },
  { word: 'مدينة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'قرية', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'شارع', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'ساحة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'جسر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'سوق', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'حديقة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'مطار', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'محطة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'فندق', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'مستشفى', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'صيدلية', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'بنك', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'مطعم', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'مقهى', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'متجر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'سينما', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'مسرح', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'متحف', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'مسجد', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'كنيسة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'place'] },
  { word: 'معبد', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'place'] },
  { word: 'سيارة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'transport'] },
  { word: 'حافلة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'transport'] },
  { word: 'قطار', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'transport'] },
  { word: 'طائرة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'transport'] },
  { word: 'سفينة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'transport'] },
  { word: 'دراجة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'transport'] },
  { word: 'مترو', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'transport'] },
  { word: 'تاكسي', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'transport'] },
  { word: 'أجرة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'transport'] },
  { word: 'سفر', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'travel'] },
  { word: 'رحلة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'travel'] },
  { word: 'تأشيرة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'travel'] },
  { word: 'تذكرة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'travel'] },
  { word: 'حقيبة', difficulty: 2, tags: ['noun', 'feminine', 'intermediate', 'travel'] },
  { word: 'حجز', difficulty: 2, tags: ['noun', 'masculine', 'intermediate', 'travel'] },

  // === Difficulty 3: Advanced (Contextual letter forms) ===
  { word: 'السلام عليكم', difficulty: 3, tags: ['greeting', 'advanced', 'phrase', 'islamic'] },
  { word: 'وعليكم السلام', difficulty: 3, tags: ['greeting', 'advanced', 'phrase', 'islamic'] },
  { word: 'بسم الله الرحمن الرحيم', difficulty: 3, tags: ['phrase', 'advanced', 'islamic', 'basmala'] },
  { word: 'الحمد لله', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'إن شاء الله', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'ما شاء الله', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'سبحان الله', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'الله أكبر', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'استغفر الله', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'جزاك الله خيرا', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'بارك الله فيك', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'حياك الله', difficulty: 3, tags: ['phrase', 'advanced', 'islamic'] },
  { word: 'مرحبا بك', difficulty: 3, tags: ['greeting', 'advanced', 'phrase'] },
  { word: 'أهلا وسهلا', difficulty: 3, tags: ['greeting', 'advanced', 'phrase'] },
  { word: 'تفضل', difficulty: 3, tags: ['courtesy', 'advanced'] },
  { word: 'تفضلي', difficulty: 3, tags: ['courtesy', 'advanced', 'feminine'] },
  { word: 'مع السلامة', difficulty: 3, tags: ['farewell', 'advanced', 'phrase'] },
  { word: 'في أمان الله', difficulty: 3, tags: ['farewell', 'advanced', 'phrase', 'islamic'] },
  { word: 'إلى اللقاء', difficulty: 3, tags: ['farewell', 'advanced', 'phrase'] },
  { word: 'معذرة', difficulty: 3, tags: ['courtesy', 'advanced'] },
  { word: 'آسف', difficulty: 3, tags: ['courtesy', 'advanced', 'masculine'] },
  { word: 'آسفة', difficulty: 3, tags: ['courtesy', 'advanced', 'feminine'] },
  { word: 'مبروك', difficulty: 3, tags: ['congratulation', 'advanced'] },
  { word: 'عقبالك', difficulty: 3, tags: ['congratulation', 'advanced'] },
  { word: 'صحة وهنا', difficulty: 3, tags: ['blessing', 'advanced', 'phrase'] },
  { word: 'بالتوفيق', difficulty: 3, tags: ['blessing', 'advanced'] },
  { word: 'حظ موفق', difficulty: 3, tags: ['blessing', 'advanced', 'phrase'] },
  { word: 'فلسفة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'علم النفس', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic', 'phrase'] },
  { word: 'اجتماعيات', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'تاريخ', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'جغرافيا', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'فيزياء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'كيمياء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'أحياء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'رياضيات', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'حاسوب', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'برمجة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'هندسة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'طب', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'صيدلة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'تمريض', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'محاسبة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'حقوق', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'آداب', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'تربية', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'إعلام', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'صحافة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'فنون', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'موسيقى', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'رسم', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'تصوير', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'أدب', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'شعر', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'نثر', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'رواية', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'قصة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'مقالة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'بحث', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'دراسة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'تحليل', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'نقد', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'تفسير', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'ترجمة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'معنى', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'لفظ', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'نطق', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'كتابة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'قراءة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'استماع', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'محادثة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'مفردات', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'قواعد', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'إملاء', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'خط', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'تشكيل', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'academic'] },
  { word: 'حركات', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'academic'] },
  { word: 'ضمة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'harakat'] },
  { word: 'فتحة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'harakat'] },
  { word: 'كسرة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'harakat'] },
  { word: 'سكون', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'harakat'] },
  { word: 'شدة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'harakat'] },
  { word: 'مد', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'harakat'] },
  { word: 'تنوين', difficulty: 3, tags: ['noun', 'masculine', 'advanced', 'harakat'] },
  { word: 'همزة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'harakat'] },
  { word: 'ألف', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'باء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'تاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'ثاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'جيم', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'حاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'خاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'دال', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'ذال', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'راء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'زاي', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'سين', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'شين', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'صاد', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'ضاد', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'طاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'ظاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'عين', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'غين', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'فاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'قاف', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'كاف', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'لام', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'ميم', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'نون', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'هاء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'واو', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'ياء', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter'] },
  { word: 'تاء مربوطة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter', 'phrase'] },
  { word: 'ألف مقصورة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter', 'phrase'] },
  { word: 'ألف لينة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'letter', 'phrase'] },
  { word: 'لام شمسية', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'grammar', 'phrase'] },
  { word: 'لام قمرية', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'grammar', 'phrase'] },
  { word: 'حروف العلة', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'grammar', 'phrase'] },
  { word: 'حروف الجر', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'grammar', 'phrase'] },
  { word: 'حروف النصب', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'grammar', 'phrase'] },
  { word: 'حروف الجزم', difficulty: 3, tags: ['noun', 'feminine', 'advanced', 'grammar', 'phrase'] },
  { word: '١', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٢', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٣', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٤', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٥', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٦', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٧', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٨', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٩', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  { word: '٠', difficulty: 3, tags: ['numeral', 'advanced', 'arabic-indic'] },
  // === Classic Literature ===
  { word: 'أنا الذي نظر الأعمى إلى أدبي', difficulty: 3, tags: ['literature', 'mutanabbi'] },
  { word: 'وأسمعت كلماتي من به صمم', difficulty: 3, tags: ['literature', 'mutanabbi'] },
  { word: 'الخيل والليل والبيداء تعرفني', difficulty: 3, tags: ['literature', 'mutanabbi'] },
  { word: 'والسيف والرمح والقرطاس والقلم', difficulty: 3, tags: ['literature', 'mutanabbi'] },
  { word: 'وما نيل المطالب بالتمني', difficulty: 3, tags: ['literature', 'shawqi'] },
];

export default arabicWordlist;
