export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

export const arabicWordlist: WordlistEntry[] = [
  // Beginner (difficulty 1) — short common words
  { word: 'في', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'من', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'على', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'أن', difficulty: 1, tags: ['conjunction', 'rtl'] },
  { word: 'هذا', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'هذه', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'هو', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'هي', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'أنا', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'نحن', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'أنت', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'أنتِ', difficulty: 1, tags: ['pronoun', 'rtl'] },
  { word: 'هل', difficulty: 1, tags: ['particle', 'rtl'] },
  { word: 'لا', difficulty: 1, tags: ['negation', 'rtl'] },
  { word: 'نعم', difficulty: 1, tags: ['affirmation', 'rtl'] },
  { word: 'كان', difficulty: 1, tags: ['verb', 'rtl'] },
  { word: 'يكون', difficulty: 1, tags: ['verb', 'rtl'] },
  { word: 'له', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'لها', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'مع', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'عن', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'كل', difficulty: 1, tags: ['determiner', 'rtl'] },
  { word: 'بين', difficulty: 1, tags: ['preposition', 'rtl'] },
  { word: 'حتى', difficulty: 1, tags: ['preposition', 'rtl'] },
  // Intermediate (difficulty 2)
  { word: 'الآن', difficulty: 2, tags: ['adverb', 'rtl'] },
  { word: 'اليوم', difficulty: 2, tags: ['noun', 'rtl'] },
  { word: 'غداً', difficulty: 2, tags: ['noun', 'rtl'] },
  { word: 'سنة', difficulty: 2, tags: ['noun', 'rtl'] },
  { word: 'شخص', difficulty: 2, tags: ['noun', 'rtl'] },
  { word: 'وقت', difficulty: 2, tags: ['noun', 'rtl'] },
  { word: 'أمر', difficulty: 2, tags: ['noun', 'rtl'] },
  { word: 'بعد', difficulty: 2, tags: ['preposition', 'rtl'] },
  { word: 'قبل', difficulty: 2, tags: ['preposition', 'rtl'] },
  { word: 'عند', difficulty: 2, tags: ['preposition', 'rtl'] },
  { word: 'لم', difficulty: 2, tags: ['negation', 'rtl'] },
  { word: 'إن', difficulty: 2, tags: ['conjunction', 'rtl'] },
  { word: 'لكن', difficulty: 2, tags: ['conjunction', 'rtl'] },
  { word: 'أو', difficulty: 2, tags: ['conjunction', 'rtl'] },
  { word: 'ثم', difficulty: 2, tags: ['adverb', 'rtl'] },
  { word: 'كما', difficulty: 2, tags: ['adverb', 'rtl'] },
  { word: 'غير', difficulty: 2, tags: ['adverb', 'rtl'] },
  { word: 'جدا', difficulty: 2, tags: ['adverb', 'rtl'] },
  { word: 'كثير', difficulty: 2, tags: ['adjective', 'rtl'] },
  { word: 'صغير', difficulty: 2, tags: ['adjective', 'rtl'] },
  { word: 'كبير', difficulty: 2, tags: ['adjective', 'rtl'] },
  { word: 'جيد', difficulty: 2, tags: ['adjective', 'rtl'] },
  { word: 'جديد', difficulty: 2, tags: ['adjective', 'rtl'] },
  { word: 'قديم', difficulty: 2, tags: ['adjective', 'rtl'] },
  { word: 'أكثر', difficulty: 2, tags: ['adverb', 'rtl'] },
  { word: 'الله', difficulty: 2, tags: ['noun', 'rtl'] },
  // Advanced (difficulty 3) — words with contextual letter forms
  { word: 'الطالب', difficulty: 3, tags: ['noun', 'rtl', 'sun-letters'] },
  { word: 'الكتاب', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'الامتحان', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'البيت', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'التاريخ', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'الشمس', difficulty: 3, tags: ['noun', 'rtl', 'sun-letters'] },
  { word: 'القمر', difficulty: 3, tags: ['noun', 'rtl', 'moon-letters'] },
  { word: 'مدرسة', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'معلم', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'طالبة', difficulty: 3, tags: ['noun', 'rtl', 'sun-letters'] },
  { word: 'لغز', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'عصفور', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: 'مستشفى', difficulty: 3, tags: ['noun', 'rtl'] },
  { word: '١٢٣', difficulty: 3, tags: ['numeral', 'arabic-indic'] },
  { word: '٤٥٦', difficulty: 3, tags: ['numeral', 'arabic-indic'] },
  { word: '٧٨٩٠', difficulty: 3, tags: ['numeral', 'arabic-indic'] },
];
