/**
 * German wordlist with 210+ common words organized by difficulty
 * Includes German-specific characters: ä, ö, ü, ß
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * German wordlist - 210+ common words
 * Difficulty 1: Basic articles, pronouns, common verbs, simple words
 * Difficulty 2: Intermediate vocabulary, compound words
 * Difficulty 3: Advanced words with German-specific characters and abstract concepts
 */
export const germanWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'der', difficulty: 1, tags: ['article', 'masculine', 'basic'] },
  { word: 'die', difficulty: 1, tags: ['article', 'feminine', 'plural', 'basic'] },
  { word: 'das', difficulty: 1, tags: ['article', 'neuter', 'basic'] },
  { word: 'und', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'oder', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'ist', difficulty: 1, tags: ['verb', 'sein', 'basic'] },
  { word: 'sind', difficulty: 1, tags: ['verb', 'sein', 'plural', 'basic'] },
  { word: 'war', difficulty: 1, tags: ['verb', 'sein', 'past', 'basic'] },
  { word: 'haben', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'sein', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'werden', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'ich', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'du', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'er', difficulty: 1, tags: ['pronoun', 'masculine', 'basic'] },
  { word: 'sie', difficulty: 1, tags: ['pronoun', 'feminine', 'plural', 'basic'] },
  { word: 'es', difficulty: 1, tags: ['pronoun', 'neuter', 'basic'] },
  { word: 'wir', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'ihr', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'nicht', difficulty: 1, tags: ['adverb', 'negation', 'basic'] },
  { word: 'ein', difficulty: 1, tags: ['article', 'masculine', 'basic'] },
  { word: 'eine', difficulty: 1, tags: ['article', 'feminine', 'basic'] },
  { word: 'auch', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'so', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'sehr', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'gut', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'neu', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'alt', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'groß', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'klein', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'lang', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'kurz', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'wie', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'was', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'wer', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'wo', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'wann', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'warum', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'ja', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'nein', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'bitte', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'danke', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'guten', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'morgen', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'abend', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'nacht', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'man', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'frau', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'kind', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'mann', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'jahr', difficulty: 1, tags: ['noun', 'neuter', 'time', 'basic'] },
  { word: 'tag', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'woche', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'monat', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'stunde', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'minute', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'sekunde', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'platz', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'stadt', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'land', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'welt', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'leben', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'zeit', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'früh', difficulty: 1, tags: ['adjective', 'time', 'basic'] },
  { word: 'spät', difficulty: 1, tags: ['adjective', 'time', 'basic'] },
  { word: 'frühling', difficulty: 1, tags: ['noun', 'masculine', 'season', 'basic'] },
  { word: 'sommer', difficulty: 1, tags: ['noun', 'masculine', 'season', 'basic'] },
  { word: 'herbst', difficulty: 1, tags: ['noun', 'masculine', 'season', 'basic'] },
  { word: 'winter', difficulty: 1, tags: ['noun', 'masculine', 'season', 'basic'] },
  { word: 'heute', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'morgen', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'gestern', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'hier', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'da', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'jetzt', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'dann', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'immer', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'oft', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'viel', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'wenig', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'alle', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'viele', difficulty: 1, tags: ['adjective', 'plural', 'basic'] },

  // === Difficulty 2: Intermediate ===
  { word: 'arbeiten', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'wissen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'denken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'sprechen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'lesen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'schreiben', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'kommen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'gehen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'bleiben', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'finden', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'geben', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'zeigen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'heißen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'meinen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'sagen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'fragen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'brauchen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'verstehen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'kennen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'lernen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'fahren', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'fliegen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'schwimmen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'tanzen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'singen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'kochen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'essen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'trinken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'schlafen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'wohnen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'haus', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'auto', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'zug', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'flugzeug', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'krank', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'gesund', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'arzt', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'krankenhaus', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'schule', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'universität', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'student', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'lehrer', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'buch', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'wort', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'frage', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'antwort', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'problem', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'idee', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'musik', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'lied', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'sport', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'spielen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'laufen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'wasser', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'brot', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'fleisch', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'gemüse', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'obst', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'kaffee', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'tee', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'freund', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'familie', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'mutter', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'vater', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'bruder', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'schwester', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'computer', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'internet', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'email', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'telefon', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'geld', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'arbeit', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'straße', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'straße', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },

  // === Difficulty 3: Advanced ===
  { word: 'entwicklung', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'verantwortung', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'beziehung', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'erfahrung', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'wissen', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'umwelt', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'gesellschaft', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'demokratie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'wirtschaft', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'politik', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'kultur', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'wissenschaft', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'technologie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'forschung', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'theorie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'prozess', difficulty: 3, tags: ['noun', 'masculine', 'advanced'] },
  { word: 'produkt', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'system', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'bedingung', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'situation', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'möglichkeit', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'wirklichkeit', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'gemeinschaft', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'organisation', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'international', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'professionell', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'persönlich', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'national', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'wirtschaftlich', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'politisch', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'kulturell', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'sozial', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'historisch', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'wissenschaftlich', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'umweltbezogen', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'traditionell', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'religiös', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'grundlegend', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'bedeutsam', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'verstehen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'betrachten', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'entwickeln', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'bieten', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'fortfahren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'geschehen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'glauben', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'erwarten', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'vorschlagen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'erinnern', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'bestimmen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'beschreiben', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'erkennen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'identifizieren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'aufbauen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'herstellen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'erschaffen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'verbessern', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'erklären', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'anwenden', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'berichten', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'teilnehmen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'unterstützen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'nützen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'erreichen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'jedoch', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'daher', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'obwohl', difficulty: 3, tags: ['conjunction', 'advanced'] },
  { word: 'deshalb', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'trotzdem', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'außerdem', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'zusätzlich', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'besonders', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'ähnlich', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'verschieden', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'wichtig', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'möglich', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'notwendig', difficulty: 3, tags: ['adjective', 'advanced'] },
];

export default germanWordlist;
