/**
 * Greek wordlist with 210+ common words organized by difficulty
 * Script: Greek alphabet (α, β, γ, δ, ε, ζ, η, θ, ι, κ, λ, μ, ν, ξ, ο, π, ρ, σ, τ, υ, φ, χ, ψ, ω)
 * Uppercase/lowercase forms included where appropriate
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Greek wordlist - 210+ common words
 * Difficulty 1: Basic Greek words, high-frequency vocabulary
 * Difficulty 2: Intermediate - everyday nouns, verbs, adjectives
 * Difficulty 3: Abstract, professional, culturally specific
 */
export const greekWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner ===
  { word: 'ο', difficulty: 1, tags: ['article'] },
  { word: 'η', difficulty: 1, tags: ['article'] },
  { word: 'το', difficulty: 1, tags: ['article'] },
  { word: 'οι', difficulty: 1, tags: ['article'] },
  { word: 'του', difficulty: 1, tags: ['article'] },
  { word: 'της', difficulty: 1, tags: ['article'] },
  { word: 'του', difficulty: 1, tags: ['article'] },
  { word: 'των', difficulty: 1, tags: ['article'] },
  { word: 'ένας', difficulty: 1, tags: ['article'] },
  { word: 'μια', difficulty: 1, tags: ['article'] },
  { word: 'ένα', difficulty: 1, tags: ['article'] },
  { word: 'και', difficulty: 1, tags: ['conjunction'] },
  { word: 'ή', difficulty: 1, tags: ['conjunction'] },
  { word: 'αλλά', difficulty: 1, tags: ['conjunction'] },
  { word: 'είναι', difficulty: 1, tags: ['verb'] },
  { word: 'ήμουν', difficulty: 1, tags: ['verb'] },
  { word: 'είσαι', difficulty: 1, tags: ['verb'] },
  { word: 'ήσουν', difficulty: 1, tags: ['verb'] },
  { word: 'είμαστε', difficulty: 1, tags: ['verb'] },
  { word: 'είστε', difficulty: 1, tags: ['verb'] },
  { word: 'ήμαστε', difficulty: 1, tags: ['verb'] },
  { word: 'είχα', difficulty: 1, tags: ['verb'] },
  { word: 'είχε', difficulty: 1, tags: ['verb'] },
  { word: 'έχω', difficulty: 1, tags: ['verb'] },
  { word: 'έχει', difficulty: 1, tags: ['verb'] },
  { word: 'κάνω', difficulty: 1, tags: ['verb'] },
  { word: 'κάνει', difficulty: 1, tags: ['verb'] },
  { word: 'πάω', difficulty: 1, tags: ['verb'] },
  { word: 'πάει', difficulty: 1, tags: ['verb'] },
  { word: 'έρχομαι', difficulty: 1, tags: ['verb'] },
  { word: 'βλέπω', difficulty: 1, tags: ['verb'] },
  { word: 'λέω', difficulty: 1, tags: ['verb'] },
  { word: 'θέλω', difficulty: 1, tags: ['verb'] },
  { word: 'παίρνω', difficulty: 1, tags: ['verb'] },
  { word: 'δίνω', difficulty: 1, tags: ['verb'] },
  { word: 'μπορώ', difficulty: 1, tags: ['verb'] },
  { word: 'πρέπει', difficulty: 1, tags: ['verb'] },
  { word: 'ξέρω', difficulty: 1, tags: ['verb'] },
  { word: 'νομίζω', difficulty: 1, tags: ['verb'] },
  { word: 'εγώ', difficulty: 1, tags: ['pronoun'] },
  { word: 'εσύ', difficulty: 1, tags: ['pronoun'] },
  { word: 'αυτός', difficulty: 1, tags: ['pronoun'] },
  { word: 'αυτή', difficulty: 1, tags: ['pronoun'] },
  { word: 'αυτό', difficulty: 1, tags: ['pronoun'] },
  { word: 'εμείς', difficulty: 1, tags: ['pronoun'] },
  { word: 'εσείς', difficulty: 1, tags: ['pronoun'] },
  { word: 'αυτοί', difficulty: 1, tags: ['pronoun'] },
  { word: 'αυτές', difficulty: 1, tags: ['pronoun'] },
  { word: 'αυτά', difficulty: 1, tags: ['pronoun'] },
  { word: 'τι', difficulty: 1, tags: ['pronoun'] },
  { word: 'ποιος', difficulty: 1, tags: ['pronoun'] },
  { word: 'πού', difficulty: 1, tags: ['adverb'] },
  { word: 'πώς', difficulty: 1, tags: ['adverb'] },
  { word: 'γιατί', difficulty: 1, tags: ['adverb'] },
  { word: 'πότε', difficulty: 1, tags: ['adverb'] },
  { word: 'ναι', difficulty: 1, tags: ['adverb'] },
  { word: 'όχι', difficulty: 1, tags: ['adverb'] },
  { word: 'εδώ', difficulty: 1, tags: ['adverb'] },
  { word: 'εκεί', difficulty: 1, tags: ['adverb'] },
  { word: 'τώρα', difficulty: 1, tags: ['adverb'] },
  { word: 'μετά', difficulty: 1, tags: ['adverb'] },
  { word: 'πριν', difficulty: 1, tags: ['adverb'] },
  { word: 'πάντα', difficulty: 1, tags: ['adverb'] },
  { word: 'ποτέ', difficulty: 1, tags: ['adverb'] },
  { word: 'καλό', difficulty: 1, tags: ['adjective'] },
  { word: 'καλή', difficulty: 1, tags: ['adjective'] },
  { word: 'καλός', difficulty: 1, tags: ['adjective'] },
  { word: 'καλοί', difficulty: 1, tags: ['adjective'] },
  { word: 'καλές', difficulty: 1, tags: ['adjective'] },
  { word: 'καλά', difficulty: 1, tags: ['adjective'] },
  { word: 'καινούργιος', difficulty: 1, tags: ['adjective'] },
  { word: 'παλιός', difficulty: 1, tags: ['adjective'] },
  { word: 'μεγάλος', difficulty: 1, tags: ['adjective'] },
  { word: 'μικρός', difficulty: 1, tags: ['adjective'] },
  { word: 'ψηλός', difficulty: 1, tags: ['adjective'] },
  { word: 'κοντός', difficulty: 1, tags: ['adjective'] },
  { word: 'ένας', difficulty: 1, tags: ['number'] },
  { word: 'δύο', difficulty: 1, tags: ['number'] },
  { word: 'τρία', difficulty: 1, tags: ['number'] },
  { word: 'τέσσερα', difficulty: 1, tags: ['number'] },
  { word: 'πέντε', difficulty: 1, tags: ['number'] },
  { word: 'δέκα', difficulty: 1, tags: ['number'] },
  { word: 'εκατό', difficulty: 1, tags: ['number'] },
  { word: 'χίλια', difficulty: 1, tags: ['number'] },
  { word: 'γεια', difficulty: 1, tags: ['greeting'] },
  { word: 'γεια σου', difficulty: 1, tags: ['greeting'] },
  { word: 'αντίο', difficulty: 1, tags: ['greeting'] },
  { word: 'καλημέρα', difficulty: 1, tags: ['greeting'] },
  { word: 'καληνύχτα', difficulty: 1, tags: ['greeting'] },
  { word: 'ευχαριστώ', difficulty: 1, tags: ['greeting'] },
  { word: 'παρακαλώ', difficulty: 1, tags: ['greeting'] },

  // === Difficulty 2: Intermediate ===
  { word: 'άνθρωπος', difficulty: 2, tags: ['noun'] },
  { word: 'γυναίκα', difficulty: 2, tags: ['noun'] },
  { word: 'άντρας', difficulty: 2, tags: ['noun'] },
  { word: 'παιδί', difficulty: 2, tags: ['noun'] },
  { word: 'οικογένεια', difficulty: 2, tags: ['noun'] },
  { word: 'φίλος', difficulty: 2, tags: ['noun'] },
  { word: 'σπίτι', difficulty: 2, tags: ['noun'] },
  { word: 'δουλειά', difficulty: 2, tags: ['noun'] },
  { word: 'δρόμος', difficulty: 2, tags: ['noun'] },
  { word: 'πόλη', difficulty: 2, tags: ['noun'] },
  { word: 'χώρα', difficulty: 2, tags: ['noun'] },
  { word: 'κόσμος', difficulty: 2, tags: ['noun'] },
  { word: 'ζωή', difficulty: 2, tags: ['noun'] },
  { word: 'χρόνος', difficulty: 2, tags: ['noun'] },
  { word: 'μέρα', difficulty: 2, tags: ['noun'] },
  { word: 'νύχτα', difficulty: 2, tags: ['noun'] },
  { word: 'χέρι', difficulty: 2, tags: ['noun'] },
  { word: 'μάτι', difficulty: 2, tags: ['noun'] },
  { word: 'στόμα', difficulty: 2, tags: ['noun'] },
  { word: 'καρδιά', difficulty: 2, tags: ['noun'] },
  { word: 'κεφάλι', difficulty: 2, tags: ['noun'] },
  { word: 'πόδι', difficulty: 2, tags: ['noun'] },
  { word: 'αυτί', difficulty: 2, tags: ['noun'] },
  { word: 'μήνας', difficulty: 2, tags: ['noun'] },
  { word: 'βδομάδα', difficulty: 2, tags: ['noun'] },
  { word: 'ώρα', difficulty: 2, tags: ['noun'] },
  { word: 'λεπτό', difficulty: 2, tags: ['noun'] },
  { word: 'δευτερόλεπτο', difficulty: 2, tags: ['noun'] },
  { word: 'αριθμός', difficulty: 2, tags: ['noun'] },
  { word: 'όνομα', difficulty: 2, tags: ['noun'] },
  { word: 'βιβλίο', difficulty: 2, tags: ['education'] },
  { word: 'λέξη', difficulty: 2, tags: ['noun'] },
  { word: 'ερώτηση', difficulty: 2, tags: ['noun'] },
  { word: 'απάντηση', difficulty: 2, tags: ['noun'] },
  { word: 'πρόβλημα', difficulty: 2, tags: ['noun'] },
  { word: 'ιδέα', difficulty: 2, tags: ['noun'] },
  { word: 'σχολείο', difficulty: 2, tags: ['education'] },
  { word: 'πανεπιστήμιο', difficulty: 2, tags: ['education'] },
  { word: 'μαθητής', difficulty: 2, tags: ['education'] },
  { word: 'δάσκαλος', difficulty: 2, tags: ['education'] },
  { word: 'καθηγητής', difficulty: 2, tags: ['education'] },
  { word: 'νοσοκομείο', difficulty: 2, tags: ['health'] },
  { word: 'γιατρός', difficulty: 2, tags: ['health'] },
  { word: 'ασθένεια', difficulty: 2, tags: ['health'] },
  { word: 'υγεία', difficulty: 2, tags: ['health'] },
  { word: 'φάρμακο', difficulty: 2, tags: ['health'] },
  { word: 'τραπέζι', difficulty: 2, tags: ['noun'] },
  { word: 'καρέκλα', difficulty: 2, tags: ['noun'] },
  { word: 'παράθυρο', difficulty: 2, tags: ['noun'] },
  { word: 'πόρτα', difficulty: 2, tags: ['noun'] },
  { word: 'αυτοκίνητο', difficulty: 2, tags: ['travel'] },
  { word: 'λεωφορείο', difficulty: 2, tags: ['travel'] },
  { word: 'τρένο', difficulty: 2, tags: ['travel'] },
  { word: 'αεροπλάνο', difficulty: 2, tags: ['travel'] },
  { word: 'καφές', difficulty: 2, tags: ['food'] },
  { word: 'νερό', difficulty: 2, tags: ['food'] },
  { word: 'ψωμί', difficulty: 2, tags: ['food'] },
  { word: 'κρέας', difficulty: 2, tags: ['food'] },
  { word: 'ψάρι', difficulty: 2, tags: ['food'] },
  { word: 'λαχανικά', difficulty: 2, tags: ['food'] },
  { word: 'φρούτα', difficulty: 2, tags: ['food'] },
  { word: 'γάλα', difficulty: 2, tags: ['food'] },
  { word: 'αυγό', difficulty: 2, tags: ['food'] },
  { word: 'τσάι', difficulty: 2, tags: ['food'] },
  { word: 'κρασί', difficulty: 2, tags: ['food'] },
  { word: 'εστιατόριο', difficulty: 2, tags: ['food'] },
  { word: 'αγορά', difficulty: 2, tags: ['work'] },
  { word: 'τράπεζα', difficulty: 2, tags: ['work'] },
  { word: 'κατάστημα', difficulty: 2, tags: ['work'] },
  { word: 'γραφείο', difficulty: 2, tags: ['work'] },
  { word: 'δουλειά', difficulty: 2, tags: ['work'] },
  { word: 'χρήμα', difficulty: 2, tags: ['work'] },
  { word: 'μουσική', difficulty: 2, tags: ['art'] },
  { word: 'τραγούδι', difficulty: 2, tags: ['art'] },
  { word: 'ζωγραφική', difficulty: 2, tags: ['art'] },
  { word: 'θέατρο', difficulty: 2, tags: ['art'] },
  { word: 'κινηματογράφος', difficulty: 2, tags: ['art'] },
  { word: 'ποδόσφαιρο', difficulty: 2, tags: ['sport'] },
  { word: 'κολύμπι', difficulty: 2, tags: ['sport'] },
  { word: 'τρέξιμο', difficulty: 2, tags: ['sport'] },
  { word: 'χορός', difficulty: 2, tags: ['sport'] },
  { word: 'βουνό', difficulty: 2, tags: ['nature'] },
  { word: 'θάλασσα', difficulty: 2, tags: ['nature'] },
  { word: 'λίμνη', difficulty: 2, tags: ['nature'] },
  { word: 'ποταμός', difficulty: 2, tags: ['nature'] },
  { word: 'δάσος', difficulty: 2, tags: ['nature'] },
  { word: 'αέρας', difficulty: 2, tags: ['nature'] },
  { word: 'ήλιος', difficulty: 2, tags: ['nature'] },
  { word: 'βροχή', difficulty: 2, tags: ['nature'] },
  { word: 'χιόνι', difficulty: 2, tags: ['nature'] },
  { word: 'καιρός', difficulty: 2, tags: ['nature'] },
  { word: 'γάτα', difficulty: 2, tags: ['animal'] },
  { word: 'σκύλος', difficulty: 2, tags: ['animal'] },
  { word: 'πουλί', difficulty: 2, tags: ['animal'] },
  { word: 'ψάρι', difficulty: 2, tags: ['animal'] },
  { word: 'άλογο', difficulty: 2, tags: ['animal'] },
  { word: 'δέντρο', difficulty: 2, tags: ['nature'] },
  { word: 'λουλούδι', difficulty: 2, tags: ['nature'] },
  { word: 'τηλέφωνο', difficulty: 2, tags: ['technology'] },
  { word: 'υπολογιστής', difficulty: 2, tags: ['technology'] },
  { word: 'ίντερνετ', difficulty: 2, tags: ['technology'] },
  { word: 'email', difficulty: 2, tags: ['technology'] },
  { word: 'τηλεόραση', difficulty: 2, tags: ['technology'] },
  { word: 'ευτυχισμένος', difficulty: 2, tags: ['emotion'] },
  { word: 'λυπημένος', difficulty: 2, tags: ['emotion'] },
  { word: 'θυμωμένος', difficulty: 2, tags: ['emotion'] },
  { word: 'κουρασμένος', difficulty: 2, tags: ['emotion'] },
  { word: 'γρήγορος', difficulty: 2, tags: ['adjective'] },
  { word: 'αργός', difficulty: 2, tags: ['adjective'] },
  { word: 'εύκολος', difficulty: 2, tags: ['adjective'] },
  { word: 'δύσκολος', difficulty: 2, tags: ['adjective'] },
  { word: 'ακριβός', difficulty: 2, tags: ['adjective'] },
  { word: 'φθηνός', difficulty: 2, tags: ['adjective'] },
  { word: 'ωραίος', difficulty: 2, tags: ['adjective'] },
  { word: 'άσχημος', difficulty: 2, tags: ['adjective'] },
  { word: 'πλούσιος', difficulty: 2, tags: ['adjective'] },
  { word: 'φτωχός', difficulty: 2, tags: ['adjective'] },

  // === Difficulty 3: Advanced ===
  { word: 'δημοκρατία', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'κυβέρνηση', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'πολιτική', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'οικονομία', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'εκλογές', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'κοινωνία', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'δικαιώματα', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'νόμος', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'επιστήμη', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'τεχνολογία', difficulty: 3, tags: ['noun', 'technology'] },
  { word: 'έρευνα', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'θεωρία', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'ανάλυση', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'πείραμα', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'διαδικασία', difficulty: 3, tags: ['noun'] },
  { word: 'προϊόν', difficulty: 3, tags: ['noun'] },
  { word: 'σύστημα', difficulty: 3, tags: ['noun'] },
  { word: 'κατάσταση', difficulty: 3, tags: ['noun'] },
  { word: 'πραγματικότητα', difficulty: 3, tags: ['noun'] },
  { word: 'δυνατότητα', difficulty: 3, tags: ['noun'] },
  { word: 'ανάγκη', difficulty: 3, tags: ['noun'] },
  { word: 'ευκαιρία', difficulty: 3, tags: ['noun'] },
  { word: 'ευθύνη', difficulty: 3, tags: ['noun'] },
  { word: 'σχέση', difficulty: 3, tags: ['noun'] },
  { word: 'εμπειρία', difficulty: 3, tags: ['noun'] },
  { word: 'γνώση', difficulty: 3, tags: ['noun'] },
  { word: 'περιβάλλον', difficulty: 3, tags: ['noun'] },
  { word: 'καλλιέργεια', difficulty: 3, tags: ['noun'] },
  { word: 'πολιτισμός', difficulty: 3, tags: ['noun'] },
  { word: 'ιστορία', difficulty: 3, tags: ['noun'] },
  { word: 'φιλοσοφία', difficulty: 3, tags: ['noun'] },
  { word: 'μυθολογία', difficulty: 3, tags: ['noun'] },
  { word: 'διεθνής', difficulty: 3, tags: ['adjective'] },
  { word: 'επαγγελματικός', difficulty: 3, tags: ['adjective'] },
  { word: 'προσωπικός', difficulty: 3, tags: ['adjective'] },
  { word: 'εθνικός', difficulty: 3, tags: ['adjective'] },
  { word: 'οικονομικός', difficulty: 3, tags: ['adjective'] },
  { word: 'πολιτικός', difficulty: 3, tags: ['adjective'] },
  { word: 'πολιτιστικός', difficulty: 3, tags: ['adjective'] },
  { word: 'κοινωνικός', difficulty: 3, tags: ['adjective'] },
  { word: 'ιστορικός', difficulty: 3, tags: ['adjective'] },
  { word: 'επιστημονικός', difficulty: 3, tags: ['adjective'] },
  { word: 'περιβαλλοντικός', difficulty: 3, tags: ['adjective'] },
  { word: 'παραδοσιακός', difficulty: 3, tags: ['adjective'] },
  { word: 'θρησκευτικός', difficulty: 3, tags: ['adjective'] },
  { word: 'θεμελιώδης', difficulty: 3, tags: ['adjective'] },
  { word: 'σημαντικός', difficulty: 3, tags: ['adjective'] },
  { word: 'κατανοώ', difficulty: 3, tags: ['verb'] },
  { word: 'εξετάζω', difficulty: 3, tags: ['verb'] },
  { word: 'αναπτύσσω', difficulty: 3, tags: ['verb'] },
  { word: 'παρέχω', difficulty: 3, tags: ['verb'] },
  { word: 'συνεχίζω', difficulty: 3, tags: ['verb'] },
  { word: 'συμβαίνω', difficulty: 3, tags: ['verb'] },
  { word: 'πιστεύω', difficulty: 3, tags: ['verb'] },
  { word: 'αναμένω', difficulty: 3, tags: ['verb'] },
  { word: 'προτείνω', difficulty: 3, tags: ['verb'] },
  { word: 'θυμάμαι', difficulty: 3, tags: ['verb'] },
  { word: 'καθορίζω', difficulty: 3, tags: ['verb'] },
  { word: 'περιγράφω', difficulty: 3, tags: ['verb'] },
  { word: 'αναγνωρίζω', difficulty: 3, tags: ['verb'] },
  { word: 'ταυτοποιώ', difficulty: 3, tags: ['verb'] },
  { word: 'εγκαθιδρύω', difficulty: 3, tags: ['verb'] },
  { word: 'παράγω', difficulty: 3, tags: ['verb'] },
  { word: 'δημιουργώ', difficulty: 3, tags: ['verb'] },
  { word: 'βελτιώνω', difficulty: 3, tags: ['verb'] },
  { word: 'εξηγώ', difficulty: 3, tags: ['verb'] },
  { word: 'εφαρμόζω', difficulty: 3, tags: ['verb'] },
  { word: 'αναφέρω', difficulty: 3, tags: ['verb'] },
  { word: 'συμμετέχω', difficulty: 3, tags: ['verb'] },
  { word: 'υποστηρίζω', difficulty: 3, tags: ['verb'] },
  { word: 'επωφελούμαι', difficulty: 3, tags: ['verb'] },
  { word: 'επιτυγχάνω', difficulty: 3, tags: ['verb'] },
  { word: 'ωστόσο', difficulty: 3, tags: ['adverb'] },
  { word: 'επομένως', difficulty: 3, tags: ['adverb'] },
  { word: 'μολονότι', difficulty: 3, tags: ['conjunction'] },
  { word: 'Σωκράτης', difficulty: 3, tags: ['noun'] },
  { word: 'Πλάτων', difficulty: 3, tags: ['noun'] },
  { word: 'Αριστοτέλης', difficulty: 3, tags: ['noun'] },
  { word: 'Ολυμπία', difficulty: 3, tags: ['noun'] },
  { word: 'Κορίνθος', difficulty: 3, tags: ['noun'] },
  { word: 'Αθήνα', difficulty: 3, tags: ['noun'] },
];

export default greekWordlist;
