/**
 * English wordlist with 210+ common words organized by difficulty
 * Covers everyday vocabulary across semantic domains
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * English wordlist - 210+ common words
 * Difficulty 1: Basic articles, pronouns, verbs, prepositions, simple words
 * Difficulty 2: Intermediate vocabulary - everyday nouns, adjectives, verbs
 * Difficulty 3: Abstract, professional, and culturally specific vocabulary
 */
export const englishWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner ===
  { word: 'the', difficulty: 1, tags: ['article'] },
  { word: 'a', difficulty: 1, tags: ['article'] },
  { word: 'an', difficulty: 1, tags: ['article'] },
  { word: 'of', difficulty: 1, tags: ['preposition'] },
  { word: 'to', difficulty: 1, tags: ['preposition'] },
  { word: 'in', difficulty: 1, tags: ['preposition'] },
  { word: 'for', difficulty: 1, tags: ['preposition'] },
  { word: 'on', difficulty: 1, tags: ['preposition'] },
  { word: 'with', difficulty: 1, tags: ['preposition'] },
  { word: 'at', difficulty: 1, tags: ['preposition'] },
  { word: 'by', difficulty: 1, tags: ['preposition'] },
  { word: 'from', difficulty: 1, tags: ['preposition'] },
  { word: 'and', difficulty: 1, tags: ['conjunction'] },
  { word: 'or', difficulty: 1, tags: ['conjunction'] },
  { word: 'but', difficulty: 1, tags: ['conjunction'] },
  { word: 'is', difficulty: 1, tags: ['verb'] },
  { word: 'are', difficulty: 1, tags: ['verb'] },
  { word: 'was', difficulty: 1, tags: ['verb'] },
  { word: 'were', difficulty: 1, tags: ['verb'] },
  { word: 'be', difficulty: 1, tags: ['verb'] },
  { word: 'have', difficulty: 1, tags: ['verb'] },
  { word: 'has', difficulty: 1, tags: ['verb'] },
  { word: 'had', difficulty: 1, tags: ['verb'] },
  { word: 'do', difficulty: 1, tags: ['verb'] },
  { word: 'does', difficulty: 1, tags: ['verb'] },
  { word: 'did', difficulty: 1, tags: ['verb'] },
  { word: 'will', difficulty: 1, tags: ['verb'] },
  { word: 'would', difficulty: 1, tags: ['verb'] },
  { word: 'could', difficulty: 1, tags: ['verb'] },
  { word: 'can', difficulty: 1, tags: ['verb'] },
  { word: 'i', difficulty: 1, tags: ['pronoun'] },
  { word: 'you', difficulty: 1, tags: ['pronoun'] },
  { word: 'he', difficulty: 1, tags: ['pronoun'] },
  { word: 'she', difficulty: 1, tags: ['pronoun'] },
  { word: 'it', difficulty: 1, tags: ['pronoun'] },
  { word: 'we', difficulty: 1, tags: ['pronoun'] },
  { word: 'they', difficulty: 1, tags: ['pronoun'] },
  { word: 'me', difficulty: 1, tags: ['pronoun'] },
  { word: 'him', difficulty: 1, tags: ['pronoun'] },
  { word: 'her', difficulty: 1, tags: ['pronoun'] },
  { word: 'us', difficulty: 1, tags: ['pronoun'] },
  { word: 'them', difficulty: 1, tags: ['pronoun'] },
  { word: 'my', difficulty: 1, tags: ['determiner'] },
  { word: 'your', difficulty: 1, tags: ['determiner'] },
  { word: 'his', difficulty: 1, tags: ['determiner'] },
  { word: 'its', difficulty: 1, tags: ['determiner'] },
  { word: 'our', difficulty: 1, tags: ['determiner'] },
  { word: 'their', difficulty: 1, tags: ['determiner'] },
  { word: 'this', difficulty: 1, tags: ['determiner'] },
  { word: 'that', difficulty: 1, tags: ['determiner'] },
  { word: 'these', difficulty: 1, tags: ['determiner'] },
  { word: 'those', difficulty: 1, tags: ['determiner'] },
  { word: 'not', difficulty: 1, tags: ['adverb'] },
  { word: 'yes', difficulty: 1, tags: ['adverb'] },
  { word: 'no', difficulty: 1, tags: ['adverb'] },
  { word: 'very', difficulty: 1, tags: ['adverb'] },
  { word: 'so', difficulty: 1, tags: ['adverb'] },
  { word: 'just', difficulty: 1, tags: ['adverb'] },
  { word: 'all', difficulty: 1, tags: ['determiner'] },
  { word: 'now', difficulty: 1, tags: ['time'] },
  { word: 'then', difficulty: 1, tags: ['time'] },
  { word: 'here', difficulty: 1, tags: ['adverb'] },
  { word: 'there', difficulty: 1, tags: ['adverb'] },
  { word: 'good', difficulty: 1, tags: ['adjective'] },
  { word: 'new', difficulty: 1, tags: ['adjective'] },
  { word: 'old', difficulty: 1, tags: ['adjective'] },
  { word: 'big', difficulty: 1, tags: ['adjective'] },
  { word: 'small', difficulty: 1, tags: ['adjective'] },
  { word: 'first', difficulty: 1, tags: ['number'] },
  { word: 'last', difficulty: 1, tags: ['number'] },
  { word: 'one', difficulty: 1, tags: ['number'] },
  { word: 'two', difficulty: 1, tags: ['number'] },
  { word: 'three', difficulty: 1, tags: ['number'] },
  { word: 'hello', difficulty: 1, tags: ['greeting'] },
  { word: 'bye', difficulty: 1, tags: ['greeting'] },

  // === Difficulty 2: Intermediate ===
  { word: 'about', difficulty: 2, tags: ['preposition'] },
  { word: 'after', difficulty: 2, tags: ['preposition'] },
  { word: 'before', difficulty: 2, tags: ['preposition'] },
  { word: 'into', difficulty: 2, tags: ['preposition'] },
  { word: 'always', difficulty: 2, tags: ['adverb'] },
  { word: 'never', difficulty: 2, tags: ['adverb'] },
  { word: 'often', difficulty: 2, tags: ['adverb'] },
  { word: 'really', difficulty: 2, tags: ['adverb'] },
  { word: 'week', difficulty: 2, tags: ['time'] },
  { word: 'month', difficulty: 2, tags: ['time'] },
  { word: 'year', difficulty: 2, tags: ['time'] },
  { word: 'hour', difficulty: 2, tags: ['time'] },
  { word: 'home', difficulty: 2, tags: ['noun'] },
  { word: 'house', difficulty: 2, tags: ['noun'] },
  { word: 'family', difficulty: 2, tags: ['noun'] },
  { word: 'friend', difficulty: 2, tags: ['noun'] },
  { word: 'work', difficulty: 2, tags: ['work'] },
  { word: 'job', difficulty: 2, tags: ['work'] },
  { word: 'money', difficulty: 2, tags: ['noun'] },
  { word: 'man', difficulty: 2, tags: ['noun'] },
  { word: 'woman', difficulty: 2, tags: ['noun'] },
  { word: 'child', difficulty: 2, tags: ['noun'] },
  { word: 'people', difficulty: 2, tags: ['noun'] },
  { word: 'world', difficulty: 2, tags: ['noun'] },
  { word: 'life', difficulty: 2, tags: ['noun'] },
  { word: 'day', difficulty: 2, tags: ['noun'] },
  { word: 'night', difficulty: 2, tags: ['time'] },
  { word: 'school', difficulty: 2, tags: ['education'] },
  { word: 'student', difficulty: 2, tags: ['education'] },
  { word: 'teacher', difficulty: 2, tags: ['education'] },
  { word: 'book', difficulty: 2, tags: ['education'] },
  { word: 'word', difficulty: 2, tags: ['noun'] },
  { word: 'question', difficulty: 2, tags: ['noun'] },
  { word: 'answer', difficulty: 2, tags: ['noun'] },
  { word: 'problem', difficulty: 2, tags: ['noun'] },
  { word: 'idea', difficulty: 2, tags: ['noun'] },
  { word: 'thing', difficulty: 2, tags: ['noun'] },
  { word: 'food', difficulty: 2, tags: ['food'] },
  { word: 'water', difficulty: 2, tags: ['food'] },
  { word: 'car', difficulty: 2, tags: ['travel'] },
  { word: 'bus', difficulty: 2, tags: ['travel'] },
  { word: 'train', difficulty: 2, tags: ['travel'] },
  { word: 'city', difficulty: 2, tags: ['geography'] },
  { word: 'country', difficulty: 2, tags: ['geography'] },
  { word: 'change', difficulty: 2, tags: ['verb'] },
  { word: 'look', difficulty: 2, tags: ['verb'] },
  { word: 'think', difficulty: 2, tags: ['verb'] },
  { word: 'know', difficulty: 2, tags: ['verb'] },
  { word: 'want', difficulty: 2, tags: ['verb'] },
  { word: 'need', difficulty: 2, tags: ['verb'] },
  { word: 'feel', difficulty: 2, tags: ['verb'] },
  { word: 'see', difficulty: 2, tags: ['verb'] },
  { word: 'hear', difficulty: 2, tags: ['verb'] },
  { word: 'make', difficulty: 2, tags: ['verb'] },
  { word: 'give', difficulty: 2, tags: ['verb'] },
  { word: 'take', difficulty: 2, tags: ['verb'] },
  { word: 'get', difficulty: 2, tags: ['verb'] },
  { word: 'come', difficulty: 2, tags: ['verb'] },
  { word: 'go', difficulty: 2, tags: ['verb'] },
  { word: 'tell', difficulty: 2, tags: ['verb'] },
  { word: 'ask', difficulty: 2, tags: ['verb'] },
  { word: 'use', difficulty: 2, tags: ['verb'] },
  { word: 'find', difficulty: 2, tags: ['verb'] },
  { word: 'happy', difficulty: 2, tags: ['emotion'] },
  { word: 'sad', difficulty: 2, tags: ['emotion'] },
  { word: 'love', difficulty: 2, tags: ['emotion'] },
  { word: 'music', difficulty: 2, tags: ['art'] },
  { word: 'song', difficulty: 2, tags: ['art'] },
  { word: 'play', difficulty: 2, tags: ['sport'] },
  { word: 'run', difficulty: 2, tags: ['sport'] },
  { word: 'read', difficulty: 2, tags: ['education'] },
  { word: 'write', difficulty: 2, tags: ['education'] },
  { word: 'learn', difficulty: 2, tags: ['education'] },
  { word: 'doctor', difficulty: 2, tags: ['health'] },
  { word: 'sick', difficulty: 2, tags: ['health'] },
  { word: 'rain', difficulty: 2, tags: ['nature'] },
  { word: 'sun', difficulty: 2, tags: ['nature'] },
  { word: 'tree', difficulty: 2, tags: ['nature'] },
  { word: 'animal', difficulty: 2, tags: ['animal'] },
  { word: 'dog', difficulty: 2, tags: ['animal'] },
  { word: 'cat', difficulty: 2, tags: ['animal'] },
  { word: 'bird', difficulty: 2, tags: ['animal'] },
  { word: 'phone', difficulty: 2, tags: ['technology'] },
  { word: 'computer', difficulty: 2, tags: ['technology'] },
  { word: 'internet', difficulty: 2, tags: ['technology'] },
  { word: 'email', difficulty: 2, tags: ['technology'] },
  { word: 'room', difficulty: 2, tags: ['noun'] },
  { word: 'door', difficulty: 2, tags: ['noun'] },
  { word: 'table', difficulty: 2, tags: ['noun'] },
  { word: 'chair', difficulty: 2, tags: ['noun'] },
  { word: 'important', difficulty: 2, tags: ['adjective'] },
  { word: 'different', difficulty: 2, tags: ['adjective'] },
  { word: 'possible', difficulty: 2, tags: ['adjective'] },
  { word: 'father', difficulty: 2, tags: ['family'] },
  { word: 'mother', difficulty: 2, tags: ['family'] },
  { word: 'brother', difficulty: 2, tags: ['family'] },
  { word: 'sister', difficulty: 2, tags: ['family'] },
  { word: 'white', difficulty: 2, tags: ['adjective'] },
  { word: 'black', difficulty: 2, tags: ['adjective'] },
  { word: 'red', difficulty: 2, tags: ['adjective'] },
  { word: 'blue', difficulty: 2, tags: ['adjective'] },
  { word: 'green', difficulty: 2, tags: ['adjective'] },
  { word: 'group', difficulty: 2, tags: ['noun'] },
  { word: 'team', difficulty: 2, tags: ['noun'] },
  { word: 'market', difficulty: 2, tags: ['work'] },
  { word: 'company', difficulty: 2, tags: ['work'] },
  { word: 'area', difficulty: 2, tags: ['geography'] },
  { word: 'river', difficulty: 2, tags: ['nature'] },
  { word: 'sea', difficulty: 2, tags: ['nature'] },
  { word: 'mountain', difficulty: 2, tags: ['nature'] },

  // === Difficulty 3: Advanced ===
  { word: 'opportunity', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'responsibility', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'relationship', difficulty: 3, tags: ['noun', 'emotion'] },
  { word: 'development', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'experience', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'knowledge', difficulty: 3, tags: ['noun', 'education'] },
  { word: 'environment', difficulty: 3, tags: ['noun', 'nature'] },
  { word: 'government', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'society', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'democracy', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'election', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'economy', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'culture', difficulty: 3, tags: ['noun', 'art'] },
  { word: 'history', difficulty: 3, tags: ['noun', 'education'] },
  { word: 'science', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'technology', difficulty: 3, tags: ['noun', 'technology'] },
  { word: 'research', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'theory', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'process', difficulty: 3, tags: ['noun'] },
  { word: 'product', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'system', difficulty: 3, tags: ['noun', 'technology'] },
  { word: 'condition', difficulty: 3, tags: ['noun'] },
  { word: 'situation', difficulty: 3, tags: ['noun'] },
  { word: 'possibility', difficulty: 3, tags: ['noun'] },
  { word: 'reality', difficulty: 3, tags: ['noun', 'abstract'] },
  { word: 'community', difficulty: 3, tags: ['noun', 'abstract'] },
  { word: 'organization', difficulty: 3, tags: ['noun', 'abstract'] },
  { word: 'international', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'professional', difficulty: 3, tags: ['adjective', 'work'] },
  { word: 'personal', difficulty: 3, tags: ['adjective'] },
  { word: 'national', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'economic', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'political', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'cultural', difficulty: 3, tags: ['adjective', 'art'] },
  { word: 'social', difficulty: 3, tags: ['adjective'] },
  { word: 'historical', difficulty: 3, tags: ['adjective', 'education'] },
  { word: 'scientific', difficulty: 3, tags: ['adjective', 'science'] },
  { word: 'environmental', difficulty: 3, tags: ['adjective', 'nature'] },
  { word: 'traditional', difficulty: 3, tags: ['adjective'] },
  { word: 'religious', difficulty: 3, tags: ['adjective', 'religion'] },
  { word: 'fundamental', difficulty: 3, tags: ['adjective'] },
  { word: 'significant', difficulty: 3, tags: ['adjective'] },
  { word: 'understand', difficulty: 3, tags: ['verb'] },
  { word: 'consider', difficulty: 3, tags: ['verb'] },
  { word: 'develop', difficulty: 3, tags: ['verb'] },
  { word: 'provide', difficulty: 3, tags: ['verb'] },
  { word: 'continue', difficulty: 3, tags: ['verb'] },
  { word: 'happen', difficulty: 3, tags: ['verb'] },
  { word: 'believe', difficulty: 3, tags: ['verb'] },
  { word: 'expect', difficulty: 3, tags: ['verb'] },
  { word: 'suggest', difficulty: 3, tags: ['verb'] },
  { word: 'remember', difficulty: 3, tags: ['verb'] },
  { word: 'determine', difficulty: 3, tags: ['verb'] },
  { word: 'describe', difficulty: 3, tags: ['verb'] },
  { word: 'recognize', difficulty: 3, tags: ['verb'] },
  { word: 'identify', difficulty: 3, tags: ['verb'] },
  { word: 'establish', difficulty: 3, tags: ['verb'] },
  { word: 'produce', difficulty: 3, tags: ['verb'] },
  { word: 'create', difficulty: 3, tags: ['verb'] },
  { word: 'complete', difficulty: 3, tags: ['verb'] },
  { word: 'improve', difficulty: 3, tags: ['verb'] },
  { word: 'explain', difficulty: 3, tags: ['verb'] },
  { word: 'apply', difficulty: 3, tags: ['verb'] },
  { word: 'report', difficulty: 3, tags: ['verb'] },
  { word: 'participate', difficulty: 3, tags: ['verb'] },
  { word: 'support', difficulty: 3, tags: ['verb'] },
  { word: 'benefit', difficulty: 3, tags: ['verb'] },
  { word: 'achieve', difficulty: 3, tags: ['verb'] },
  { word: 'however', difficulty: 3, tags: ['adverb'] },
  { word: 'therefore', difficulty: 3, tags: ['adverb'] },
  { word: 'although', difficulty: 3, tags: ['conjunction'] },
];

export default englishWordlist;
