/**
 * English wordlist with 300+ common words organised by difficulty
 * Covers all 26 keys and common bigrams for targeted drill generation
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * English wordlist
 * Difficulty 1: High-frequency words, home-row heavy, short (2–4 chars)
 * Difficulty 2: Common words, all rows, medium length (4–7 chars)
 * Difficulty 3: Less common, longer words, punctuation-adjacent patterns
 */
export const englishWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner ===
  { word: 'the', difficulty: 1, tags: ['article', 'high-frequency', 'home-row'] },
  { word: 'and', difficulty: 1, tags: ['conjunction', 'high-frequency'] },
  { word: 'for', difficulty: 1, tags: ['preposition', 'high-frequency'] },
  { word: 'are', difficulty: 1, tags: ['verb', 'high-frequency', 'home-row'] },
  { word: 'but', difficulty: 1, tags: ['conjunction', 'high-frequency'] },
  { word: 'not', difficulty: 1, tags: ['adverb', 'high-frequency'] },
  { word: 'you', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'all', difficulty: 1, tags: ['determiner', 'high-frequency', 'home-row'] },
  { word: 'can', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'her', difficulty: 1, tags: ['pronoun', 'high-frequency', 'home-row'] },
  { word: 'was', difficulty: 1, tags: ['verb', 'high-frequency', 'home-row'] },
  { word: 'one', difficulty: 1, tags: ['number', 'high-frequency'] },
  { word: 'our', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'out', difficulty: 1, tags: ['adverb', 'high-frequency'] },
  { word: 'who', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'get', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'his', difficulty: 1, tags: ['pronoun', 'high-frequency', 'home-row'] },
  { word: 'him', difficulty: 1, tags: ['pronoun', 'high-frequency', 'home-row'] },
  { word: 'has', difficulty: 1, tags: ['verb', 'high-frequency', 'home-row'] },
  { word: 'had', difficulty: 1, tags: ['verb', 'high-frequency', 'home-row'] },
  { word: 'did', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'its', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'let', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'put', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'say', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'she', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'too', difficulty: 1, tags: ['adverb', 'high-frequency'] },
  { word: 'use', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'way', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'day', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'see', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'now', difficulty: 1, tags: ['adverb', 'high-frequency'] },
  { word: 'how', difficulty: 1, tags: ['adverb', 'high-frequency'] },
  { word: 'new', difficulty: 1, tags: ['adjective', 'high-frequency'] },
  { word: 'old', difficulty: 1, tags: ['adjective', 'high-frequency', 'home-row'] },
  { word: 'add', difficulty: 1, tags: ['verb', 'home-row'] },
  { word: 'set', difficulty: 1, tags: ['verb', 'home-row'] },
  { word: 'ash', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'fade', difficulty: 1, tags: ['verb', 'home-row'] },
  { word: 'safe', difficulty: 1, tags: ['adjective', 'home-row'] },
  { word: 'sale', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'dale', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'jade', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'hall', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'fall', difficulty: 1, tags: ['verb', 'home-row'] },
  { word: 'dash', difficulty: 1, tags: ['verb', 'home-row'] },
  { word: 'glad', difficulty: 1, tags: ['adjective', 'home-row'] },
  { word: 'flag', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'flask', difficulty: 1, tags: ['noun', 'home-row'] },
  { word: 'shall', difficulty: 1, tags: ['modal', 'home-row'] },

  // === Difficulty 2: Intermediate ===
  { word: 'about', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'after', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'again', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'along', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'asked', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'being', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'below', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'better', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'bring', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'build', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'carry', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'cause', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'change', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'check', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'clear', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'close', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'could', difficulty: 2, tags: ['modal', 'common'] },
  { word: 'cover', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'cross', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'drive', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'early', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'earth', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'eight', difficulty: 2, tags: ['number', 'common'] },
  { word: 'every', difficulty: 2, tags: ['determiner', 'common'] },
  { word: 'face', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'feet', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'find', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'fire', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'five', difficulty: 2, tags: ['number', 'common'] },
  { word: 'food', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'four', difficulty: 2, tags: ['number', 'common'] },
  { word: 'from', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'full', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'give', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'given', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'going', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'great', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'group', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'grown', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'hands', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'heart', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'heavy', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'help', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'here', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'high', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'hold', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'home', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'hope', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'hour', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'idea', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'into', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'just', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'keep', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kind', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'knew', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'know', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'large', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'last', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'late', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'learn', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'left', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'life', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'like', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'line', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'list', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'live', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'long', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'look', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'made', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'main', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'make', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'many', difficulty: 2, tags: ['determiner', 'common'] },
  { word: 'mark', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'mean', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'mind', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'more', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'most', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'move', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'much', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'must', difficulty: 2, tags: ['modal', 'common'] },
  { word: 'name', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'near', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'need', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'next', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'night', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'nine', difficulty: 2, tags: ['number', 'common'] },
  { word: 'only', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'open', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'over', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'page', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'part', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'pass', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'past', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'path', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'plan', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'play', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'point', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'poor', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'push', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'read', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'real', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'rest', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'rich', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'road', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'role', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'room', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'root', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'rule', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'same', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'send', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'ship', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'show', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'side', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'sign', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'site', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'size', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'slow', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'small', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'soft', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'some', difficulty: 2, tags: ['determiner', 'common'] },
  { word: 'song', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'soon', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'sort', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'soul', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'star', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'stay', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'step', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'stop', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'such', difficulty: 2, tags: ['determiner', 'common'] },
  { word: 'sure', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'take', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'talk', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'tell', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'than', difficulty: 2, tags: ['conjunction', 'common'] },
  { word: 'that', difficulty: 2, tags: ['conjunction', 'common'] },
  { word: 'them', difficulty: 2, tags: ['pronoun', 'common'] },
  { word: 'then', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'they', difficulty: 2, tags: ['pronoun', 'common'] },
  { word: 'this', difficulty: 2, tags: ['determiner', 'common'] },
  { word: 'time', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'told', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'took', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'tree', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'true', difficulty: 2, tags: ['adjective', 'common'] },
  { word: 'turn', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'type', difficulty: 2, tags: ['noun', 'typing'] },
  { word: 'under', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'upon', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'very', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'view', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'walk', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'want', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'well', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'went', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'were', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'what', difficulty: 2, tags: ['pronoun', 'common'] },
  { word: 'when', difficulty: 2, tags: ['adverb', 'common'] },
  { word: 'will', difficulty: 2, tags: ['modal', 'common'] },
  { word: 'with', difficulty: 2, tags: ['preposition', 'common'] },
  { word: 'word', difficulty: 2, tags: ['noun', 'common', 'typing'] },
  { word: 'work', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'year', difficulty: 2, tags: ['noun', 'common'] },
  { word: 'your', difficulty: 2, tags: ['pronoun', 'common'] },

  // === Difficulty 3: Advanced ===
  { word: 'achieve', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'accuracy', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'approach', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'between', difficulty: 3, tags: ['preposition', 'advanced'] },
  { word: 'breathe', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'complete', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'complex', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'correct', difficulty: 3, tags: ['adjective', 'typing'] },
  { word: 'control', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'design', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'develop', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'different', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'digital', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'dynamic', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'efficient', difficulty: 3, tags: ['adjective', 'typing'] },
  { word: 'either', difficulty: 3, tags: ['conjunction', 'advanced'] },
  { word: 'enforce', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'example', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'exercise', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'expect', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'express', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'feature', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'finger', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'fluency', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'forward', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'function', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'improve', difficulty: 3, tags: ['verb', 'typing'] },
  { word: 'include', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'increase', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'keyboard', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'language', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'lesson', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'letters', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'logical', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'manage', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'master', difficulty: 3, tags: ['verb', 'typing'] },
  { word: 'measure', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'method', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'minutes', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'mistake', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'network', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'nothing', difficulty: 3, tags: ['pronoun', 'advanced'] },
  { word: 'pattern', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'perfect', difficulty: 3, tags: ['adjective', 'typing'] },
  { word: 'perform', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'practice', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'precise', difficulty: 3, tags: ['adjective', 'typing'] },
  { word: 'process', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'produce', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'program', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'progress', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'project', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'quality', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'quickly', difficulty: 3, tags: ['adverb', 'typing'] },
  { word: 'realize', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'receive', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'require', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'results', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'rhythm', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'session', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'service', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'should', difficulty: 3, tags: ['modal', 'advanced'] },
  { word: 'skills', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'software', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'special', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'speed', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'strategy', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'strength', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'structure', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'support', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'system', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'target', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'technique', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'thought', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'through', difficulty: 3, tags: ['preposition', 'advanced'] },
  { word: 'together', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'training', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'trigger', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'typing', difficulty: 3, tags: ['noun', 'typing'] },
  { word: 'unique', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'update', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'useful', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'various', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'version', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'visible', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'whether', difficulty: 3, tags: ['conjunction', 'advanced'] },
  { word: 'without', difficulty: 3, tags: ['preposition', 'advanced'] },
  { word: 'wonder', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'written', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'xylophone', difficulty: 3, tags: ['noun', 'x-key'] },
  { word: 'yourself', difficulty: 3, tags: ['pronoun', 'advanced'] },
  { word: 'zealous', difficulty: 3, tags: ['adjective', 'z-key'] },
];
