export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

export const spanishWordlist: WordlistEntry[] = [
  // Beginner (difficulty 1)
  { word: 'el', difficulty: 1, tags: ['article'] },
  { word: 'la', difficulty: 1, tags: ['article'] },
  { word: 'un', difficulty: 1, tags: ['article'] },
  { word: 'una', difficulty: 1, tags: ['article'] },
  { word: 'de', difficulty: 1, tags: ['preposition'] },
  { word: 'y', difficulty: 1, tags: ['conjunction'] },
  { word: 'es', difficulty: 1, tags: ['verb'] },
  { word: 'en', difficulty: 1, tags: ['preposition'] },
  { word: 'que', difficulty: 1, tags: ['conjunction'] },
  { word: 'se', difficulty: 1, tags: ['pronoun'] },
  { word: 'no', difficulty: 1, tags: ['adverb'] },
  { word: 'los', difficulty: 1, tags: ['article'] },
  { word: 'las', difficulty: 1, tags: ['article'] },
  { word: 'del', difficulty: 1, tags: ['contraction'] },
  { word: 'al', difficulty: 1, tags: ['contraction'] },
  { word: 'por', difficulty: 1, tags: ['preposition'] },
  { word: 'con', difficulty: 1, tags: ['preposition'] },
  { word: 'para', difficulty: 1, tags: ['preposition'] },
  { word: 'su', difficulty: 1, tags: ['possessive'] },
  { word: 'mi', difficulty: 1, tags: ['possessive'] },
  { word: 'tu', difficulty: 1, tags: ['possessive'] },
  { word: 'yo', difficulty: 1, tags: ['pronoun'] },
  { word: 'tu', difficulty: 1, tags: ['pronoun'] },
  { word: 'si', difficulty: 1, tags: ['adverb'] },
  { word: 'más', difficulty: 1, tags: ['adverb'] },
  { word: 'pero', difficulty: 1, tags: ['conjunction'] },
  { word: 'todo', difficulty: 1, tags: ['pronoun'] },
  { word: 'como', difficulty: 1, tags: ['conjunction'] },
  { word: 'muy', difficulty: 1, tags: ['adverb'] },
  { word: 'también', difficulty: 1, tags: ['adverb'] },
  { word: 'este', difficulty: 1, tags: ['pronoun'] },
  { word: 'esta', difficulty: 1, tags: ['pronoun'] },
  { word: 'ser', difficulty: 1, tags: ['verb'] },
  { word: 'estar', difficulty: 1, tags: ['verb'] },
  { word: 'haber', difficulty: 1, tags: ['verb'] },
  { word: 'tener', difficulty: 1, tags: ['verb'] },
  { word: 'hacer', difficulty: 1, tags: ['verb'] },
  { word: 'poder', difficulty: 1, tags: ['verb'] },
  { word: 'decir', difficulty: 1, tags: ['verb'] },
  // Intermediate (difficulty 2)
  { word: 'buenos', difficulty: 2, tags: ['adjective', 'accent'] },
  { word: 'días', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'gracias', difficulty: 2, tags: ['noun'] },
  { word: 'hola', difficulty: 2, tags: ['greeting'] },
  { word: 'adiós', difficulty: 2, tags: ['greeting', 'accent'] },
  { word: 'nación', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'español', difficulty: 2, tags: ['adjective', 'accent'] },
  { word: 'tío', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'tía', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'mañana', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'año', difficulty: 2, tags: ['noun', 'tilde'] },
  { word: 'niño', difficulty: 2, tags: ['noun', 'tilde'] },
  { word: 'niña', difficulty: 2, tags: ['noun', 'tilde'] },
  { word: 'España', difficulty: 2, tags: ['noun', 'tilde'] },
  { word: 'mujer', difficulty: 2, tags: ['noun'] },
  { word: 'hombre', difficulty: 2, tags: ['noun'] },
  { word: 'persona', difficulty: 2, tags: ['noun'] },
  { word: 'tiempo', difficulty: 2, tags: ['noun'] },
  { word: 'país', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'razón', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'corazón', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'avíon', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'ubicación', difficulty: 2, tags: ['noun', 'accent'] },
  { word: ' Martínez', difficulty: 2, tags: ['noun', 'accent'] },
  // Advanced (difficulty 3)
  { word: '¿cómo', difficulty: 3, tags: ['interrogative', 'inverted'] },
  { word: '¡hola', difficulty: 3, tags: ['greeting', 'inverted'] },
  { word: '¡adiós', difficulty: 3, tags: ['greeting', 'inverted'] },
  { word: 'pingüino', difficulty: 3, tags: ['noun', 'dieresis'] },
  { word: 'Antártida', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'pingüï', difficulty: 3, tags: ['noun', 'dieresis'] },
  { word: 'cigüeña', difficulty: 3, tags: ['noun', 'dieresis'] },
  { word: 'jüeö', difficulty: 3, tags: ['noun', 'dieresis'] },
  { word: 'vergüenza', difficulty: 3, tags: ['noun', 'dieresis'] },
  { word: 'coyote', difficulty: 3, tags: ['noun'] },
  { word: 'reggae', difficulty: 3, tags: ['noun'] },
  { word: '、保镖', difficulty: 3, tags: ['noun'] },
  { word: 'café', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'sofá', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'papá', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'mamá', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'iqué', difficulty: 3, tags: ['interrogative', 'inverted'] },
  { word: '¡ándale', difficulty: 3, tags: ['interjection', 'inverted'] },
];
