/**
 * Spanish wordlist with 200+ common words organized by difficulty
 * Includes Spanish-specific characters: ñ, ü, ¡, ¿, á, é, í, ó, ú
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Spanish wordlist - 200+ common words
 * Difficulty 1: Basic articles, pronouns, common verbs, simple words
 * Difficulty 2: Intermediate vocabulary, longer words
 * Difficulty 3: Advanced words with Spanish-specific characters
 */
export const spanishWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'el', difficulty: 1, tags: ['article', 'masculine', 'basic'] },
  { word: 'la', difficulty: 1, tags: ['article', 'feminine', 'basic'] },
  { word: 'un', difficulty: 1, tags: ['article', 'basic'] },
  { word: 'una', difficulty: 1, tags: ['article', 'feminine', 'basic'] },
  { word: 'de', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'y', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'es', difficulty: 1, tags: ['verb', 'ser', 'basic'] },
  { word: 'en', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'del', difficulty: 1, tags: ['preposition', 'contraction', 'basic'] },
  { word: 'se', difficulty: 1, tags: ['pronoun', 'reflexive', 'basic'] },
  { word: 'no', difficulty: 1, tags: ['adverb', 'negation', 'basic'] },
  { word: 'más', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'su', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'mundo', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'todo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'sobre', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'con', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'para', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'por', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'que', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'quien', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'usted', difficulty: 1, tags: ['pronoun', 'formal', 'basic'] },
  { word: 'nosotros', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'él', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'ella', difficulty: 1, tags: ['pronoun', 'feminine', 'basic'] },
  { word: 'tiene', difficulty: 1, tags: ['verb', 'tener', 'basic'] },
  { word: 'al', difficulty: 1, tags: ['preposition', 'contraction', 'basic'] },
  { word: 'son', difficulty: 1, tags: ['verb', 'ser', 'plural', 'basic'] },
  { word: 'hace', difficulty: 1, tags: ['verb', 'hacer', 'basic'] },
  { word: 'bien', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'pero', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'también', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'yo', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'tú', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'nos', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'les', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'lo', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'los', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'las', difficulty: 1, tags: ['pronoun', 'feminine', 'plural', 'basic'] },
  { word: 'me', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'te', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'le', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'os', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'este', difficulty: 1, tags: ['demonstrative', 'basic'] },
  { word: 'esta', difficulty: 1, tags: ['demonstrative', 'feminine', 'basic'] },
  { word: 'estos', difficulty: 1, tags: ['demonstrative', 'plural', 'basic'] },
  { word: 'estas', difficulty: 1, tags: ['demonstrative', 'feminine', 'plural', 'basic'] },
  { word: 'ese', difficulty: 1, tags: ['demonstrative', 'basic'] },
  { word: 'esa', difficulty: 1, tags: ['demonstrative', 'feminine', 'basic'] },
  { word: 'mi', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'tu', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'mis', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'tus', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'sus', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'nuestro', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'nuestra', difficulty: 1, tags: ['possessive', 'feminine', 'basic'] },
  { word: 'vuestro', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'vuestra', difficulty: 1, tags: ['possessive', 'feminine', 'basic'] },
  { word: 'nuestros', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'nuestras', difficulty: 1, tags: ['possessive', 'feminine', 'plural', 'basic'] },
  { word: 'soy', difficulty: 1, tags: ['verb', 'ser', 'basic'] },
  { word: 'eres', difficulty: 1, tags: ['verb', 'ser', 'basic'] },
  { word: 'somos', difficulty: 1, tags: ['verb', 'ser', 'plural', 'basic'] },
  { word: 'sois', difficulty: 1, tags: ['verb', 'ser', 'plural', 'basic'] },
  { word: 'estoy', difficulty: 1, tags: ['verb', 'estar', 'basic'] },
  { word: 'estás', difficulty: 1, tags: ['verb', 'estar', 'basic'] },
  { word: 'está', difficulty: 1, tags: ['verb', 'estar', 'basic'] },
  { word: 'estamos', difficulty: 1, tags: ['verb', 'estar', 'plural', 'basic'] },
  { word: 'estáis', difficulty: 1, tags: ['verb', 'estar', 'plural', 'basic'] },
  { word: 'están', difficulty: 1, tags: ['verb', 'estar', 'plural', 'basic'] },
  { word: 'tengo', difficulty: 1, tags: ['verb', 'tener', 'basic'] },
  { word: 'tienes', difficulty: 1, tags: ['verb', 'tener', 'basic'] },
  { word: 'tenemos', difficulty: 1, tags: ['verb', 'tener', 'plural', 'basic'] },
  { word: 'tenéis', difficulty: 1, tags: ['verb', 'tener', 'plural', 'basic'] },
  { word: 'tienen', difficulty: 1, tags: ['verb', 'tener', 'plural', 'basic'] },
  { word: 'ir', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'ver', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'venir', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'tomar', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'hablar', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'amar', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'encontrar', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'dar', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'tiempo', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'vida', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'hombre', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'mujer', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'día', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'mano', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'cosa', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'ojos', difficulty: 1, tags: ['noun', 'plural', 'basic'] },
  { word: 'puerta', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'chica', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'chico', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'casa', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'agua', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'pan', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'vino', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'amigo', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'amiga', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'pequeño', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'pequeña', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'grande', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'bueno', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'buena', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'malo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'mala', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'hermoso', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'hermosa', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'joven', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'viejo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'vieja', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'gordo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'gorda', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'nuevo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'nueva', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'primero', difficulty: 1, tags: ['adjective', 'ordinal', 'basic'] },
  { word: 'primera', difficulty: 1, tags: ['adjective', 'feminine', 'ordinal', 'basic'] },
  { word: 'último', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'última', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'mismo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'misma', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'otro', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'otra', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'todos', difficulty: 1, tags: ['adjective', 'plural', 'basic'] },
  { word: 'todas', difficulty: 1, tags: ['adjective', 'feminine', 'plural', 'basic'] },
  { word: 'sí', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'gracias', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'si', difficulty: 1, tags: ['conjunction', 'basic'] },

  // === Difficulty 2: Intermediate ===
  { word: 'hola', difficulty: 2, tags: ['greeting', 'intermediate'] },
  { word: 'cómo', difficulty: 2, tags: ['adverb', 'interrogative', 'intermediate'] },
  { word: 'trabajo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'ahora', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'importante', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'diferente', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'apartamento', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'conversación', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'vocabulario', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'gramática', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'nacionalidad', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'español', difficulty: 2, tags: ['noun', 'adjective', 'intermediate'] },
  { word: 'matemáticas', difficulty: 2, tags: ['noun', 'plural', 'intermediate'] },
  { word: 'alumno', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'profesor', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'estudiante', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'universidad', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'biblioteca', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'restaurante', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hospital', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'tienda', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'panadería', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'farmacia', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'banco', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'correo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'estación', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'aeropuerto', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hotel', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'cocina', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'habitación', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'sala', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'comedor', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'jardín', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'calle', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'plaza', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'puente', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'mercado', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'parque', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'mañana', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'tarde', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'noche', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'año', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'semana', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'mes', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hora', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'minuto', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'segundo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'almuerzo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'cena', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'desayuno', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'pregunta', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'respuesta', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'problema', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'solución', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'idea', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'razón', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'ejemplo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'historia', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'geografía', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'ciencias', difficulty: 2, tags: ['noun', 'plural', 'intermediate'] },
  { word: 'literatura', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'música', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'pintura', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'deporte', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'fútbol', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'tenis', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'natación', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'bicicleta', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'coche', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'moto', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'tren', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'autobús', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'metro', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'avión', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'barco', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'familia', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'madre', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'padre', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'padres', difficulty: 2, tags: ['noun', 'plural', 'intermediate'] },
  { word: 'hijo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hija', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'hermano', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hermana', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'primo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'prima', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'tío', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'tía', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'padrastro', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'madrastra', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'cuñado', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'cuñada', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },

  // === Difficulty 3: Advanced (Spanish-specific characters) ===
  { word: 'niño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'niña', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'cariño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'baño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'daño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'dueño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'dueña', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'pequeño', difficulty: 3, tags: ['adjective', 'tilde', 'advanced'] },
  { word: 'pequeña', difficulty: 3, tags: ['adjective', 'feminine', 'tilde', 'advanced'] },
  { word: 'montaña', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'araña', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'muñeca', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'muñeco', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'pañuelo', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'sueño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'teñir', difficulty: 3, tags: ['verb', 'tilde', 'advanced'] },
  { word: 'cañón', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'añadir', difficulty: 3, tags: ['verb', 'tilde', 'advanced'] },
  { word: 'tamaño', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'extraño', difficulty: 3, tags: ['adjective', 'tilde', 'advanced'] },
  { word: 'extraña', difficulty: 3, tags: ['adjective', 'feminine', 'tilde', 'advanced'] },
  { word: 'compañía', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'compañero', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'compañera', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'español', difficulty: 3, tags: ['noun', 'adjective', 'tilde', 'advanced'] },
  { word: 'española', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'señor', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'señora', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'señorita', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'inglés', difficulty: 3, tags: ['noun', 'adjective', 'tilde', 'advanced'] },
  { word: 'francés', difficulty: 3, tags: ['noun', 'adjective', 'tilde', 'advanced'] },
  { word: 'alemán', difficulty: 3, tags: ['noun', 'adjective', 'tilde', 'advanced'] },
  { word: 'canción', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'nación', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'acción', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'atención', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'función', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'lección', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'relación', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'lápiz', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'mamá', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'papá', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'sofá', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'menú', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'túnel', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'crimen', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'imagen', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'origen', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'examen', difficulty: 3, tags: ['noun', 'advanced'] },
  { word: 'país', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'raíz', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'café', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'bebé', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'corazón', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'razón', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'salón', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'balcón', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'rincón', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'sillón', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'teléfono', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'televisión', difficulty: 3, tags: ['noun', 'feminine', 'tilde', 'advanced'] },
  { word: 'cómo', difficulty: 3, tags: ['adverb', 'interrogative', 'tilde', 'advanced'] },
  { word: 'qué', difficulty: 3, tags: ['pronoun', 'interrogative', 'tilde', 'advanced'] },
  { word: 'quién', difficulty: 3, tags: ['pronoun', 'interrogative', 'tilde', 'advanced'] },
  { word: 'dónde', difficulty: 3, tags: ['adverb', 'interrogative', 'tilde', 'advanced'] },
  { word: 'cuándo', difficulty: 3, tags: ['adverb', 'interrogative', 'tilde', 'advanced'] },
  { word: 'cuál', difficulty: 3, tags: ['pronoun', 'interrogative', 'tilde', 'advanced'] },
  { word: 'cuánto', difficulty: 3, tags: ['adjective', 'interrogative', 'tilde', 'advanced'] },
  { word: 'por qué', difficulty: 3, tags: ['adverb', 'interrogative', 'tilde', 'advanced'] },
  { word: 'porque', difficulty: 3, tags: ['conjunction', 'advanced'] },
  { word: 'también', difficulty: 3, tags: ['adverb', 'tilde', 'advanced'] },
  { word: 'aún', difficulty: 3, tags: ['adverb', 'tilde', 'advanced'] },
  { word: 'sí', difficulty: 3, tags: ['interjection', 'tilde', 'advanced'] },
  { word: 'tú', difficulty: 3, tags: ['pronoun', 'tilde', 'advanced'] },
  { word: 'mí', difficulty: 3, tags: ['pronoun', 'tilde', 'advanced'] },
  { word: 'sé', difficulty: 3, tags: ['verb', 'tilde', 'advanced'] },
  { word: 'té', difficulty: 3, tags: ['noun', 'tilde', 'advanced'] },
  { word: 'sólo', difficulty: 3, tags: ['adverb', 'tilde', 'advanced'] },
  { word: 'solo', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'sola', difficulty: 3, tags: ['adjective', 'feminine', 'advanced'] },
  { word: 'pingüino', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'vergüenza', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'bilingüe', difficulty: 3, tags: ['adjective', 'diaeresis', 'advanced'] },
  { word: 'cigüeña', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'antigüedad', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'lengüeta', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'agüero', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'ambigüedad', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'argüir', difficulty: 3, tags: ['verb', 'diaeresis', 'advanced'] },
  { word: 'bilingüismo', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'cigüeñal', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'güero', difficulty: 3, tags: ['adjective', 'diaeresis', 'advanced'] },
  { word: 'güey', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'güiro', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'paragüero', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: '¡hola', difficulty: 3, tags: ['interjection', 'inverted-exclamation', 'advanced'] },
  { word: '¡qué', difficulty: 3, tags: ['pronoun', 'interjection', 'inverted-exclamation', 'advanced'] },
  { word: '¡cómo', difficulty: 3, tags: ['adverb', 'interjection', 'inverted-exclamation', 'advanced'] },
  { word: '¿cómo', difficulty: 3, tags: ['adverb', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿qué', difficulty: 3, tags: ['pronoun', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿quién', difficulty: 3, tags: ['pronoun', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿dónde', difficulty: 3, tags: ['adverb', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿cuándo', difficulty: 3, tags: ['adverb', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿por qué', difficulty: 3, tags: ['adverb', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿cuál', difficulty: 3, tags: ['pronoun', 'interrogative', 'inverted-question', 'advanced'] },
  { word: '¿cuánto', difficulty: 3, tags: ['adjective', 'interrogative', 'inverted-question', 'advanced'] },
];

export default spanishWordlist;
