/**
 * French wordlist with 200+ common words organized by difficulty
 * Includes French-specific characters: â, ê, î, ô, û, ë, ï, ü, ÿ, ç, œ, æ, à, è, ù
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * French wordlist - 200+ common words
 * Difficulty 1: Basic articles, pronouns, common verbs, simple words
 * Difficulty 2: Intermediate vocabulary, longer words
 * Difficulty 3: Advanced words with French-specific characters
 */
export const frenchWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'le', difficulty: 1, tags: ['article', 'masculine', 'basic'] },
  { word: 'la', difficulty: 1, tags: ['article', 'feminine', 'basic'] },
  { word: 'un', difficulty: 1, tags: ['article', 'number', 'basic'] },
  { word: 'une', difficulty: 1, tags: ['article', 'feminine', 'basic'] },
  { word: 'de', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'et', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'est', difficulty: 1, tags: ['verb', 'être', 'basic'] },
  { word: 'en', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'du', difficulty: 1, tags: ['article', 'contraction', 'basic'] },
  { word: 'se', difficulty: 1, tags: ['pronoun', 'reflexive', 'basic'] },
  { word: 'pas', difficulty: 1, tags: ['adverb', 'negation', 'basic'] },
  { word: 'plus', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'son', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'monde', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'tout', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'sur', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'avec', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'pour', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'dans', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'que', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'qui', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'vous', difficulty: 1, tags: ['pronoun', 'formal', 'basic'] },
  { word: 'nous', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'il', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'elle', difficulty: 1, tags: ['pronoun', 'feminine', 'basic'] },
  { word: 'a', difficulty: 1, tags: ['verb', 'avoir', 'basic'] },
  { word: 'au', difficulty: 1, tags: ['preposition', 'contraction', 'basic'] },
  { word: 'aux', difficulty: 1, tags: ['preposition', 'plural', 'basic'] },
  { word: 'sont', difficulty: 1, tags: ['verb', 'être', 'plural', 'basic'] },
  { word: 'fait', difficulty: 1, tags: ['verb', 'faire', 'basic'] },
  { word: 'bien', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'mais', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'aussi', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'je', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'tu', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'on', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'ils', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'elles', difficulty: 1, tags: ['pronoun', 'feminine', 'plural', 'basic'] },
  { word: 'me', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'te', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'lui', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'leur', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'y', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'ce', difficulty: 1, tags: ['demonstrative', 'basic'] },
  { word: 'cet', difficulty: 1, tags: ['demonstrative', 'basic'] },
  { word: 'cette', difficulty: 1, tags: ['demonstrative', 'feminine', 'basic'] },
  { word: 'ces', difficulty: 1, tags: ['demonstrative', 'plural', 'basic'] },
  { word: 'mon', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'ton', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'ma', difficulty: 1, tags: ['possessive', 'feminine', 'basic'] },
  { word: 'ta', difficulty: 1, tags: ['possessive', 'feminine', 'basic'] },
  { word: 'mes', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'tes', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'ses', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'notre', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'votre', difficulty: 1, tags: ['possessive', 'formal', 'basic'] },
  { word: 'nos', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'vos', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'leurs', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'suis', difficulty: 1, tags: ['verb', 'être', 'basic'] },
  { word: 'es', difficulty: 1, tags: ['verb', 'être', 'basic'] },
  { word: 'sommes', difficulty: 1, tags: ['verb', 'être', 'plural', 'basic'] },
  { word: 'êtes', difficulty: 1, tags: ['verb', 'être', 'formal', 'basic'] },
  { word: 'ont', difficulty: 1, tags: ['verb', 'avoir', 'plural', 'basic'] },
  { word: 'ai', difficulty: 1, tags: ['verb', 'avoir', 'basic'] },
  { word: 'as', difficulty: 1, tags: ['verb', 'avoir', 'basic'] },
  { word: 'avons', difficulty: 1, tags: ['verb', 'avoir', 'plural', 'basic'] },
  { word: 'avez', difficulty: 1, tags: ['verb', 'avoir', 'formal', 'basic'] },
  { word: 'aller', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'voir', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'venir', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'prendre', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'parler', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'aimer', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'trouver', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'donner', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'temps', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'vie', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'homme', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'femme', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'jour', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'main', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'chose', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'yeux', difficulty: 1, tags: ['noun', 'plural', 'basic'] },
  { word: 'porte', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'fille', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'garçon', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'maison', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'eau', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'pain', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'vin', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'ami', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'amie', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'petit', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'petite', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'grand', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'grande', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'bon', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'bonne', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'mauvais', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'mauvaise', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'beau', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'belle', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'jeune', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'vieux', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'vieille', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'gros', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'grosse', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'nouveau', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'nouvelle', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'premier', difficulty: 1, tags: ['adjective', 'ordinal', 'basic'] },
  { word: 'première', difficulty: 1, tags: ['adjective', 'feminine', 'ordinal', 'basic'] },
  { word: 'dernier', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'dernière', difficulty: 1, tags: ['adjective', 'feminine', 'basic'] },
  { word: 'même', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'autre', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'tous', difficulty: 1, tags: ['adjective', 'plural', 'basic'] },
  { word: 'toutes', difficulty: 1, tags: ['adjective', 'feminine', 'plural', 'basic'] },
  { word: 'oui', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'non', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'merci', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'svp', difficulty: 1, tags: ['abbreviation', 'basic'] },

  // === Difficulty 2: Intermediate ===
  { word: 'bonjour', difficulty: 2, tags: ['greeting', 'intermediate'] },
  { word: 'comment', difficulty: 2, tags: ['adverb', 'interrogative', 'intermediate'] },
  { word: 'travail', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'maintenant', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'important', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'différent', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'appartement', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'conversation', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'vocabulaire', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'grammaire', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'nationalité', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'français', difficulty: 2, tags: ['noun', 'adjective', 'intermediate'] },
  { word: 'mathématiques', difficulty: 2, tags: ['noun', 'plural', 'intermediate'] },
  { word: 'élève', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'professeur', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'étudiant', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'université', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'bibliothèque', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'restaurant', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hôpital', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'magasin', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'boulangerie', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'pharmacie', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'banque', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'poste', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'gare', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'aéroport', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'hôtel', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'cuisine', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'chambre', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'salon', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'salle', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'jardin', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'rue', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'place', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'pont', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'marché', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'parc', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'journée', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'soirée', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'matinée', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'année', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'semaine', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'mois', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'heure', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'minute', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'seconde', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'déjeuner', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'dîner', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'question', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'réponse', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'problème', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'solution', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'idée', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'raison', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'exemple', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'histoire', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'géographie', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'sciences', difficulty: 2, tags: ['noun', 'plural', 'intermediate'] },
  { word: 'littérature', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'musique', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'peinture', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'sport', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'football', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'tennis', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'natation', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'vélo', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'voiture', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'moto', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'train', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'bus', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'métro', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'avion', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'bateau', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'famille', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'mère', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'père', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'parent', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'enfant', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'frère', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'cousin', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'cousine', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'oncle', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'tante', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'beau-père', difficulty: 2, tags: ['noun', 'intermediate'] },
  { word: 'belle-mère', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'beau-frère', difficulty: 2, tags: ['noun', 'intermediate'] },

  // === Difficulty 3: Advanced (French-specific characters) ===
  { word: 'être', difficulty: 3, tags: ['verb', 'circumflex', 'advanced'] },
  { word: 'forêt', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'bête', difficulty: 3, tags: ['adjective', 'circumflex', 'advanced'] },
  { word: 'fête', difficulty: 3, tags: ['noun', 'feminine', 'circumflex', 'advanced'] },
  { word: 'arrêt', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'connaître', difficulty: 3, tags: ['verb', 'circumflex', 'advanced'] },
  { word: 'paraître', difficulty: 3, tags: ['verb', 'circumflex', 'advanced'] },
  { word: 'naître', difficulty: 3, tags: ['verb', 'circumflex', 'advanced'] },
  { word: 'apparaître', difficulty: 3, tags: ['verb', 'circumflex', 'advanced'] },
  { word: 'déjà', difficulty: 3, tags: ['adverb', 'grave', 'advanced'] },
  { word: 'là', difficulty: 3, tags: ['adverb', 'grave', 'advanced'] },
  { word: 'voilà', difficulty: 3, tags: ['adverb', 'grave', 'advanced'] },
  { word: 'où', difficulty: 3, tags: ['adverb', 'grave', 'advanced'] },
  { word: 'dès', difficulty: 3, tags: ['preposition', 'grave', 'advanced'] },
  { word: 'très', difficulty: 3, tags: ['adverb', 'grave', 'advanced'] },
  { word: 'près', difficulty: 3, tags: ['adverb', 'grave', 'advanced'] },
  { word: 'après', difficulty: 3, tags: ['preposition', 'grave', 'advanced'] },
  { word: 'décès', difficulty: 3, tags: ['noun', 'grave', 'advanced'] },
  { word: 'bienfaît', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'goût', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'dépôt', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'bientôt', difficulty: 3, tags: ['adverb', 'circumflex', 'advanced'] },
  { word: 'côte', difficulty: 3, tags: ['noun', 'feminine', 'circumflex', 'advanced'] },
  { word: 'côté', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'coût', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'hôte', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'île', difficulty: 3, tags: ['noun', 'feminine', 'circumflex', 'advanced'] },
  { word: 'maître', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'maîtresse', difficulty: 3, tags: ['noun', 'feminine', 'circumflex', 'advanced'] },
  { word: 'gâteau', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'château', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'âge', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'pâté', difficulty: 3, tags: ['noun', 'circumflex', 'advanced'] },
  { word: 'Noël', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'naïf', difficulty: 3, tags: ['adjective', 'diaeresis', 'advanced'] },
  { word: 'maïs', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'haïr', difficulty: 3, tags: ['verb', 'diaeresis', 'advanced'] },
  { word: 'aïeul', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'ambigüité', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'égoïsme', difficulty: 3, tags: ['noun', 'diaeresis', 'advanced'] },
  { word: 'égoïste', difficulty: 3, tags: ['adjective', 'diaeresis', 'advanced'] },
  { word: 'ciguë', difficulty: 3, tags: ['noun', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'aiguë', difficulty: 3, tags: ['adjective', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'contiguë', difficulty: 3, tags: ['adjective', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'exiguë', difficulty: 3, tags: ['adjective', 'feminine', 'diaeresis', 'advanced'] },
  { word: 'garçon', difficulty: 3, tags: ['noun', 'cedilla', 'advanced'] },
  { word: 'leçon', difficulty: 3, tags: ['noun', 'feminine', 'cedilla', 'advanced'] },
  { word: 'façon', difficulty: 3, tags: ['noun', 'feminine', 'cedilla', 'advanced'] },
  { word: 'reçu', difficulty: 3, tags: ['noun', 'cedilla', 'advanced'] },
  { word: 'déçu', difficulty: 3, tags: ['adjective', 'cedilla', 'advanced'] },
  { word: 'aperçu', difficulty: 3, tags: ['noun', 'cedilla', 'advanced'] },
  { word: 'ça', difficulty: 3, tags: ['pronoun', 'cedilla', 'advanced'] },
  { word: 'soupçon', difficulty: 3, tags: ['noun', 'cedilla', 'advanced'] },
  { word: 'glaçon', difficulty: 3, tags: ['noun', 'cedilla', 'advanced'] },
  { word: 'maçon', difficulty: 3, tags: ['noun', 'cedilla', 'advanced'] },
  { word: 'cœur', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'sœur', difficulty: 3, tags: ['noun', 'feminine', 'ligature', 'advanced'] },
  { word: 'œuf', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'bœuf', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'œuvre', difficulty: 3, tags: ['noun', 'feminine', 'ligature', 'advanced'] },
  { word: 'œil', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'vœu', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'chœur', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'fœtus', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'ex æquo', difficulty: 3, tags: ['adverb', 'ligature', 'advanced'] },
  { word: 'curriculum vitæ', difficulty: 3, tags: ['noun', 'ligature', 'advanced'] },
  { word: 'et cætera', difficulty: 3, tags: ['adverb', 'ligature', 'advanced'] },
];

export default frenchWordlist;
