export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

export const frenchWordlist: WordlistEntry[] = [
  // Beginner (difficulty 1)
  { word: 'le', difficulty: 1, tags: ['article'] },
  { word: 'la', difficulty: 1, tags: ['article'] },
  { word: 'un', difficulty: 1, tags: ['article'] },
  { word: 'une', difficulty: 1, tags: ['article'] },
  { word: 'de', difficulty: 1, tags: ['article'] },
  { word: 'et', difficulty: 1, tags: ['conjunction'] },
  { word: 'est', difficulty: 1, tags: ['verb'] },
  { word: 'en', difficulty: 1, tags: ['preposition'] },
  { word: 'du', difficulty: 1, tags: ['article'] },
  { word: 'se', difficulty: 1, tags: ['pronoun'] },
  { word: 'pas', difficulty: 1, tags: ['adverb'] },
  { word: 'plus', difficulty: 1, tags: ['adverb'] },
  { word: 'son', difficulty: 1, tags: ['possessive'] },
  { word: 'monde', difficulty: 1, tags: ['noun'] },
  { word: 'tout', difficulty: 1, tags: ['adjective'] },
  { word: 'sur', difficulty: 1, tags: ['preposition'] },
  { word: 'avec', difficulty: 1, tags: ['preposition'] },
  { word: 'pour', difficulty: 1, tags: ['preposition'] },
  { word: 'dans', difficulty: 1, tags: ['preposition'] },
  { word: 'que', difficulty: 1, tags: ['conjunction'] },
  { word: 'qui', difficulty: 1, tags: ['pronoun'] },
  { word: 'vous', difficulty: 1, tags: ['pronoun'] },
  { word: 'nous', difficulty: 1, tags: ['pronoun'] },
  { word: 'il', difficulty: 1, tags: ['pronoun'] },
  { word: 'elle', difficulty: 1, tags: ['pronoun'] },
  { word: 'a', difficulty: 1, tags: ['verb'] },
  { word: 'au', difficulty: 1, tags: ['article'] },
  { word: 'aux', difficulty: 1, tags: ['article'] },
  { word: 'sont', difficulty: 1, tags: ['verb'] },
  { word: 'fait', difficulty: 1, tags: ['verb'] },
  { word: 'bien', difficulty: 1, tags: ['adverb'] },
  { word: 'mais', difficulty: 1, tags: ['conjunction'] },
  { word: 'aussi', difficulty: 1, tags: ['adverb'] },
  { word: 'its', difficulty: 1, tags: ['noun'] },
  { word: 'des', difficulty: 1, tags: ['article'] },
  { word: 'mes', difficulty: 1, tags: ['possessive'] },
  { word: 'ces', difficulty: 1, tags: ['determiner'] },
  { word: 'les', difficulty: 1, tags: ['article'] },
  { word: 'par', difficulty: 1, tags: ['preposition'] },
  { word: 'sur', difficulty: 1, tags: ['preposition'] },
  { word: 'notre', difficulty: 1, tags: ['possessive'] },
  // Intermediate (difficulty 2)
  { word: 'bonjour', difficulty: 2, tags: ['greeting'] },
  { word: 'merci', difficulty: 2, tags: ['greeting'] },
  { word: 'travail', difficulty: 2, tags: ['noun'] },
  { word: 'maintenant', difficulty: 2, tags: ['adverb'] },
  { word: 'important', difficulty: 2, tags: ['adjective'] },
  { word: 'différent', difficulty: 2, tags: ['adjective', 'accent'] },
  { word: 'appartement', difficulty: 2, tags: ['noun'] },
  { word: 'conversation', difficulty: 2, tags: ['noun'] },
  { word: 'vocabulaire', difficulty: 2, tags: ['noun'] },
  { word: 'grammaire', difficulty: 2, tags: ['noun'] },
  { word: 'nationalité', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'français', difficulty: 2, tags: ['adjective', 'accent'] },
  { word: 'mathématiques', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'élève', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'forêt', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'n'est', difficulty: 2, tags: ['contraction'] },
  { word: 'cette', difficulty: 2, tags: ['determiner', 'accent'] },
  { word: 'où', difficulty: 2, tags: ['adverb', 'accent'] },
  { word: 'ça', difficulty: 2, tags: ['pronoun', 'accent'] },
  { word: 'été', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'tête', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'héros', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'bureau', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'côte', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'numéro', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'problème', difficulty: 2, tags: ['noun', 'accent'] },
  { word: 'être', difficulty: 2, tags: ['verb', 'accent'] },
  { word: 'avoir', difficulty: 2, tags: ['verb', 'accent'] },
  { word: 'faire', difficulty: 2, tags: ['verb', 'accent'] },
  { word: 'prise', difficulty: 2, tags: ['noun', 'accent'] },
  // Advanced (difficulty 3)
  { word: 'maîtrise', difficulty: 3, tags: ['noun', 'circumflex'] },
  { word: 'naître', difficulty: 3, tags: ['verb', 'circumflex'] },
  { word: 'dû', difficulty: 3, tags: ['verb', 'accent', 'circumflex'] },
  { word: 'hârtage', difficulty: 3, tags: ['noun', 'circumflex'] },
  { word: 'êêê', difficulty: 3, tags: ['noun', 'circumflex'] },
  { word: 'anniversaire', difficulty: 3, tags: ['noun', 'double-accent'] },
  { word: 'éclaircie', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'œuvre', difficulty: 3, tags: ['noun', 'ligature'] },
  { word: 'cœur', difficulty: 3, tags: ['noun', 'ligature'] },
  { word: 'œil', difficulty: 3, tags: ['noun', 'ligature'] },
  { word: 'sœur', difficulty: 3, tags: ['noun', 'ligature'] },
  { word: 'français', difficulty: 3, tags: ['noun', 'cédille'] },
  { word: 'garçon', difficulty: 3, tags: ['noun', 'cédille'] },
  { word: 'maçon', difficulty: 3, tags: ['noun', 'cédille'] },
  { word: 'François', difficulty: 3, tags: ['noun', 'cédille'] },
  { word: 'reçu', difficulty: 3, tags: ['verb', 'accent'] },
  { word: 'perçu', difficulty: 3, tags: ['verb', 'accent'] },
  { word: 'à', difficulty: 3, tags: ['preposition', 'accent'] },
  { word: 'è', difficulty: 3, tags: ['noun', 'accent'] },
  { word: 'ù', difficulty: 3, tags: ['noun', 'accent'] },
];
