/**
 * Hebrew wordlist with 200+ common words organized by difficulty
 * Includes Hebrew letters and common vocabulary
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Hebrew wordlist - 200+ common words
 * Difficulty 1: Basic words, short words, common prepositions
 * Difficulty 2: Intermediate vocabulary, longer words
 * Difficulty 3: Advanced words, complex vocabulary, foreign loanwords
 */
export const hebrewWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  // Prepositions and conjunctions
  { word: 'ב', difficulty: 1, tags: ['preposition', 'in', 'basic'] },
  { word: 'ל', difficulty: 1, tags: ['preposition', 'to', 'basic'] },
  { word: 'מ', difficulty: 1, tags: ['preposition', 'from', 'basic'] },
  { word: 'ו', difficulty: 1, tags: ['conjunction', 'and', 'basic'] },
  { word: 'כ', difficulty: 1, tags: ['preposition', 'like', 'basic'] },
  { word: 'ש', difficulty: 1, tags: ['conjunction', 'that', 'basic'] },
  { word: 'ה', difficulty: 1, tags: ['article', 'the', 'basic'] },
  { word: 'את', difficulty: 1, tags: ['preposition', 'with', 'basic'] },
  { word: 'עם', difficulty: 1, tags: ['preposition', 'with', 'basic'] },
  { word: 'או', difficulty: 1, tags: ['conjunction', 'or', 'basic'] },
  { word: 'על', difficulty: 1, tags: ['preposition', 'on', 'basic'] },
  { word: 'לא', difficulty: 1, tags: ['adverb', 'negation', 'basic'] },
  { word: 'כן', difficulty: 1, tags: ['adverb', 'yes', 'basic'] },
  { word: 'גם', difficulty: 1, tags: ['adverb', 'also', 'basic'] },
  { word: 'רק', difficulty: 1, tags: ['adverb', 'only', 'basic'] },
  { word: 'כי', difficulty: 1, tags: ['conjunction', 'because', 'basic'] },
  { word: 'אם', difficulty: 1, tags: ['conjunction', 'if', 'basic'] },
  { word: 'כל', difficulty: 1, tags: ['adjective', 'all', 'basic'] },
  { word: 'עוד', difficulty: 1, tags: ['adverb', 'more', 'basic'] },
  { word: 'פה', difficulty: 1, tags: ['adverb', 'here', 'basic'] },
  { word: 'שם', difficulty: 1, tags: ['adverb', 'there', 'basic'] },
  { word: 'עכשיו', difficulty: 1, tags: ['adverb', 'now', 'basic'] },
  { word: 'אז', difficulty: 1, tags: ['adverb', 'then', 'basic'] },
  { word: 'כבר', difficulty: 1, tags: ['adverb', 'already', 'basic'] },
  { word: 'יותר', difficulty: 1, tags: ['adverb', 'more', 'basic'] },
  { word: 'פחות', difficulty: 1, tags: ['adverb', 'less', 'basic'] },
  { word: 'טוב', difficulty: 1, tags: ['adjective', 'good', 'basic'] },
  { word: 'רע', difficulty: 1, tags: ['adjective', 'bad', 'basic'] },
  { word: 'חדש', difficulty: 1, tags: ['adjective', 'new', 'basic'] },
  { word: 'ישן', difficulty: 1, tags: ['adjective', 'old', 'basic'] },
  { word: 'גדול', difficulty: 1, tags: ['adjective', 'big', 'basic'] },
  { word: 'קטן', difficulty: 1, tags: ['adjective', 'small', 'basic'] },
  { word: 'יפה', difficulty: 1, tags: ['adjective', 'beautiful', 'basic'] },
  { word: 'רחוק', difficulty: 1, tags: ['adjective', 'far', 'basic'] },
  { word: 'קרוב', difficulty: 1, tags: ['adjective', 'close', 'basic'] },
  { word: 'חם', difficulty: 1, tags: ['adjective', 'hot', 'basic'] },
  { word: 'קר', difficulty: 1, tags: ['adjective', 'cold', 'basic'] },
  { word: 'מהר', difficulty: 1, tags: ['adverb', 'fast', 'basic'] },
  { word: 'לאט', difficulty: 1, tags: ['adverb', 'slow', 'basic'] },
  { word: 'בית', difficulty: 1, tags: ['noun', 'house', 'basic'] },
  { word: 'אבא', difficulty: 1, tags: ['noun', 'father', 'family', 'basic'] },
  { word: 'אמא', difficulty: 1, tags: ['noun', 'mother', 'family', 'basic'] },
  { word: 'ילד', difficulty: 1, tags: ['noun', 'child', 'family', 'basic'] },
  { word: 'דג', difficulty: 1, tags: ['noun', 'fish', 'basic'] },
  { word: 'שמש', difficulty: 1, tags: ['noun', 'sun', 'basic'] },
  { word: 'ירח', difficulty: 1, tags: ['noun', 'moon', 'basic'] },
  { word: 'מים', difficulty: 1, tags: ['noun', 'water', 'basic'] },
  { word: 'אש', difficulty: 1, tags: ['noun', 'fire', 'basic'] },
  { word: 'אדמה', difficulty: 1, tags: ['noun', 'earth', 'basic'] },
  { word: 'שמים', difficulty: 1, tags: ['noun', 'sky', 'basic'] },
  { word: 'ים', difficulty: 1, tags: ['noun', 'sea', 'basic'] },
  { word: 'הר', difficulty: 1, tags: ['noun', 'mountain', 'basic'] },
  { word: 'עץ', difficulty: 1, tags: ['noun', 'tree', 'basic'] },
  { word: 'פרח', difficulty: 1, tags: ['noun', 'flower', 'basic'] },
  { word: 'אני', difficulty: 1, tags: ['pronoun', 'I', 'basic'] },
  { word: 'אתה', difficulty: 1, tags: ['pronoun', 'you', 'masculine', 'basic'] },
  { word: 'את', difficulty: 1, tags: ['pronoun', 'you', 'feminine', 'basic'] },
  { word: 'הוא', difficulty: 1, tags: ['pronoun', 'he', 'basic'] },
  { word: 'היא', difficulty: 1, tags: ['pronoun', 'she', 'basic'] },
  { word: 'אנחנו', difficulty: 1, tags: ['pronoun', 'we', 'basic'] },
  { word: 'הם', difficulty: 1, tags: ['pronoun', 'they', 'masculine', 'basic'] },
  { word: 'הן', difficulty: 1, tags: ['pronoun', 'they', 'feminine', 'basic'] },
  { word: 'זה', difficulty: 1, tags: ['pronoun', 'this', 'masculine', 'basic'] },
  { word: 'זאת', difficulty: 1, tags: ['pronoun', 'this', 'feminine', 'basic'] },
  { word: 'אלה', difficulty: 1, tags: ['pronoun', 'these', 'basic'] },
  { word: 'מי', difficulty: 1, tags: ['pronoun', 'who', 'basic'] },
  { word: 'מה', difficulty: 1, tags: ['pronoun', 'what', 'basic'] },
  { word: 'איפה', difficulty: 1, tags: ['pronoun', 'where', 'basic'] },
  { word: 'מתי', difficulty: 1, tags: ['pronoun', 'when', 'basic'] },
  { word: 'למה', difficulty: 1, tags: ['pronoun', 'why', 'basic'] },
  { word: 'איך', difficulty: 1, tags: ['pronoun', 'how', 'basic'] },

  // === Difficulty 2: Intermediate ===
  { word: 'ספר', difficulty: 2, tags: ['noun', 'book', 'intermediate'] },
  { word: 'מלחמה', difficulty: 2, tags: ['noun', 'war', 'intermediate'] },
  { word: 'שלום', difficulty: 2, tags: ['noun', 'peace', 'intermediate'] },
  { word: 'אהבה', difficulty: 2, tags: ['noun', 'love', 'intermediate'] },
  { word: 'חבר', difficulty: 2, tags: ['noun', 'friend', 'intermediate'] },
  { word: 'חברה', difficulty: 2, tags: ['noun', 'friend', 'feminine', 'intermediate'] },
  { word: 'עבודה', difficulty: 2, tags: ['noun', 'work', 'intermediate'] },
  { word: 'בית ספר', difficulty: 2, tags: ['noun', 'school', 'intermediate'] },
  { word: 'מורה', difficulty: 2, tags: ['noun', 'teacher', 'intermediate'] },
  { word: 'תלמיד', difficulty: 2, tags: ['noun', 'student', 'intermediate'] },
  { word: 'אוכל', difficulty: 2, tags: ['noun', 'food', 'intermediate'] },
  { word: 'מטבח', difficulty: 2, tags: ['noun', 'kitchen', 'intermediate'] },
  { word: 'חדר', difficulty: 2, tags: ['noun', 'room', 'intermediate'] },
  { word: 'דלת', difficulty: 2, tags: ['noun', 'door', 'intermediate'] },
  { word: 'חלון', difficulty: 2, tags: ['noun', 'window', 'intermediate'] },
  { word: 'שולחן', difficulty: 2, tags: ['noun', 'table', 'intermediate'] },
  { word: 'כיסא', difficulty: 2, tags: ['noun', 'chair', 'intermediate'] },
  { word: 'מיטה', difficulty: 2, tags: ['noun', 'bed', 'intermediate'] },
  { word: 'רחוב', difficulty: 2, tags: ['noun', 'street', 'intermediate'] },
  { word: 'כביש', difficulty: 2, tags: ['noun', 'road', 'intermediate'] },
  { word: 'עיר', difficulty: 2, tags: ['noun', 'city', 'intermediate'] },
  { word: 'כפר', difficulty: 2, tags: ['noun', 'village', 'intermediate'] },
  { word: 'מדינה', difficulty: 2, tags: ['noun', 'country', 'intermediate'] },
  { word: 'עולם', difficulty: 2, tags: ['noun', 'world', 'intermediate'] },
  { word: 'חיים', difficulty: 2, tags: ['noun', 'life', 'intermediate'] },
  { word: 'מוות', difficulty: 2, tags: ['noun', 'death', 'intermediate'] },
  { word: 'שמחה', difficulty: 2, tags: ['noun', 'happiness', 'intermediate'] },
  { word: 'עצוב', difficulty: 2, tags: ['adjective', 'sad', 'intermediate'] },
  { word: 'כועס', difficulty: 2, tags: ['adjective', 'angry', 'intermediate'] },
  { word: 'עייף', difficulty: 2, tags: ['adjective', 'tired', 'intermediate'] },
  { word: 'בריא', difficulty: 2, tags: ['adjective', 'healthy', 'intermediate'] },
  { word: 'חולה', difficulty: 2, tags: ['adjective', 'sick', 'intermediate'] },
  { word: 'חזק', difficulty: 2, tags: ['adjective', 'strong', 'intermediate'] },
  { word: 'חלש', difficulty: 2, tags: ['adjective', 'weak', 'intermediate'] },
  { word: 'עשיר', difficulty: 2, tags: ['adjective', 'rich', 'intermediate'] },
  { word: 'עני', difficulty: 2, tags: ['adjective', 'poor', 'intermediate'] },
  { word: 'חכם', difficulty: 2, tags: ['adjective', 'smart', 'intermediate'] },
  { word: 'טיפש', difficulty: 2, tags: ['adjective', 'stupid', 'intermediate'] },
  { word: 'מהיר', difficulty: 2, tags: ['adjective', 'fast', 'intermediate'] },
  { word: 'איטי', difficulty: 2, tags: ['adjective', 'slow', 'intermediate'] },
  { word: 'קל', difficulty: 2, tags: ['adjective', 'easy', 'intermediate'] },
  { word: 'קשה', difficulty: 2, tags: ['adjective', 'difficult', 'intermediate'] },
  { word: 'יפה', difficulty: 2, tags: ['adjective', 'beautiful', 'intermediate'] },
  { word: 'מכוער', difficulty: 2, tags: ['adjective', 'ugly', 'intermediate'] },
  { word: 'נקי', difficulty: 2, tags: ['adjective', 'clean', 'intermediate'] },
  { word: 'מלוכלך', difficulty: 2, tags: ['adjective', 'dirty', 'intermediate'] },
  { word: 'יבש', difficulty: 2, tags: ['adjective', 'dry', 'intermediate'] },
  { word: 'רטוב', difficulty: 2, tags: ['adjective', 'wet', 'intermediate'] },
  { word: 'רך', difficulty: 2, tags: ['adjective', 'soft', 'intermediate'] },
  { word: 'קשה', difficulty: 2, tags: ['adjective', 'hard', 'intermediate'] },
  { word: 'מתוק', difficulty: 2, tags: ['adjective', 'sweet', 'intermediate'] },
  { word: 'מלוח', difficulty: 2, tags: ['adjective', 'salty', 'intermediate'] },
  { word: 'חמוץ', difficulty: 2, tags: ['adjective', 'sour', 'intermediate'] },
  { word: 'מר', difficulty: 2, tags: ['adjective', 'bitter', 'intermediate'] },
  { word: 'חד', difficulty: 2, tags: ['adjective', 'sharp', 'intermediate'] },
  { word: 'כהה', difficulty: 2, tags: ['adjective', 'dark', 'intermediate'] },
  { word: 'בהיר', difficulty: 2, tags: ['adjective', 'light', 'intermediate'] },
  { word: 'ארוך', difficulty: 2, tags: ['adjective', 'long', 'intermediate'] },
  { word: 'קצר', difficulty: 2, tags: ['adjective', 'short', 'intermediate'] },
  { word: 'רחב', difficulty: 2, tags: ['adjective', 'wide', 'intermediate'] },
  { word: 'צר', difficulty: 2, tags: ['adjective', 'narrow', 'intermediate'] },
  { word: 'עבה', difficulty: 2, tags: ['adjective', 'thick', 'intermediate'] },
  { word: 'דק', difficulty: 2, tags: ['adjective', 'thin', 'intermediate'] },
  { word: 'כבד', difficulty: 2, tags: ['adjective', 'heavy', 'intermediate'] },
  { word: 'קל', difficulty: 2, tags: ['adjective', 'light', 'intermediate'] },
  { word: 'יקר', difficulty: 2, tags: ['adjective', 'expensive', 'intermediate'] },
  { word: 'זול', difficulty: 2, tags: ['adjective', 'cheap', 'intermediate'] },
  { word: 'חדש', difficulty: 2, tags: ['adjective', 'new', 'intermediate'] },
  { word: 'ישן', difficulty: 2, tags: ['adjective', 'old', 'intermediate'] },
  { word: 'צעיר', difficulty: 2, tags: ['adjective', 'young', 'intermediate'] },
  { word: 'זקן', difficulty: 2, tags: ['adjective', 'old', 'intermediate'] },
  { word: 'נשוי', difficulty: 2, tags: ['adjective', 'married', 'intermediate'] },
  { word: 'רווק', difficulty: 2, tags: ['adjective', 'single', 'intermediate'] },
  { word: 'בטוח', difficulty: 2, tags: ['adjective', 'safe', 'intermediate'] },
  { word: 'מסוכן', difficulty: 2, tags: ['adjective', 'dangerous', 'intermediate'] },
  { word: 'חופשי', difficulty: 2, tags: ['adjective', 'free', 'intermediate'] },
  { word: 'אסור', difficulty: 2, tags: ['adjective', 'forbidden', 'intermediate'] },
  { word: 'מותר', difficulty: 2, tags: ['adjective', 'allowed', 'intermediate'] },
  { word: 'פשוט', difficulty: 2, tags: ['adjective', 'simple', 'intermediate'] },
  { word: 'מסובך', difficulty: 2, tags: ['adjective', 'complicated', 'intermediate'] },
  { word: 'רגיל', difficulty: 2, tags: ['adjective', 'normal', 'intermediate'] },
  { word: 'מיוחד', difficulty: 2, tags: ['adjective', 'special', 'intermediate'] },
  { word: 'מלא', difficulty: 2, tags: ['adjective', 'full', 'intermediate'] },
  { word: 'ריק', difficulty: 2, tags: ['adjective', 'empty', 'intermediate'] },
  { word: 'פתוח', difficulty: 2, tags: ['adjective', 'open', 'intermediate'] },
  { word: 'סגור', difficulty: 2, tags: ['adjective', 'closed', 'intermediate'] },
  { word: 'זריז', difficulty: 2, tags: ['adjective', 'quick', 'intermediate'] },
  { word: 'איטי', difficulty: 2, tags: ['adjective', 'slow', 'intermediate'] },
  { word: 'רעב', difficulty: 2, tags: ['adjective', 'hungry', 'intermediate'] },
  { word: 'צמא', difficulty: 2, tags: ['adjective', 'thirsty', 'intermediate'] },
  { word: 'עייף', difficulty: 2, tags: ['adjective', 'tired', 'intermediate'] },
  { word: 'נמרץ', difficulty: 2, tags: ['adjective', 'energetic', 'intermediate'] },

  // === Difficulty 3: Advanced ===
  { word: 'ממשלה', difficulty: 3, tags: ['noun', 'government', 'advanced'] },
  { word: 'כנסת', difficulty: 3, tags: ['noun', 'parliament', 'advanced'] },
  { word: 'צבא', difficulty: 3, tags: ['noun', 'army', 'advanced'] },
  { word: 'משטרה', difficulty: 3, tags: ['noun', 'police', 'advanced'] },
  { word: 'בית חולים', difficulty: 3, tags: ['noun', 'hospital', 'advanced'] },
  { word: 'בית כנסת', difficulty: 3, tags: ['noun', 'synagogue', 'advanced'] },
  { word: 'כנסיה', difficulty: 3, tags: ['noun', 'church', 'advanced'] },
  { word: 'מסגד', difficulty: 3, tags: ['noun', 'mosque', 'advanced'] },
  { word: 'מסעדה', difficulty: 3, tags: ['noun', 'restaurant', 'advanced'] },
  { word: 'מכולת', difficulty: 3, tags: ['noun', 'grocery', 'advanced'] },
  { word: 'סופרמרקט', difficulty: 3, tags: ['noun', 'supermarket', 'loanword', 'advanced'] },
  { word: 'מחשב', difficulty: 3, tags: ['noun', 'computer', 'advanced'] },
  { word: 'טלפון', difficulty: 3, tags: ['noun', 'phone', 'advanced'] },
  { word: 'טלוויזיה', difficulty: 3, tags: ['noun', 'television', 'loanword', 'advanced'] },
  { word: 'רדיו', difficulty: 3, tags: ['noun', 'radio', 'loanword', 'advanced'] },
  { word: 'עיתון', difficulty: 3, tags: ['noun', 'newspaper', 'advanced'] },
  { word: 'מגזין', difficulty: 3, tags: ['noun', 'magazine', 'loanword', 'advanced'] },
  { word: 'ספריה', difficulty: 3, tags: ['noun', 'library', 'advanced'] },
  { word: 'מוזיאון', difficulty: 3, tags: ['noun', 'museum', 'loanword', 'advanced'] },
  { word: 'תיאטרון', difficulty: 3, tags: ['noun', 'theater', 'loanword', 'advanced'] },
  { word: 'קולנוע', difficulty: 3, tags: ['noun', 'cinema', 'advanced'] },
  { word: 'תחנה', difficulty: 3, tags: ['noun', 'station', 'advanced'] },
  { word: 'שדה תעופה', difficulty: 3, tags: ['noun', 'airport', 'advanced'] },
  { word: 'נמל', difficulty: 3, tags: ['noun', 'port', 'advanced'] },
  { word: 'מסילה', difficulty: 3, tags: ['noun', 'railway', 'advanced'] },
  { word: 'גשר', difficulty: 3, tags: ['noun', 'bridge', 'advanced'] },
  { word: 'מנהרה', difficulty: 3, tags: ['noun', 'tunnel', 'advanced'] },
  { word: 'כיכר', difficulty: 3, tags: ['noun', 'square', 'advanced'] },
  { word: 'שכונה', difficulty: 3, tags: ['noun', 'neighborhood', 'advanced'] },
  { word: 'בנק', difficulty: 3, tags: ['noun', 'bank', 'loanword', 'advanced'] },
  { word: 'דואר', difficulty: 3, tags: ['noun', 'mail', 'advanced'] },
  { word: 'תשלום', difficulty: 3, tags: ['noun', 'payment', 'advanced'] },
  { word: 'חשבון', difficulty: 3, tags: ['noun', 'account', 'advanced'] },
  { word: 'כרטיס', difficulty: 3, tags: ['noun', 'card', 'advanced'] },
  { word: 'כסף', difficulty: 3, tags: ['noun', 'money', 'advanced'] },
  { word: 'מטבע', difficulty: 3, tags: ['noun', 'currency', 'advanced'] },
  { word: 'שטר', difficulty: 3, tags: ['noun', 'bill', 'advanced'] },
  { word: 'מטבעה', difficulty: 3, tags: ['noun', 'exchange', 'advanced'] },
  { word: 'מחיר', difficulty: 3, tags: ['noun', 'price', 'advanced'] },
  { word: 'הנחה', difficulty: 3, tags: ['noun', 'discount', 'advanced'] },
  { word: 'מבצע', difficulty: 3, tags: ['noun', 'sale', 'advanced'] },
  { word: 'קניה', difficulty: 3, tags: ['noun', 'purchase', 'advanced'] },
  { word: 'מכירה', difficulty: 3, tags: ['noun', 'sale', 'advanced'] },
  { word: 'לקוח', difficulty: 3, tags: ['noun', 'customer', 'advanced'] },
  { word: 'מוכר', difficulty: 3, tags: ['noun', 'seller', 'advanced'] },
  { word: 'עסק', difficulty: 3, tags: ['noun', 'business', 'advanced'] },
  { word: 'חברה', difficulty: 3, tags: ['noun', 'company', 'advanced'] },
  { word: 'מפעל', difficulty: 3, tags: ['noun', 'factory', 'advanced'] },
  { word: 'משרד', difficulty: 3, tags: ['noun', 'office', 'advanced'] },
  { word: 'פגישה', difficulty: 3, tags: ['noun', 'meeting', 'advanced'] },
  { word: 'הצלחה', difficulty: 3, tags: ['noun', 'success', 'advanced'] },
  { word: 'כישלון', difficulty: 3, tags: ['noun', 'failure', 'advanced'] },
  { word: 'סיכוי', difficulty: 3, tags: ['noun', 'chance', 'advanced'] },
  { word: 'סיכון', difficulty: 3, tags: ['noun', 'risk', 'advanced'] },
  { word: 'בעיה', difficulty: 3, tags: ['noun', 'problem', 'advanced'] },
  { word: 'פתרון', difficulty: 3, tags: ['noun', 'solution', 'advanced'] },
  { word: 'שאלה', difficulty: 3, tags: ['noun', 'question', 'advanced'] },
  { word: 'תשובה', difficulty: 3, tags: ['noun', 'answer', 'advanced'] },
  { word: 'דוגמה', difficulty: 3, tags: ['noun', 'example', 'advanced'] },
  { word: 'הסבר', difficulty: 3, tags: ['noun', 'explanation', 'advanced'] },
  { word: 'תיאור', difficulty: 3, tags: ['noun', 'description', 'advanced'] },
  { word: 'סיבה', difficulty: 3, tags: ['noun', 'reason', 'advanced'] },
  { word: 'תוצאה', difficulty: 3, tags: ['noun', 'result', 'advanced'] },
  { word: 'מטרה', difficulty: 3, tags: ['noun', 'goal', 'advanced'] },
  { word: 'דרך', difficulty: 3, tags: ['noun', 'way', 'advanced'] },
  { word: 'אמצעי', difficulty: 3, tags: ['noun', 'means', 'advanced'] },
  { word: 'צורך', difficulty: 3, tags: ['noun', 'need', 'advanced'] },
  { word: 'רצון', difficulty: 3, tags: ['noun', 'desire', 'advanced'] },
  { word: 'יכולת', difficulty: 3, tags: ['noun', 'ability', 'advanced'] },
  { word: 'ידע', difficulty: 3, tags: ['noun', 'knowledge', 'advanced'] },
  { word: 'מידע', difficulty: 3, tags: ['noun', 'information', 'advanced'] },
  { word: 'חדשות', difficulty: 3, tags: ['noun', 'news', 'advanced'] },
  { word: 'תקשורת', difficulty: 3, tags: ['noun', 'communication', 'advanced'] },
  { word: 'שפה', difficulty: 3, tags: ['noun', 'language', 'advanced'] },
  { word: 'מילה', difficulty: 3, tags: ['noun', 'word', 'advanced'] },
  { word: 'משפט', difficulty: 3, tags: ['noun', 'sentence', 'advanced'] },
  { word: 'פסוק', difficulty: 3, tags: ['noun', 'verse', 'advanced'] },
  { word: 'סיפור', difficulty: 3, tags: ['noun', 'story', 'advanced'] },
  { word: 'ספר', difficulty: 3, tags: ['noun', 'book', 'advanced'] },
  { word: 'כתבה', difficulty: 3, tags: ['noun', 'article', 'advanced'] },
  { word: 'חיבור', difficulty: 3, tags: ['noun', 'essay', 'advanced'] },
  { word: 'מכתב', difficulty: 3, tags: ['noun', 'letter', 'advanced'] },
  { word: 'הודעה', difficulty: 3, tags: ['noun', 'message', 'advanced'] },
  { word: 'דואל', difficulty: 3, tags: ['noun', 'email', 'loanword', 'advanced'] },
  { word: 'אינטרנט', difficulty: 3, tags: ['noun', 'internet', 'loanword', 'advanced'] },
  { word: 'אתר', difficulty: 3, tags: ['noun', 'website', 'advanced'] },
  { word: 'דף', difficulty: 3, tags: ['noun', 'page', 'advanced'] },
  { word: 'קישור', difficulty: 3, tags: ['noun', 'link', 'advanced'] },
  { word: 'תמונה', difficulty: 3, tags: ['noun', 'picture', 'advanced'] },
  { word: 'וידאו', difficulty: 3, tags: ['noun', 'video', 'loanword', 'advanced'] },
  { word: 'מוזיקה', difficulty: 3, tags: ['noun', 'music', 'loanword', 'advanced'] },
  { word: 'שיר', difficulty: 3, tags: ['noun', 'song', 'advanced'] },
  { word: 'ניגון', difficulty: 3, tags: ['noun', 'melody', 'advanced'] },
  { word: 'מקצב', difficulty: 3, tags: ['noun', 'rhythm', 'advanced'] },
  { word: 'כלי נגינה', difficulty: 3, tags: ['noun', 'instrument', 'advanced'] },
  { word: 'תזמורת', difficulty: 3, tags: ['noun', 'orchestra', 'advanced'] },
  { word: 'מקהלה', difficulty: 3, tags: ['noun', 'choir', 'advanced'] },
];

export default hebrewWordlist;
