/**
 * Japanese wordlist with 200+ common words organized by difficulty
 * Includes Hiragana, Katakana, and Kanji for typing practice
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Japanese wordlist - 200+ common words
 * Difficulty 1: Basic Hiragana (46 characters)
 * Difficulty 2: Common Katakana and simple Kanji words
 * Difficulty 3: Advanced vocabulary with complex Kanji
 */
export const japaneseWordlist: WordlistEntry[] = [
  // === Difficulty 1: Hiragana Basics ===
  { word: 'あめ', difficulty: 1, tags: ['hiragana', 'weather', 'basic'] },
  { word: 'いぬ', difficulty: 1, tags: ['hiragana', 'animal', 'basic'] },
  { word: 'うみ', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'えき', difficulty: 1, tags: ['hiragana', 'place', 'basic'] },
  { word: 'おかね', difficulty: 1, tags: ['hiragana', 'money', 'basic'] },
  { word: 'かお', difficulty: 1, tags: ['hiragana', 'body', 'basic'] },
  { word: 'きく', difficulty: 1, tags: ['hiragana', 'verb', 'basic'] },
  { word: 'くうき', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'くるま', difficulty: 1, tags: ['hiragana', 'vehicle', 'basic'] },
  { word: 'けしき', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'こめ', difficulty: 1, tags: ['hiragana', 'food', 'basic'] },
  { word: 'さくら', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'しずか', difficulty: 1, tags: ['hiragana', 'adjective', 'basic'] },
  { word: 'すし', difficulty: 1, tags: ['hiragana', 'food', 'basic'] },
  { word: 'せかい', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'そと', difficulty: 1, tags: ['hiragana', 'place', 'basic'] },
  { word: 'たび', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'ちず', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'つき', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'てぶろ', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'とりがい', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'なし', difficulty: 1, tags: ['hiragana', 'fruit', 'basic'] },
  { word: 'にほん', difficulty: 1, tags: ['hiragana', 'country', 'basic'] },
  { word: 'ぬま', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'ねこ', difficulty: 1, tags: ['hiragana', 'animal', 'basic'] },
  { word: 'のはら', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'はし', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'ひと', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'ふね', difficulty: 1, tags: ['hiragana', 'vehicle', 'basic'] },
  { word: 'へや', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'ほし', difficulty: 1, tags: ['hiragana', 'nature', 'basic'] },
  { word: 'みち', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'むすめ', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'めがね', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'もじ', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'やさい', difficulty: 1, tags: ['hiragana', 'food', 'basic'] },
  { word: 'ゆうき', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'よこはま', difficulty: 1, tags: ['hiragana', 'place', 'basic'] },
  { word: 'らいねん', difficulty: 1, tags: ['hiragana', 'time', 'basic'] },
  { word: 'るす', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'れきし', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'ろぼっと', difficulty: 1, tags: ['hiragana', 'noun', 'basic'] },
  { word: 'わに', difficulty: 1, tags: ['hiragana', 'animal', 'basic'] },

  // === Difficulty 2: Katakana and Simple Kanji ===
  { word: 'アメリカ', difficulty: 2, tags: ['katakana', 'country', 'intermediate'] },
  { word: 'ヨーロッパ', difficulty: 2, tags: ['katakana', 'country', 'intermediate'] },
  { word: 'アジア', difficulty: 2, tags: ['katakana', 'region', 'intermediate'] },
  { word: 'コンピューター', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'インターネット', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'スマートフォン', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'テレビ', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'ラジオ', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'カメラ', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'パン', difficulty: 2, tags: ['katakana', 'food', 'intermediate'] },
  { word: 'コーヒー', difficulty: 2, tags: ['katakana', 'food', 'intermediate'] },
  { word: 'アイス', difficulty: 2, tags: ['katakana', 'food', 'intermediate'] },
  { word: '牛奶', difficulty: 2, tags: ['katakana', 'food', 'intermediate'] },
  { word: 'ドライバー', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'チーム', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'ビジネス', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'デザイン', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'プログラム', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'データ', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'システム', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'ネットワーク', difficulty: 2, tags: ['katakana', 'technology', 'intermediate'] },
  { word: 'サービス', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'コントロール', difficulty: 2, tags: ['katakana', 'verb', 'intermediate'] },
  { word: 'バランス', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'エネルギー', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'シーズン', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'キャラクター', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'メッセージ', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'ボタン', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'マンション', difficulty: 2, tags: ['katakana', 'building', 'intermediate'] },
  { word: 'プレゼンテーション', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'リクエスト', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'ニュアンス', difficulty: 2, tags: ['katakana', 'noun', 'intermediate'] },
  { word: 'シンプル', difficulty: 2, tags: ['katakana', 'adjective', 'intermediate'] },
  { word: 'クール', difficulty: 2, tags: ['katakana', 'adjective', 'intermediate'] },
  { word: 'クラシック', difficulty: 2, tags: ['katakana', 'music', 'intermediate'] },
  { word: 'ピンク', difficulty: 2, tags: ['katakana', 'color', 'intermediate'] },
  { word: 'ブルー', difficulty: 2, tags: ['katakana', 'color', 'intermediate'] },
  { word: 'グリーン', difficulty: 2, tags: ['katakana', 'color', 'intermediate'] },
  { word: 'ワンちゃん', difficulty: 2, tags: ['katakana', 'animal', 'intermediate'] },
  { word: 'ラーメン', difficulty: 2, tags: ['katakana', 'food', 'intermediate'] },
  { word: 'タクシー', difficulty: 2, tags: ['katakana', 'vehicle', 'intermediate'] },

  // === Difficulty 3: Advanced Kanji and Keigo ===
  { word: '日本語', difficulty: 3, tags: ['kanji', 'language', 'advanced'] },
  { word: '漢字', difficulty: 3, tags: ['kanji', 'language', 'advanced'] },
  { word: '勉強', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '先生', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: '学生', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: '会社', difficulty: 3, tags: ['kanji', 'business', 'advanced'] },
  { word: '銀行', difficulty: 3, tags: ['kanji', 'finance', 'advanced'] },
  { word: '病院', difficulty: 3, tags: ['kanji', 'place', 'advanced'] },
  { word: '駅', difficulty: 3, tags: ['kanji', 'place', 'advanced'] },
  { word: '空港', difficulty: 3, tags: ['kanji', 'place', 'advanced'] },
  { word: '旅行', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '予約', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '計画', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '実現', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '経験', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '説明', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '約束', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '準備', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '質問', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '回答', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '感謝', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '道歉', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '紹介', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '会議', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '報告', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '練習', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '説明', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '理解', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '表現', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '環境', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '問題', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '解決', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '成功', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '失敗', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '努力', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '約束', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '提供', difficulty: 3, tags: ['kanji', 'verb', 'advanced'] },
  { word: '関係', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '影響', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '結果', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '理由', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '方法', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '場合', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '人生', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '仕事', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '生活', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '世界', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '社会', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '文化', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '科学', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '技術', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '経済', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '政治', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '歴史', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '地理', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '芸術', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '音楽', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '映画', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '写真', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '新聞', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '雑誌', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '本', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '音楽', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '電話', difficulty: 3, tags: ['kanji', 'noun', 'advanced'] },
  { word: '電車', difficulty: 3, tags: ['kanji', 'vehicle', 'advanced'] },
  { word: '飛行機', difficulty: 3, tags: ['kanji', 'vehicle', 'advanced'] },
  { word: '船', difficulty: 3, tags: ['kanji', 'vehicle', 'advanced'] },
  { word: '医者', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: '看護師', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: '弁護士', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: '会計士', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: ' Architect', difficulty: 3, tags: ['kanji', 'occupation', 'advanced'] },
  { word: 'デザイナー', difficulty: 3, tags: ['katakana', 'occupation', 'advanced'] },
  { word: 'エンジニア', difficulty: 3, tags: ['katakana', 'occupation', 'advanced'] },
  { word: 'マネージャー', difficulty: 3, tags: ['katakana', 'occupation', 'advanced'] },
  { word: 'コンサルタント', difficulty: 3, tags: ['katakana', 'occupation', 'advanced'] },
];

export default japaneseWordlist;
