/**
 * Dutch wordlist with 210+ common words organized by difficulty
 * Includes Dutch-specific characters: ij, ö, é, è
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Dutch wordlist - 210+ common words
 * Difficulty 1: Basic articles, pronouns, common verbs, simple words
 * Difficulty 2: Intermediate vocabulary
 * Difficulty 3: Advanced words with Dutch-specific characters and abstract concepts
 */
export const dutchWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'de', difficulty: 1, tags: ['article', 'basic'] },
  { word: 'het', difficulty: 1, tags: ['article', 'neuter', 'basic'] },
  { word: 'een', difficulty: 1, tags: ['article', 'basic'] },
  { word: 'en', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'of', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'is', difficulty: 1, tags: ['verb', 'zijn', 'basic'] },
  { word: 'zijn', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'was', difficulty: 1, tags: ['verb', 'zijn', 'past', 'basic'] },
  { word: 'hebben', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'worden', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'ik', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'jij', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'hij', difficulty: 1, tags: ['pronoun', 'masculine', 'basic'] },
  { word: 'zij', difficulty: 1, tags: ['pronoun', 'feminine', 'plural', 'basic'] },
  { word: 'het', difficulty: 1, tags: ['pronoun', 'neuter', 'basic'] },
  { word: 'wij', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'jullie', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'niet', difficulty: 1, tags: ['adverb', 'negation', 'basic'] },
  { word: 'ook', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'zo', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'heel', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'erg', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'goed', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'nieuw', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'oud', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'groot', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'klein', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'lang', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'kort', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'wat', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'wie', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'waar', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'wanneer', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'waarom', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'ja', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'nee', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'alsjeblieft', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'dank', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'hoi', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'dag', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'avond', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'nacht', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'man', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'vrouw', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'kind', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'jaar', difficulty: 1, tags: ['noun', 'neuter', 'time', 'basic'] },
  { word: 'week', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'maand', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'uur', difficulty: 1, tags: ['noun', 'neuter', 'time', 'basic'] },
  { word: 'minuut', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'seconde', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'stad', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'land', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'wereld', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'leven', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'tijd', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'eten', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'drinken', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'slapen', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'wonen', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'werk', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'school', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'universiteit', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'hier', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'daar', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'nu', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'dan', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'altijd', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'vaak', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'veel', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'weinig', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'alle', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'vele', difficulty: 1, tags: ['adjective', 'plural', 'basic'] },
  { word: 'mijn', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'jouw', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'zijn', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'haar', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'ons', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'jullie', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'hun', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'deze', difficulty: 1, tags: ['demonstrative', 'basic'] },
  { word: 'die', difficulty: 1, tags: ['demonstrative', 'basic'] },
  { word: 'dit', difficulty: 1, tags: ['demonstrative', 'neuter', 'basic'] },
  { word: 'dat', difficulty: 1, tags: ['demonstrative', 'neuter', 'basic'] },

  // === Difficulty 2: Intermediate ===
  { word: 'werken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'weten', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'denken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'spreken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'lezen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'schrijven', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'komen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'gaan', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'blijven', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'vinden', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'geven', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'tonen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'heten', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'menen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'zeggen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'vragen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'hoeven', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'begrijpen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'kennen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'leren', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'rijden', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'vliegen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'zwemmen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'dansen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'zingen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'koken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'huis', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'auto', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'trein', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'vliegtuig', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'ziek', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'gezond', difficulty: 2, tags: ['adjective', 'intermediate'] },
  { word: 'arts', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'ziekenhuis', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'boek', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'woord', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'vraag', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'antwoord', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'probleem', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'idee', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'muziek', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'lied', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'sport', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'spelen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'rennen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'water', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'brood', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'vlees', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'groente', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'fruit', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'koffie', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'thee', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'vriend', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'familie', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'moeder', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'vader', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'broer', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'zus', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'computer', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'internet', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'email', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'telefoon', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'geld', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'straat', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'reizen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'beginnen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'helpen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'maken', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'zien', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'horen', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'voelen', difficulty: 2, tags: ['verb', 'intermediate'] },

  // === Difficulty 3: Advanced ===
  { word: 'mogelijkheid', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'verantwoordelijkheid', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'relatie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'ervaring', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'kennis', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'milieu', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'samenvleving', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'democratie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'verkiezingen', difficulty: 3, tags: ['noun', 'plural', 'advanced'] },
  { word: 'economie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'politiek', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'cultuur', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'wetenschap', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'technologie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'onderzoek', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'theorie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'proces', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'product', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'systeem', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'conditie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'situatie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'realiteit', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'gemeenschap', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'organisatie', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'internationaal', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'professioneel', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'persoonlijk', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'nationaal', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'economisch', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'politiek', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'cultureel', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'sociaal', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'historisch', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'wetenschappelijk', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'milieuvevriendelijk', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'traditioneel', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'religieus', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'fundamenteel', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'belangrijk', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'begrijpen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'overwegen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'ontwikkelen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'verschaffen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'voortzetten', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'gebeuren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'geloven', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'verwachten', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'voorstellen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'onthouden', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'bepalen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'beschrijven', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'herkennen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'identificeren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'vestigen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'produceren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'creëren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'verbeteren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'uitleggen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'toepassen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'rapporteren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'deelnemen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'ondersteunen', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'profiteren', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'bereiken', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'echter', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'daarom', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'hoewel', difficulty: 3, tags: ['conjunction', 'advanced'] },
  { word: 'daardoor', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'toch', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'bovendien', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'bijzonder', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'gelijksoortig', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'verschillend', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'mogelijk', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'nodig', difficulty: 3, tags: ['adjective', 'advanced'] },
];

export default dutchWordlist;
