/**
 * Polish wordlist with 210+ common words organized by difficulty
 * Includes Polish-specific characters: ą, ć, ę, ł, ń, ó, ś, ź, ż
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Polish wordlist - 210+ common words
 * Difficulty 1: Basic articles, pronouns, common verbs, simple words
 * Difficulty 2: Intermediate vocabulary
 * Difficulty 3: Advanced words with Polish-specific characters and abstract concepts
 */
export const polishWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'a', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'i', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'o', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'u', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'y', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'w', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'z', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'do', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'na', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'za', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'po', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'od', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'przy', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'ze', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'lub', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'oraz', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'ale', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'że', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'czy', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'jest', difficulty: 1, tags: ['verb', 'być', 'basic'] },
  { word: 'są', difficulty: 1, tags: ['verb', 'być', 'plural', 'basic'] },
  { word: 'był', difficulty: 1, tags: ['verb', 'być', 'past', 'basic'] },
  { word: 'byli', difficulty: 1, tags: ['verb', 'być', 'plural', 'past', 'basic'] },
  { word: 'mieć', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'robić', difficulty: 1, tags: ['verb', 'basic'] },
  { word: 'ja', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'ty', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'on', difficulty: 1, tags: ['pronoun', 'masculine', 'basic'] },
  { word: 'ona', difficulty: 1, tags: ['pronoun', 'feminine', 'basic'] },
  { word: 'ono', difficulty: 1, tags: ['pronoun', 'neuter', 'basic'] },
  { word: 'my', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'wy', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'oni', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'one', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'to', difficulty: 1, tags: ['pronoun', 'neuter', 'basic'] },
  { word: 'ten', difficulty: 1, tags: ['demonstrative', 'masculine', 'basic'] },
  { word: 'ta', difficulty: 1, tags: ['demonstrative', 'feminine', 'basic'] },
  { word: 'te', difficulty: 1, tags: ['demonstrative', 'plural', 'basic'] },
  { word: 'co', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'kto', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'gdzie', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'kiedy', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'jak', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'dlaczego', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'tak', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'nie', difficulty: 1, tags: ['adverb', 'negation', 'basic'] },
  { word: 'proszę', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'dziękuję', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'cześć', difficulty: 1, tags: ['interjection', 'basic'] },
  { word: 'dzień', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'dobry', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'wieczór', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'noc', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'rok', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'miesiąc', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'tydzień', difficulty: 1, tags: ['noun', 'masculine', 'time', 'basic'] },
  { word: 'godzina', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'minuta', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'sekunda', difficulty: 1, tags: ['noun', 'feminine', 'time', 'basic'] },
  { word: 'miasto', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'wieś', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'kraj', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'świat', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'życie', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'czas', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'człowiek', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'mężczyzna', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'kobieta', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'dziecko', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'ludzie', difficulty: 1, tags: ['noun', 'plural', 'basic'] },
  { word: 'ręka', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'noga', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'głowa', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'oko', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'ucho', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'usta', difficulty: 1, tags: ['noun', 'plural', 'basic'] },
  { word: 'nos', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'serce', difficulty: 1, tags: ['noun', 'neuter', 'basic'] },
  { word: 'dom', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'rodzina', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'matka', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'ojciec', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'brat', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'siostra', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'syn', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'córka', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'wujek', difficulty: 1, tags: ['noun', 'masculine', 'basic'] },
  { word: 'ciocia', difficulty: 1, tags: ['noun', 'feminine', 'basic'] },
  { word: 'tutaj', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'tam', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'teraz', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'potem', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'zawsze', difficulty: 1, tags: ['adverb', 'time', 'basic'] },
  { word: 'często', difficulty: 1, tags: ['adverb', 'basic'] },
  { word: 'dużo', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'mało', difficulty: 1, tags: ['adjective', 'basic'] },
  { word: 'wszystko', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'każdy', difficulty: 1, tags: ['adjective', 'basic'] },

  // === Difficulty 2: Intermediate ===
  { word: 'pracować', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'wiedzieć', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'myśleć', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'mówić', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'czytać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'pisać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'przyjść', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'iść', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'zostać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'znaleźć', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'dać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'pokazać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'nazywać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'pytać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'rozumieć', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'znać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'uczyć się', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'jechać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'lecieć', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'pływać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'tańczyć', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'śpiewać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'gotować', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'jeść', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'pić', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'spać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'mieszkać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'auto', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'pociąg', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'samolot', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'lotnisko', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'szkoła', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'uniwersytet', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'student', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'nauczyciel', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'książka', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'słowo', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'pytanie', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'odpowiedź', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'problem', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'pomysł', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'muzyka', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'piosenka', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'sport', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'grać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'biegać', difficulty: 2, tags: ['verb', 'intermediate'] },
  { word: 'woda', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'chleb', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'mięso', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'warzywo', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'owoc', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'kawa', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'herbata', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'wino', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'przyjaciel', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'babcia', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'dziadek', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'komputer', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'internet', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'email', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'telefon', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'pieniądze', difficulty: 2, tags: ['noun', 'plural', 'intermediate'] },
  { word: 'praca', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'ulica', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'choroba', difficulty: 2, tags: ['noun', 'feminine', 'intermediate'] },
  { word: 'zdrowie', difficulty: 2, tags: ['noun', 'neuter', 'intermediate'] },
  { word: 'lekarz', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },
  { word: 'szpital', difficulty: 2, tags: ['noun', 'masculine', 'intermediate'] },

  // === Difficulty 3: Advanced ===
  { word: 'możliwość', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'odpowiedzialność', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'związek', difficulty: 3, tags: ['noun', 'masculine', 'advanced'] },
  { word: 'doświadczenie', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'wiedza', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'środowisko', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'społeczeństwo', difficulty: 3, tags: ['noun', 'neuter', 'advanced'] },
  { word: 'demokracja', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'wybory', difficulty: 3, tags: ['noun', 'plural', 'advanced'] },
  { word: 'gospodarka', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'polityka', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'kultura', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'nauka', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'technologia', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'badania', difficulty: 3, tags: ['noun', 'plural', 'advanced'] },
  { word: 'teoria', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'proces', difficulty: 3, tags: ['noun', 'masculine', 'advanced'] },
  { word: 'produkt', difficulty: 3, tags: ['noun', 'masculine', 'advanced'] },
  { word: 'system', difficulty: 3, tags: ['noun', 'masculine', 'advanced'] },
  { word: 'warunki', difficulty: 3, tags: ['noun', 'plural', 'advanced'] },
  { word: 'sytuacja', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'rzeczywistość', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'społeczność', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'organizacja', difficulty: 3, tags: ['noun', 'feminine', 'advanced'] },
  { word: 'międzynarodowy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'zawodowy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'osobisty', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'narodowy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'gospodarczy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'polityczny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'kulturalny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'społeczny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'historyczny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'naukowy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'środowiskowy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'tradycyjny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'religijny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'fundamentalny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'znaczący', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'rozumieć', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'rozważać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'rozwijać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'dostarczać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kontynuować', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'zdarzać się', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'wierzyć', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'oczekiwać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'sugerować', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'pamiętać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'określać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'opisywać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'rozpoznawać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'identyfikować', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'ustalać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'produkować', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'tworzyć', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'poprawiać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'wyjaśniać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'stosować', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'raportować', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'uczestniczyć', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'wspierać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'korzystać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'osiągać', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'jednak', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'dlatego', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'aczkolwiek', difficulty: 3, tags: ['conjunction', 'advanced'] },
  { word: 'mimo to', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'ponadto', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'szczególnie', difficulty: 3, tags: ['adverb', 'advanced'] },
  { word: 'podobny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'różny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'możliwy', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'konieczny', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'ważny', difficulty: 3, tags: ['adjective', 'advanced'] },
];

export default polishWordlist;
