/**
 * Brazilian Portuguese Wordlist — TypeForge Curriculum
 *
 * @license CC BY-SA 4.0
 * @standards Ortografiaivahookrules: ABL, VOLP
 *
 * Minimum 210 entries:
 *   ~60 at difficulty 1 (short, high-frequency)
 *   ~90 at difficulty 2 (common vocabulary)
 *   ~60 at difficulty 3 (abstract, professional)
 *
 * Tags:
 *   article | pronoun | verb | preposition | conjunction | adverb | adjective |
 *   noun | determiner | number | greeting | time | food | family | work |
 *   education | health | travel | nature | technology | emotion | sport |
 *   art | geography | religion | politics | science | idiom
 *
 * Notes:
 *   - Brazilian Portuguese orthography (Novo AO)
 *   - Brazilian-specific terms included where distinct from European Portuguese
 *   - Acentos preserved where orthographically required
 */

import type { WordlistEntry } from './index.js';

export const brasileiroWordlist: WordlistEntry[] = [
  // ── Difficulty 1 ────────────────────────────────────────────────────────────
  { word: 'o', difficulty: 1, tags: ['article'] },
  { word: 'a', difficulty: 1, tags: ['article'] },
  { word: 'os', difficulty: 1, tags: ['article'] },
  { word: 'as', difficulty: 1, tags: ['article'] },
  { word: 'um', difficulty: 1, tags: ['article'] },
  { word: 'uma', difficulty: 1, tags: ['article'] },
  { word: 'de', difficulty: 1, tags: ['preposition'] },
  { word: 'da', difficulty: 1, tags: ['preposition'] },
  { word: 'do', difficulty: 1, tags: ['preposition'] },
  { word: 'em', difficulty: 1, tags: ['preposition'] },
  { word: 'na', difficulty: 1, tags: ['preposition'] },
  { word: 'no', difficulty: 1, tags: ['preposition'] },
  { word: 'por', difficulty: 1, tags: ['preposition'] },
  { word: 'para', difficulty: 1, tags: ['preposition'] },
  { word: 'com', difficulty: 1, tags: ['preposition'] },
  { word: 'e', difficulty: 1, tags: ['conjunction'] },
  { word: 'mas', difficulty: 1, tags: ['conjunction'] },
  { word: 'ou', difficulty: 1, tags: ['conjunction'] },
  { word: 'é', difficulty: 1, tags: ['verb'] },
  { word: 'sou', difficulty: 1, tags: ['verb'] },
  { word: 'somos', difficulty: 1, tags: ['verb'] },
  { word: 'são', difficulty: 1, tags: ['verb'] },
  { word: 'ser', difficulty: 1, tags: ['verb'] },
  { word: 'estar', difficulty: 1, tags: ['verb'] },
  { word: 'estou', difficulty: 1, tags: ['verb'] },
  { word: 'está', difficulty: 1, tags: ['verb'] },
  { word: 'estão', difficulty: 1, tags: ['verb'] },
  { word: 'tenho', difficulty: 1, tags: ['verb'] },
  { word: 'tem', difficulty: 1, tags: ['verb'] },
  { word: 'temos', difficulty: 1, tags: ['verb'] },
  { word: 'eu', difficulty: 1, tags: ['pronoun'] },
  { word: 'você', difficulty: 1, tags: ['pronoun'] },
  { word: 'ele', difficulty: 1, tags: ['pronoun'] },
  { word: 'ela', difficulty: 1, tags: ['pronoun'] },
  { word: 'a gente', difficulty: 1, tags: ['pronoun'] },
  { word: 'nós', difficulty: 1, tags: ['pronoun'] },
  { word: 'meu', difficulty: 1, tags: ['determiner'] },
  { word: 'sua', difficulty: 1, tags: ['determiner'] },
  { word: 'esse', difficulty: 1, tags: ['determiner'] },
  { word: 'essa', difficulty: 1, tags: ['determiner'] },
  { word: 'isto', difficulty: 1, tags: ['determiner'] },
  { word: 'não', difficulty: 1, tags: ['adverb'] },
  { word: 'sim', difficulty: 1, tags: ['adverb'] },
  { word: 'já', difficulty: 1, tags: ['adverb'] },
  { word: 'bem', difficulty: 1, tags: ['adverb'] },
  { word: 'muito', difficulty: 1, tags: ['adverb'] },
  { word: 'mais', difficulty: 1, tags: ['adverb'] },
  { word: 'também', difficulty: 1, tags: ['adverb'] },
  { word: 'assim', difficulty: 1, tags: ['adverb'] },
  { word: 'dentro', difficulty: 1, tags: ['adverb'] },
  { word: 'sempre', difficulty: 1, tags: ['adverb'] },
  { word: 'aqui', difficulty: 1, tags: ['adverb'] },
  { word: 'agora', difficulty: 1, tags: ['time'] },
  { word: 'hoje', difficulty: 1, tags: ['time'] },
  { word: 'amanhã', difficulty: 1, tags: ['time'] },
  { word: 'ontem', difficulty: 1, tags: ['time'] },
  { word: 'depois', difficulty: 1, tags: ['time'] },
  { word: 'antes', difficulty: 1, tags: ['time'] },
  { word: 'bom', difficulty: 1, tags: ['greeting'] },
  { word: 'dia', difficulty: 1, tags: ['greeting'] },
  { word: 'noite', difficulty: 1, tags: ['greeting'] },

  // ── Difficulty 2 ────────────────────────────────────────────────────────────
  { word: 'gente', difficulty: 2, tags: ['noun'] },
  { word: 'pessoas', difficulty: 2, tags: ['noun'] },
  { word: 'coisa', difficulty: 2, tags: ['noun'] },
  { word: 'pessoa', difficulty: 2, tags: ['noun'] },
  { word: 'senhor', difficulty: 2, tags: ['noun'] },
  { word: 'senhora', difficulty: 2, tags: ['noun'] },
  { word: 'menino', difficulty: 2, tags: ['noun'] },
  { word: 'menina', difficulty: 2, tags: ['noun'] },
  { word: 'moço', difficulty: 2, tags: ['noun'] },
  { word: 'moça', difficulty: 2, tags: ['noun'] },
  { word: 'pai', difficulty: 2, tags: ['family'] },
  { word: 'mãe', difficulty: 2, tags: ['family'] },
  { word: 'filho', difficulty: 2, tags: ['family'] },
  { word: 'filha', difficulty: 2, tags: ['family'] },
  { word: 'irmão', difficulty: 2, tags: ['family'] },
  { word: 'irmã', difficulty: 2, tags: ['family'] },
  { word: 'avô', difficulty: 2, tags: ['family'] },
  { word: 'avó', difficulty: 2, tags: ['family'] },
  { word: 'casa', difficulty: 2, tags: ['noun'] },
  { word: 'trabalho', difficulty: 2, tags: ['work'] },
  { word: 'trabalhador', difficulty: 2, tags: ['work'] },
  { word: 'escola', difficulty: 2, tags: ['education'] },
  { word: 'estudante', difficulty: 2, tags: ['education'] },
  { word: 'professor', difficulty: 2, tags: ['education'] },
  { word: 'universidade', difficulty: 2, tags: ['education'] },
  { word: 'livro', difficulty: 2, tags: ['education'] },
  { word: 'café', difficulty: 2, tags: ['food'] },
  { word: 'comida', difficulty: 2, tags: ['food'] },
  { word: 'pão', difficulty: 2, tags: ['food'] },
  { word: 'arroz', difficulty: 2, tags: ['food'] },
  { word: 'feijão', difficulty: 2, tags: ['food'] },
  { word: 'carne', difficulty: 2, tags: ['food'] },
  { word: 'fruta', difficulty: 2, tags: ['food'] },
  { word: 'suco', difficulty: 2, tags: ['food'] },
  { word: 'água', difficulty: 2, tags: ['food'] },
  { word: 'restaurante', difficulty: 2, tags: ['food'] },
  { word: 'mercado', difficulty: 2, tags: ['food'] },
  { word: 'mercado', difficulty: 2, tags: ['work'] },
  { word: 'rua', difficulty: 2, tags: ['geography'] },
  { word: 'cidade', difficulty: 2, tags: ['geography'] },
  { word: 'estado', difficulty: 2, tags: ['geography'] },
  { word: 'região', difficulty: 2, tags: ['geography'] },
  { word: 'praia', difficulty: 2, tags: ['geography'] },
  { word: 'floresta', difficulty: 2, tags: ['nature'] },
  { word: 'rio', difficulty: 2, tags: ['nature'] },
  { word: 'montanha', difficulty: 2, tags: ['nature'] },
  { word: 'animal', difficulty: 2, tags: ['nature'] },
  { word: 'planta', difficulty: 2, tags: ['nature'] },
  { word: 'chuva', difficulty: 2, tags: ['nature'] },
  { word: 'tempo', difficulty: 2, tags: ['time'] },
  { word: 'hora', difficulty: 2, tags: ['time'] },
  { word: 'semana', difficulty: 2, tags: ['time'] },
  { word: 'mês', difficulty: 2, tags: ['time'] },
  { word: 'ano', difficulty: 2, tags: ['time'] },
  { word: 'frequência', difficulty: 2, tags: ['time'] },
  { word: 'manhã', difficulty: 2, tags: ['time'] },
  { word: 'tarde', difficulty: 2, tags: ['time'] },
  { word: 'vez', difficulty: 2, tags: ['time'] },
  { word: 'momento', difficulty: 2, tags: ['time'] },
  { word: 'importante', difficulty: 2, tags: ['adjective'] },
  { word: 'grande', difficulty: 2, tags: ['adjective'] },
  { word: 'pequeno', difficulty: 2, tags: ['adjective'] },
  { word: 'novo', difficulty: 2, tags: ['adjective'] },
  { word: 'velho', difficulty: 2, tags: ['adjective'] },
  { word: 'bom', difficulty: 2, tags: ['adjective'] },
  { word: 'mau', difficulty: 2, tags: ['adjective'] },
  { word: 'bonito', difficulty: 2, tags: ['adjective'] },
  { word: 'feliz', difficulty: 2, tags: ['emotion'] },
  { word: 'triste', difficulty: 2, tags: ['emotion'] },
  { word: 'bravo', difficulty: 2, tags: ['emotion'] },
  { word: 'cansado', difficulty: 2, tags: ['emotion'] },
  { word: 'ciente', difficulty: 2, tags: ['verb'] },
  { word: 'fazendo', difficulty: 2, tags: ['verb'] },
  { word: 'podendo', difficulty: 2, tags: ['verb'] },
  { word: 'querendo', difficulty: 2, tags: ['verb'] },
  { word: 'vendo', difficulty: 2, tags: ['verb'] },
  { word: 'querer', difficulty: 2, tags: ['verb'] },
  { word: 'poder', difficulty: 2, tags: ['verb'] },
  { word: 'fazer', difficulty: 2, tags: ['verb'] },
  { word: 'ver', difficulty: 2, tags: ['verb'] },
  { word: 'dizer', difficulty: 2, tags: ['verb'] },
  { word: 'dar', difficulty: 2, tags: ['verb'] },
  { word: 'tomar', difficulty: 2, tags: ['verb'] },
  { word: 'ficar', difficulty: 2, tags: ['verb'] },
  { word: 'levar', difficulty: 2, tags: ['verb'] },
  { word: 'sair', difficulty: 2, tags: ['verb'] },
  { word: 'chegar', difficulty: 2, tags: ['verb'] },
  { word: 'passar', difficulty: 2, tags: ['verb'] },
  { word: 'encontrar', difficulty: 2, tags: ['verb'] },
  { word: 'conhecer', difficulty: 2, tags: ['verb'] },
  { word: 'lembrar', difficulty: 2, tags: ['verb'] },
  { word: 'entender', difficulty: 2, tags: ['verb'] },
  { word: 'começar', difficulty: 2, tags: ['verb'] },
  { word: 'jogar', difficulty: 2, tags: ['sport'] },
  { word: 'futebol', difficulty: 2, tags: ['sport'] },
  { word: 'praia', difficulty: 2, tags: ['sport'] },
  { word: 'nadar', difficulty: 2, tags: ['sport'] },
  { word: 'dançar', difficulty: 2, tags: ['art'] },
  { word: 'cantar', difficulty: 2, tags: ['art'] },
  { word: 'escrever', difficulty: 2, tags: ['art'] },
  { word: 'ler', difficulty: 2, tags: ['art'] },
  { word: 'samba', difficulty: 2, tags: ['art'] },
  { word: 'bossa nova', difficulty: 2, tags: ['art'] },
  { word: 'carnaval', difficulty: 2, tags: ['art'] },
  { word: 'saúde', difficulty: 2, tags: ['health'] },
  { word: 'médico', difficulty: 2, tags: ['health'] },
  { word: 'hospital', difficulty: 2, tags: ['health'] },
  { word: 'remédio', difficulty: 2, tags: ['health'] },
  { word: 'doença', difficulty: 2, tags: ['health'] },
  { word: 'viajar', difficulty: 2, tags: ['travel'] },
  { word: 'ônibus', difficulty: 2, tags: ['travel'] },
  { word: 'avião', difficulty: 2, tags: ['travel'] },
  { word: 'aeroporto', difficulty: 2, tags: ['travel'] },
  { word: 'hotel', difficulty: 2, tags: ['travel'] },
  { word: 'malas', difficulty: 2, tags: ['travel'] },
  { word: 'quarto', difficulty: 2, tags: ['travel'] },
  { word: 'telefone', difficulty: 2, tags: ['technology'] },
  { word: 'computador', difficulty: 2, tags: ['technology'] },
  { word: 'internet', difficulty: 2, tags: ['technology'] },
  { word: 'aplicativo', difficulty: 2, tags: ['technology'] },
  { word: 'celular', difficulty: 2, tags: ['technology'] },
  { word: 'rede', difficulty: 2, tags: ['technology'] },
  { word: 'informação', difficulty: 2, tags: ['technology'] },
  { word: 'numero', difficulty: 2, tags: ['number'] },
  { word: 'cem', difficulty: 2, tags: ['number'] },
  { word: 'mil', difficulty: 2, tags: ['number'] },
  { word: 'primeiro', difficulty: 2, tags: ['number'] },
  { word: 'segundo', difficulty: 2, tags: ['number'] },
  { word: 'último', difficulty: 2, tags: ['number'] },
  { word: 'Santo', difficulty: 2, tags: ['religion'] },
  { word: 'igreja', difficulty: 2, tags: ['religion'] },
  { word: 'rezar', difficulty: 2, tags: ['religion'] },

  // ── Difficulty 3 ────────────────────────────────────────────────────────────
  { word: 'conhecimento', difficulty: 3, tags: ['noun', 'education'] },
  { word: 'experiência', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'desenvolvimento', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'oportunidade', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'responsabilidade', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'relacionamento', difficulty: 3, tags: ['noun', 'emotion'] },
  { word: 'consequência', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'possibilidade', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'necessidade', difficulty: 3, tags: ['noun'] },
  { word: 'realidade', difficulty: 3, tags: ['noun'] },
  { word: 'sociedade', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'política', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'governo', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'democracia', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'eleição', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'imposto', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'direito', difficulty: 3, tags: ['noun', 'politics'] },
  { word: 'obrigação', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'decisão', difficulty: 3, tags: ['noun', 'work'] },
  { word: 'resultado', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'pesquisa', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'ciência', difficulty: 3, tags: ['noun', 'science'] },
  { word: 'tecnologia', difficulty: 3, tags: ['noun', 'technology'] },
  { word: 'inteligência', difficulty: 3, tags: ['noun', 'technology'] },
  { word: 'artificial', difficulty: 3, tags: ['adjective', 'technology'] },
  { word: 'ambiental', difficulty: 3, tags: ['adjective', 'nature'] },
  { word: 'sustentável', difficulty: 3, tags: ['adjective', 'nature'] },
  { word: 'desenvolvido', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'emergente', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'educacional', difficulty: 3, tags: ['adjective', 'education'] },
  { word: 'internacional', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'profissional', difficulty: 3, tags: ['adjective', 'work'] },
  { word: 'científico', difficulty: 3, tags: ['adjective', 'science'] },
  { word: 'acontecer', difficulty: 3, tags: ['verb'] },
  { word: 'desenvolver', difficulty: 3, tags: ['verb'] },
  { word: 'continuar', difficulty: 3, tags: ['verb'] },
  { word: 'considerar', difficulty: 3, tags: ['verb'] },
  { word: 'aperfeiçoar', difficulty: 3, tags: ['verb', 'education'] },
  { word: 'participar', difficulty: 3, tags: ['verb'] },
  { word: 'contribuir', difficulty: 3, tags: ['verb'] },
  { word: 'beneficiar', difficulty: 3, tags: ['verb'] },
  { word: 'garantir', difficulty: 3, tags: ['verb'] },
  { word: 'estabelecer', difficulty: 3, tags: ['verb'] },
  { word: 'diferenciar', difficulty: 3, tags: ['verb'] },
  { word: 'identificar', difficulty: 3, tags: ['verb', 'technology'] },
  { word: 'compreender', difficulty: 3, tags: ['verb'] },
  { word: 'comunicar', difficulty: 3, tags: ['verb'] },
  { word: 'agradecer', difficulty: 3, tags: ['verb', 'emotion'] },
  { word: 'felicidades', difficulty: 3, tags: ['greeting'] },
  { word: 'parabéns', difficulty: 3, tags: ['greeting'] },
  { word: 'despedida', difficulty: 3, tags: ['greeting'] },
  { word: 'saudação', difficulty: 3, tags: ['greeting'] },
  { word: 'atenciosamente', difficulty: 3, tags: ['greeting'] },
  { word: 'cordialmente', difficulty: 3, tags: ['greeting'] },
  { word: 'jeitinho brasileiro', difficulty: 3, tags: ['idiom'] },
  { word: 'dar um jeito', difficulty: 3, tags: ['idiom'] },
  { word: 'marola', difficulty: 3, tags: ['idiom'] },
  { word: 'SAC', difficulty: 3, tags: ['work', 'technology'] },
  { word: 'samba de roda', difficulty: 3, tags: ['art'] },
  { word: 'capoeira', difficulty: 3, tags: ['art'] },
  { word: 'frevo', difficulty: 3, tags: ['art'] },
  { word: 'choro', difficulty: 3, tags: ['art'] },
  { word: 'bossa nova', difficulty: 3, tags: ['art'] },
  { word: 'tropical', difficulty: 3, tags: ['adjective', 'nature'] },
  { word: 'amazônia', difficulty: 3, tags: ['geography', 'nature'] },
  { word: 'pantanal', difficulty: 3, tags: ['geography', 'nature'] },
  { word: 'cerrado', difficulty: 3, tags: ['geography', 'nature'] },
  { word: 'caatinga', difficulty: 3, tags: ['geography', 'nature'] },
  { word: 'cotidiano', difficulty: 3, tags: ['adjective'] },
  { word: 'multicultural', difficulty: 3, tags: ['adjective', 'politics'] },
  { word: 'ribeirinho', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'nordestino', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'gaucho', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'paulista', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'baiano', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'mineiro', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'catarinense', difficulty: 3, tags: ['adjective', 'geography'] },
  { word: 'fortaleza', difficulty: 3, tags: ['noun', 'geography'] },
  { word: 'democracia', difficulty: 3, tags: ['noun', 'politics'] },
];
