/**
 * Russian wordlist with 200+ common words organized by difficulty
 * Uses Cyrillic script for Russian language practice
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Russian wordlist - 200+ common words
 * Difficulty 1: Basic words, pronouns, common verbs
 * Difficulty 2: Intermediate vocabulary, longer words
 * Difficulty 3: Advanced words with complex characters
 */
export const russianWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner (Basic words) ===
  { word: 'и', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'в', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'на', difficulty: 1, tags: ['preposition', 'basic'] },
  { word: 'я', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'ты', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'он', difficulty: 1, tags: ['pronoun', 'basic'] },
  { word: 'она', difficulty: 1, tags: ['pronoun', 'feminine', 'basic'] },
  { word: 'мы', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'вы', difficulty: 1, tags: ['pronoun', 'formal', 'basic'] },
  { word: 'они', difficulty: 1, tags: ['pronoun', 'plural', 'basic'] },
  { word: 'это', difficulty: 1, tags: ['pronoun', 'demonstrative', 'basic'] },
  { word: 'то', difficulty: 1, tags: ['pronoun', 'demonstrative', 'basic'] },
  { word: 'быть', difficulty: 1, tags: ['verb', 'infinitive', 'basic'] },
  { word: 'есть', difficulty: 1, tags: ['verb', 'to-have', 'basic'] },
  { word: 'не', difficulty: 1, tags: ['particle', 'negation', 'basic'] },
  { word: 'что', difficulty: 1, tags: ['conjunction', 'basic'] },
  { word: 'как', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'где', difficulty: 1, tags: ['adverb', 'interrogative', 'basic'] },
  { word: 'кто', difficulty: 1, tags: ['pronoun', 'interrogative', 'basic'] },
  { word: 'да', difficulty: 1, tags: ['particle', 'affirmation', 'basic'] },
  { word: 'нет', difficulty: 1, tags: ['particle', 'negation', 'basic'] },
  { word: 'свой', difficulty: 1, tags: ['possessive', 'reflexive', 'basic'] },
  { word: 'мой', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'твой', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'его', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'её', difficulty: 1, tags: ['possessive', 'basic'] },
  { word: 'наш', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'ваш', difficulty: 1, tags: ['possessive', 'formal', 'basic'] },
  { word: 'их', difficulty: 1, tags: ['possessive', 'plural', 'basic'] },
  { word: 'один', difficulty: 1, tags: ['number', 'basic'] },
  { word: 'два', difficulty: 1, tags: ['number', 'basic'] },
  { word: 'три', difficulty: 1, tags: ['number', 'basic'] },
  { word: 'четыре', difficulty: 1, tags: ['number', 'basic'] },
  { word: 'пять', difficulty: 1, tags: ['number', 'basic'] },
  { word: 'десять', difficulty: 1, tags: ['number', 'basic'] },
  { word: 'год', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'день', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'ночь', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'утро', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'вечер', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'дом', difficulty: 1, tags: ['noun', 'place', 'basic'] },
  { word: 'вода', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'еда', difficulty: 1, tags: ['noun', 'food', 'basic'] },
  { word: 'хлеб', difficulty: 1, tags: ['noun', 'food', 'basic'] },
  { word: 'мясо', difficulty: 1, tags: ['noun', 'food', 'basic'] },
  { word: 'чай', difficulty: 1, tags: ['noun', 'drink', 'basic'] },
  { word: 'кофе', difficulty: 1, tags: ['noun', 'drink', 'basic'] },
  { word: 'друг', difficulty: 1, tags: ['noun', 'person', 'basic'] },
  { word: 'человек', difficulty: 1, tags: ['noun', 'person', 'basic'] },
  { word: 'мужчина', difficulty: 1, tags: ['noun', 'person', 'basic'] },
  { word: 'женщина', difficulty: 1, tags: ['noun', 'person', 'basic'] },
  { word: 'ребенок', difficulty: 1, tags: ['noun', 'person', 'basic'] },
  { word: 'работа', difficulty: 1, tags: ['noun', 'work', 'basic'] },
  { word: 'время', difficulty: 1, tags: ['noun', 'time', 'basic'] },
  { word: 'дело', difficulty: 1, tags: ['noun', 'basic'] },
  { word: 'жизнь', difficulty: 1, tags: ['noun', 'abstract', 'basic'] },
  { word: 'рука', difficulty: 1, tags: ['noun', 'body', 'basic'] },
  { word: 'голова', difficulty: 1, tags: ['noun', 'body', 'basic'] },
  { word: 'глаз', difficulty: 1, tags: ['noun', 'body', 'basic'] },
  { word: 'сердце', difficulty: 1, tags: ['noun', 'body', 'basic'] },
  { word: 'нога', difficulty: 1, tags: ['noun', 'body', 'basic'] },
  { word: 'слово', difficulty: 1, tags: ['noun', 'communication', 'basic'] },
  { word: 'язык', difficulty: 1, tags: ['noun', 'body', 'basic'] },
  { word: 'мир', difficulty: 1, tags: ['noun', 'abstract', 'basic'] },
  { word: 'страна', difficulty: 1, tags: ['noun', 'place', 'basic'] },
  { word: 'город', difficulty: 1, tags: ['noun', 'place', 'basic'] },

  // === Difficulty 2: Intermediate (More complex words) ===
  { word: 'книга', difficulty: 2, tags: ['noun', 'object', 'intermediate'] },
  { word: 'письмо', difficulty: 2, tags: ['noun', 'communication', 'intermediate'] },
  { word: 'стол', difficulty: 2, tags: ['noun', 'furniture', 'intermediate'] },
  { word: 'стул', difficulty: 2, tags: ['noun', 'furniture', 'intermediate'] },
  { word: 'окно', difficulty: 2, tags: ['noun', 'building', 'intermediate'] },
  { word: 'дверь', difficulty: 2, tags: ['noun', 'building', 'intermediate'] },
  { word: 'комната', difficulty: 2, tags: ['noun', 'place', 'intermediate'] },
  { word: 'школа', difficulty: 2, tags: ['noun', 'place', 'intermediate'] },
  { word: 'магазин', difficulty: 2, tags: ['noun', 'place', 'intermediate'] },
  { word: 'улица', difficulty: 2, tags: ['noun', 'place', 'intermediate'] },
  { word: 'дорога', difficulty: 2, tags: ['noun', 'place', 'intermediate'] },
  { word: 'машина', difficulty: 2, tags: ['noun', 'vehicle', 'intermediate'] },
  { word: 'поезд', difficulty: 2, tags: ['noun', 'vehicle', 'intermediate'] },
  { word: 'самолёт', difficulty: 2, tags: ['noun', 'vehicle', 'intermediate'] },
  { word: 'автобус', difficulty: 2, tags: ['noun', 'vehicle', 'intermediate'] },
  { word: 'погода', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'дождь', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'снег', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'солнце', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'луна', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'звезда', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'дерево', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'цветок', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'животное', difficulty: 2, tags: ['noun', 'nature', 'intermediate'] },
  { word: 'собака', difficulty: 2, tags: ['noun', 'animal', 'intermediate'] },
  { word: 'кошка', difficulty: 2, tags: ['noun', 'animal', 'intermediate'] },
  { word: 'птица', difficulty: 2, tags: ['noun', 'animal', 'intermediate'] },
  { word: 'рыба', difficulty: 2, tags: ['noun', 'animal', 'intermediate'] },
  { word: 'идти', difficulty: 2, tags: ['verb', 'motion', 'intermediate'] },
  { word: 'ехать', difficulty: 2, tags: ['verb', 'motion', 'intermediate'] },
  { word: 'бежать', difficulty: 2, tags: ['verb', 'motion', 'intermediate'] },
  { word: 'лететь', difficulty: 2, tags: ['verb', 'motion', 'intermediate'] },
  { word: 'плыть', difficulty: 2, tags: ['verb', 'motion', 'intermediate'] },
  { word: 'ходить', difficulty: 2, tags: ['verb', 'motion', 'intermediate'] },
  { word: 'ходить', difficulty: 2, tags: ['verb', 'habitual', 'intermediate'] },
  { word: 'стоять', difficulty: 2, tags: ['verb', 'position', 'intermediate'] },
  { word: 'сидеть', difficulty: 2, tags: ['verb', 'position', 'intermediate'] },
  { word: 'лежать', difficulty: 2, tags: ['verb', 'position', 'intermediate'] },
  { word: 'спать', difficulty: 2, tags: ['verb', 'state', 'intermediate'] },
  { word: 'видеть', difficulty: 2, tags: ['verb', 'perception', 'intermediate'] },
  { word: 'слышать', difficulty: 2, tags: ['verb', 'perception', 'intermediate'] },
  { word: 'чувствовать', difficulty: 2, tags: ['verb', 'perception', 'intermediate'] },
  { word: 'знать', difficulty: 2, tags: ['verb', 'cognition', 'intermediate'] },
  { word: 'понимать', difficulty: 2, tags: ['verb', 'cognition', 'intermediate'] },
  { word: 'думать', difficulty: 2, tags: ['verb', 'cognition', 'intermediate'] },
  { word: 'хотеть', difficulty: 2, tags: ['verb', 'desire', 'intermediate'] },
  { word: 'мочь', difficulty: 2, tags: ['verb', 'ability', 'intermediate'] },
  { word: 'должен', difficulty: 2, tags: ['verb', 'obligation', 'intermediate'] },
  { word: 'нужно', difficulty: 2, tags: ['verb', 'necessity', 'intermediate'] },
  { word: 'любить', difficulty: 2, tags: ['verb', 'emotion', 'intermediate'] },
  { word: 'жить', difficulty: 2, tags: ['verb', 'state', 'intermediate'] },
  { word: 'работать', difficulty: 2, tags: ['verb', 'work', 'intermediate'] },
  { word: 'учить', difficulty: 2, tags: ['verb', 'learning', 'intermediate'] },
  { word: 'учиться', difficulty: 2, tags: ['verb', 'learning', 'intermediate'] },
  { word: 'писать', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'читать', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'говорить', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'сказать', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'спросить', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'ответить', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'рассказать', difficulty: 2, tags: ['verb', 'communication', 'intermediate'] },
  { word: 'большой', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'маленький', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'новый', difficulty: 2, tags: ['adjective', 'time', 'intermediate'] },
  { word: 'старый', difficulty: 2, tags: ['adjective', 'time', 'intermediate'] },
  { word: 'хороший', difficulty: 2, tags: ['adjective', 'quality', 'intermediate'] },
  { word: 'плохой', difficulty: 2, tags: ['adjective', 'quality', 'intermediate'] },
  { word: 'длинный', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'короткий', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'высокий', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'низкий', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'широкий', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'узкий', difficulty: 2, tags: ['adjective', 'size', 'intermediate'] },
  { word: 'тяжёлый', difficulty: 2, tags: ['adjective', 'weight', 'intermediate'] },
  { word: 'лёгкий', difficulty: 2, tags: ['adjective', 'weight', 'intermediate'] },
  { word: 'тёплый', difficulty: 2, tags: ['adjective', 'temperature', 'intermediate'] },
  { word: 'холодный', difficulty: 2, tags: ['adjective', 'temperature', 'intermediate'] },
  { word: 'красивый', difficulty: 2, tags: ['adjective', 'quality', 'intermediate'] },
  { word: 'умный', difficulty: 2, tags: ['adjective', 'quality', 'intermediate'] },
  { word: 'богатый', difficulty: 2, tags: ['adjective', 'status', 'intermediate'] },
  { word: 'бедный', difficulty: 2, tags: ['adjective', 'status', 'intermediate'] },
  { word: 'сегодня', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'завтра', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'вчера', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'сейчас', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'потом', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'раньше', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'позже', difficulty: 2, tags: ['adverb', 'time', 'intermediate'] },
  { word: 'здесь', difficulty: 2, tags: ['adverb', 'place', 'intermediate'] },
  { word: 'там', difficulty: 2, tags: ['adverb', 'place', 'intermediate'] },
  { word: 'тут', difficulty: 2, tags: ['adverb', 'place', 'intermediate'] },
  { word: 'туда', difficulty: 2, tags: ['adverb', 'direction', 'intermediate'] },
  { word: 'сюда', difficulty: 2, tags: ['adverb', 'direction', 'intermediate'] },
  { word: 'быстро', difficulty: 2, tags: ['adverb', 'speed', 'intermediate'] },
  { word: 'медленно', difficulty: 2, tags: ['adverb', 'speed', 'intermediate'] },
  { word: 'много', difficulty: 2, tags: ['adverb', 'quantity', 'intermediate'] },
  { word: 'мало', difficulty: 2, tags: ['adverb', 'quantity', 'intermediate'] },

  // === Difficulty 3: Advanced (Complex words with ё, harder characters) ===
  { word: 'объяснять', difficulty: 3, tags: ['verb', 'communication', 'advanced', 'hard'] },
  { word: 'создавать', difficulty: 3, tags: ['verb', 'creation', 'advanced', 'hard'] },
  { word: 'развивать', difficulty: 3, tags: ['verb', 'progress', 'advanced', 'hard'] },
  { word: 'происходить', difficulty: 3, tags: ['verb', 'event', 'advanced', 'hard'] },
  { word: 'существовать', difficulty: 3, tags: ['verb', 'state', 'advanced', 'hard'] },
  { word: 'появляться', difficulty: 3, tags: ['verb', 'event', 'advanced', 'hard'] },
  { word: 'исчезать', difficulty: 3, tags: ['verb', 'event', 'advanced', 'hard'] },
  { word: 'двигаться', difficulty: 3, tags: ['verb', 'motion', 'advanced', 'hard'] },
  { word: 'останавливаться', difficulty: 3, tags: ['verb', 'motion', 'advanced', 'hard'] },
  { word: 'начинать', difficulty: 3, tags: ['verb', 'time', 'advanced', 'hard'] },
  { word: 'заканчивать', difficulty: 3, tags: ['verb', 'time', 'advanced', 'hard'] },
  { word: 'продолжать', difficulty: 3, tags: ['verb', 'time', 'advanced', 'hard'] },
  { word: 'решать', difficulty: 3, tags: ['verb', 'cognition', 'advanced', 'hard'] },
  { word: 'пробовать', difficulty: 3, tags: ['verb', 'attempt', 'advanced', 'hard'] },
  { word: 'изменять', difficulty: 3, tags: ['verb', 'change', 'advanced', 'hard'] },
  { word: 'получать', difficulty: 3, tags: ['verb', 'action', 'advanced', 'hard'] },
  { word: 'отправлять', difficulty: 3, tags: ['verb', 'communication', 'advanced', 'hard'] },
  { word: 'получаться', difficulty: 3, tags: ['verb', 'result', 'advanced', 'hard'] },
  { word: 'оказываться', difficulty: 3, tags: ['verb', 'discovery', 'advanced', 'hard'] },
  { word: 'встречать', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'знакомить', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'помогать', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'мечтать', difficulty: 3, tags: ['verb', 'emotion', 'advanced', 'hard'] },
  { word: 'надеяться', difficulty: 3, tags: ['verb', 'emotion', 'advanced', 'hard'] },
  { word: 'беспокоиться', difficulty: 3, tags: ['verb', 'emotion', 'advanced', 'hard'] },
  { word: 'удивляться', difficulty: 3, tags: ['verb', 'emotion', 'advanced', 'hard'] },
  { word: 'гордиться', difficulty: 3, tags: ['verb', 'emotion', 'advanced', 'hard'] },
  { word: 'бояться', difficulty: 3, tags: ['verb', 'emotion', 'advanced', 'hard'] },
  { word: 'интересоваться', difficulty: 3, tags: ['verb', 'cognition', 'advanced', 'hard'] },
  { word: 'запоминать', difficulty: 3, tags: ['verb', 'memory', 'advanced', 'hard'] },
  { word: 'забывать', difficulty: 3, tags: ['verb', 'memory', 'advanced', 'hard'] },
  { word: 'представлять', difficulty: 3, tags: ['verb', 'cognition', 'advanced', 'hard'] },
  { word: 'сравнивать', difficulty: 3, tags: ['verb', 'cognition', 'advanced', 'hard'] },
  { word: 'анализировать', difficulty: 3, tags: ['verb', 'cognition', 'advanced', 'hard'] },
  { word: 'проверять', difficulty: 3, tags: ['verb', 'action', 'advanced', 'hard'] },
  { word: 'использовать', difficulty: 3, tags: ['verb', 'action', 'advanced', 'hard'] },
  { word: 'создавать', difficulty: 3, tags: ['verb', 'creation', 'advanced', 'hard'] },
  { word: 'строить', difficulty: 3, tags: ['verb', 'creation', 'advanced', 'hard'] },
  { word: 'рисовать', difficulty: 3, tags: ['verb', 'creation', 'advanced', 'hard'] },
  { word: 'писать', difficulty: 3, tags: ['verb', 'creation', 'advanced', 'hard'] },
  { word: 'печатать', difficulty: 3, tags: ['verb', 'action', 'advanced', 'hard'] },
  { word: 'переводить', difficulty: 3, tags: ['verb', 'communication', 'advanced', 'hard'] },
  { word: 'информировать', difficulty: 3, tags: ['verb', 'communication', 'advanced', 'hard'] },
  { word: 'выражать', difficulty: 3, tags: ['verb', 'communication', 'advanced', 'hard'] },
  { word: 'обсуждать', difficulty: 3, tags: ['verb', 'communication', 'advanced', 'hard'] },
  { word: 'договариваться', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'соглашаться', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'отказываться', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'приглашать', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'поздравлять', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'благодарить', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'извиняться', difficulty: 3, tags: ['verb', 'social', 'advanced', 'hard'] },
  { word: 'совершенный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'невозможный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'необходимый', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'возможный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'различный', difficulty: 3, tags: ['adjective', 'variety', 'advanced', 'hard'] },
  { word: 'определённый', difficulty: 3, tags: ['adjective', 'certainty', 'advanced', 'hard'] },
  { word: 'специальный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'отдельный', difficulty: 3, tags: ['adjective', 'separateness', 'advanced', 'hard'] },
  { word: 'собственный', difficulty: 3, tags: ['adjective', 'possession', 'advanced', 'hard'] },
  { word: 'государственный', difficulty: 3, tags: ['adjective', 'politics', 'advanced', 'hard'] },
  { word: 'международный', difficulty: 3, tags: ['adjective', 'politics', 'advanced', 'hard'] },
  { word: 'экономический', difficulty: 3, tags: ['adjective', 'economy', 'advanced', 'hard'] },
  { word: 'политический', difficulty: 3, tags: ['adjective', 'politics', 'advanced', 'hard'] },
  { word: 'культурный', difficulty: 3, tags: ['adjective', 'culture', 'advanced', 'hard'] },
  { word: 'исторический', difficulty: 3, tags: ['adjective', 'history', 'advanced', 'hard'] },
  { word: 'научный', difficulty: 3, tags: ['adjective', 'science', 'advanced', 'hard'] },
  { word: 'технический', difficulty: 3, tags: ['adjective', 'technology', 'advanced', 'hard'] },
  { word: 'современный', difficulty: 3, tags: ['adjective', 'time', 'advanced', 'hard'] },
  { word: 'традиционный', difficulty: 3, tags: ['adjective', 'culture', 'advanced', 'hard'] },
  { word: 'независимый', difficulty: 3, tags: ['adjective', 'status', 'advanced', 'hard'] },
  { word: 'ответственный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'активный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'пассивный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'организованный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'дисциплинированный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'искренний', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'честный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'внимательный', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'терпеливый', difficulty: 3, tags: ['adjective', 'quality', 'advanced', 'hard'] },
  { word: 'успешный', difficulty: 3, tags: ['adjective', 'result', 'advanced', 'hard'] },
  { word: 'безопасный', difficulty: 3, tags: ['adjective', 'safety', 'advanced', 'hard'] },
  { word: '-dangerous', difficulty: 3, tags: ['adjective', 'safety', 'advanced', 'hard'] },
];
