/**
 * Swahili wordlist with 200+ common words organised by difficulty
 * Swahili uses the Latin alphabet with no diacritics, making it well-suited
 * for typing practice. Rich in noun-class prefixes and agglutinative structure,
 * providing excellent coverage of consonant clusters and vowel sequences.
 */

export interface WordlistEntry {
  word: string;
  difficulty: 1 | 2 | 3;
  tags: string[];
}

/**
 * Swahili wordlist — 200+ common words
 * Difficulty 1: Short, high-frequency words, simple CV patterns
 * Difficulty 2: Common nouns/verbs, medium length, common noun-class prefixes
 * Difficulty 3: Longer words, agglutinative forms, less-common vocabulary
 */
export const swahiliWordlist: WordlistEntry[] = [
  // === Difficulty 1: Beginner ===
  { word: 'na', difficulty: 1, tags: ['conjunction', 'high-frequency'] },
  { word: 'ya', difficulty: 1, tags: ['preposition', 'high-frequency'] },
  { word: 'wa', difficulty: 1, tags: ['preposition', 'high-frequency'] },
  { word: 'la', difficulty: 1, tags: ['article', 'high-frequency'] },
  { word: 'si', difficulty: 1, tags: ['negation', 'high-frequency'] },
  { word: 'ni', difficulty: 1, tags: ['verb', 'high-frequency'] },
  { word: 'au', difficulty: 1, tags: ['conjunction', 'high-frequency'] },
  { word: 'kwa', difficulty: 1, tags: ['preposition', 'high-frequency'] },
  { word: 'hii', difficulty: 1, tags: ['demonstrative', 'high-frequency'] },
  { word: 'huo', difficulty: 1, tags: ['demonstrative', 'high-frequency'] },
  { word: 'mtu', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'mji', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'mke', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'mme', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'watu', difficulty: 1, tags: ['noun', 'plural', 'high-frequency'] },
  { word: 'nchi', difficulty: 1, tags: ['noun', 'high-frequency'] },
  { word: 'baba', difficulty: 1, tags: ['noun', 'family'] },
  { word: 'mama', difficulty: 1, tags: ['noun', 'family'] },
  { word: 'dada', difficulty: 1, tags: ['noun', 'family'] },
  { word: 'kaka', difficulty: 1, tags: ['noun', 'family'] },
  { word: 'ndio', difficulty: 1, tags: ['affirmation', 'high-frequency'] },
  { word: 'hapana', difficulty: 1, tags: ['negation', 'high-frequency'] },
  { word: 'sawa', difficulty: 1, tags: ['adjective', 'high-frequency'] },
  { word: 'tena', difficulty: 1, tags: ['adverb', 'high-frequency'] },
  { word: 'sasa', difficulty: 1, tags: ['adverb', 'time'] },
  { word: 'leo', difficulty: 1, tags: ['adverb', 'time'] },
  { word: 'jana', difficulty: 1, tags: ['adverb', 'time'] },
  { word: 'kesho', difficulty: 1, tags: ['adverb', 'time'] },
  { word: 'mara', difficulty: 1, tags: ['adverb', 'time'] },
  { word: 'nini', difficulty: 1, tags: ['pronoun', 'question'] },
  { word: 'nani', difficulty: 1, tags: ['pronoun', 'question'] },
  { word: 'wapi', difficulty: 1, tags: ['adverb', 'question'] },
  { word: 'lini', difficulty: 1, tags: ['adverb', 'question'] },
  { word: 'mimi', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'wewe', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'yeye', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'sisi', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'nyie', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'wao', difficulty: 1, tags: ['pronoun', 'high-frequency'] },
  { word: 'paka', difficulty: 1, tags: ['noun', 'animal'] },
  { word: 'mbwa', difficulty: 1, tags: ['noun', 'animal'] },
  { word: 'ndege', difficulty: 1, tags: ['noun', 'animal'] },
  { word: 'samaki', difficulty: 1, tags: ['noun', 'animal'] },
  { word: 'nyumba', difficulty: 1, tags: ['noun', 'place'] },
  { word: 'shule', difficulty: 1, tags: ['noun', 'place'] },
  { word: 'duka', difficulty: 1, tags: ['noun', 'place'] },
  { word: 'bahari', difficulty: 1, tags: ['noun', 'place'] },
  { word: 'mto', difficulty: 1, tags: ['noun', 'place'] },
  { word: 'mlima', difficulty: 1, tags: ['noun', 'place'] },
  { word: 'mwaka', difficulty: 1, tags: ['noun', 'time'] },

  // === Difficulty 2: Intermediate ===
  { word: 'kujua', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kusema', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kuona', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kwenda', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kuja', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kufanya', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kutaka', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kuleta', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kupata', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kusoma', difficulty: 2, tags: ['verb', 'education'] },
  { word: 'kuandika', difficulty: 2, tags: ['verb', 'education'] },
  { word: 'kufungua', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kufunga', difficulty: 2, tags: ['verb', 'common'] },
  { word: 'kipindi', difficulty: 2, tags: ['noun', 'time'] },
  { word: 'mkutano', difficulty: 2, tags: ['noun', 'event'] },
  { word: 'habari', difficulty: 2, tags: ['noun', 'common', 'greeting'] },
  { word: 'jambo', difficulty: 2, tags: ['noun', 'greeting'] },
  { word: 'asante', difficulty: 2, tags: ['phrase', 'greeting'] },
  { word: 'karibu', difficulty: 2, tags: ['phrase', 'greeting'] },
  { word: 'samahani', difficulty: 2, tags: ['phrase', 'polite'] },
  { word: 'tafadhali', difficulty: 2, tags: ['phrase', 'polite'] },
  { word: 'rafiki', difficulty: 2, tags: ['noun', 'person'] },
  { word: 'mwalimu', difficulty: 2, tags: ['noun', 'person', 'education'] },
  { word: 'daktari', difficulty: 2, tags: ['noun', 'person', 'profession'] },
  { word: 'askari', difficulty: 2, tags: ['noun', 'person', 'profession'] },
  { word: 'mkulima', difficulty: 2, tags: ['noun', 'person', 'profession'] },
  { word: 'dereva', difficulty: 2, tags: ['noun', 'person', 'profession'] },
  { word: 'chakula', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'maji', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'mkate', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'matunda', difficulty: 2, tags: ['noun', 'food', 'plural'] },
  { word: 'mboga', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'nyama', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'kahawa', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'chai', difficulty: 2, tags: ['noun', 'food'] },
  { word: 'nguo', difficulty: 2, tags: ['noun', 'clothing'] },
  { word: 'viatu', difficulty: 2, tags: ['noun', 'clothing', 'plural'] },
  { word: 'kofia', difficulty: 2, tags: ['noun', 'clothing'] },
  { word: 'kitabu', difficulty: 2, tags: ['noun', 'education'] },
  { word: 'karatasi', difficulty: 2, tags: ['noun', 'education'] },
  { word: 'kalamu', difficulty: 2, tags: ['noun', 'education'] },
  { word: 'simu', difficulty: 2, tags: ['noun', 'technology'] },
  { word: 'kompyuta', difficulty: 2, tags: ['noun', 'technology'] },
  { word: 'gari', difficulty: 2, tags: ['noun', 'transport'] },
  { word: 'basi', difficulty: 2, tags: ['noun', 'transport'] },
  { word: 'ndege', difficulty: 2, tags: ['noun', 'transport'] },
  { word: 'meli', difficulty: 2, tags: ['noun', 'transport'] },
  { word: 'barabara', difficulty: 2, tags: ['noun', 'place'] },
  { word: 'hospitali', difficulty: 2, tags: ['noun', 'place'] },
  { word: 'kanisa', difficulty: 2, tags: ['noun', 'place'] },
  { word: 'msikiti', difficulty: 2, tags: ['noun', 'place'] },
  { word: 'soko', difficulty: 2, tags: ['noun', 'place'] },
  { word: 'benki', difficulty: 2, tags: ['noun', 'institution'] },
  { word: 'serikali', difficulty: 2, tags: ['noun', 'institution'] },
  { word: 'mahali', difficulty: 2, tags: ['noun', 'location'] },
  { word: 'mbali', difficulty: 2, tags: ['adverb', 'distance'] },
  { word: 'karibu', difficulty: 2, tags: ['adverb', 'distance'] },
  { word: 'pamoja', difficulty: 2, tags: ['adverb', 'manner'] },
  { word: 'haraka', difficulty: 2, tags: ['adverb', 'manner'] },
  { word: 'polepole', difficulty: 2, tags: ['adverb', 'manner'] },
  { word: 'vizuri', difficulty: 2, tags: ['adverb', 'manner'] },
  { word: 'vibaya', difficulty: 2, tags: ['adverb', 'manner'] },
  { word: 'kubwa', difficulty: 2, tags: ['adjective', 'size'] },
  { word: 'ndogo', difficulty: 2, tags: ['adjective', 'size'] },
  { word: 'nzuri', difficulty: 2, tags: ['adjective', 'quality'] },
  { word: 'mbaya', difficulty: 2, tags: ['adjective', 'quality'] },
  { word: 'mpya', difficulty: 2, tags: ['adjective', 'state'] },
  { word: 'zamani', difficulty: 2, tags: ['adjective', 'time'] },
  { word: 'mzee', difficulty: 2, tags: ['noun', 'adjective', 'age'] },
  { word: 'kijana', difficulty: 2, tags: ['noun', 'age'] },
  { word: 'mtoto', difficulty: 2, tags: ['noun', 'family'] },
  { word: 'watoto', difficulty: 2, tags: ['noun', 'family', 'plural'] },
  { word: 'familia', difficulty: 2, tags: ['noun', 'family'] },
  { word: 'maisha', difficulty: 2, tags: ['noun', 'abstract'] },
  { word: 'moyo', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'mkono', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'mguu', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'kichwa', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'jicho', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'mdomo', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'sikio', difficulty: 2, tags: ['noun', 'body'] },
  { word: 'pesa', difficulty: 2, tags: ['noun', 'commerce'] },
  { word: 'biashara', difficulty: 2, tags: ['noun', 'commerce'] },
  { word: 'bei', difficulty: 2, tags: ['noun', 'commerce'] },
  { word: 'hewa', difficulty: 2, tags: ['noun', 'nature'] },
  { word: 'jua', difficulty: 2, tags: ['noun', 'nature'] },
  { word: 'mvua', difficulty: 2, tags: ['noun', 'nature'] },
  { word: 'upepo', difficulty: 2, tags: ['noun', 'nature'] },
  { word: 'ardhi', difficulty: 2, tags: ['noun', 'nature'] },
  { word: 'mwanga', difficulty: 2, tags: ['noun', 'nature'] },

  // === Difficulty 3: Advanced ===
  { word: 'ushirikiano', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'maendeleo', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'utamaduni', difficulty: 3, tags: ['noun', 'culture', 'advanced'] },
  { word: 'uchumi', difficulty: 3, tags: ['noun', 'economics', 'advanced'] },
  { word: 'elimu', difficulty: 3, tags: ['noun', 'education', 'advanced'] },
  { word: 'afya', difficulty: 3, tags: ['noun', 'health', 'advanced'] },
  { word: 'uhuru', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'amani', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'haki', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'nguvu', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'akili', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'maarifa', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'utafiti', difficulty: 3, tags: ['noun', 'education', 'advanced'] },
  { word: 'teknolojia', difficulty: 3, tags: ['noun', 'technology', 'advanced'] },
  { word: 'mazingira', difficulty: 3, tags: ['noun', 'environment', 'advanced'] },
  { word: 'kiswahili', difficulty: 3, tags: ['noun', 'language', 'advanced'] },
  { word: 'lugha', difficulty: 3, tags: ['noun', 'language', 'advanced'] },
  { word: 'tafsiri', difficulty: 3, tags: ['noun', 'language', 'advanced'] },
  { word: 'mawasiliano', difficulty: 3, tags: ['noun', 'communication', 'advanced'] },
  { word: 'habari', difficulty: 3, tags: ['noun', 'media', 'advanced'] },
  { word: 'shirika', difficulty: 3, tags: ['noun', 'institution', 'advanced'] },
  { word: 'chama', difficulty: 3, tags: ['noun', 'politics', 'advanced'] },
  { word: 'uchaguzi', difficulty: 3, tags: ['noun', 'politics', 'advanced'] },
  { word: 'rais', difficulty: 3, tags: ['noun', 'politics', 'advanced'] },
  { word: 'waziri', difficulty: 3, tags: ['noun', 'politics', 'advanced'] },
  { word: 'bunge', difficulty: 3, tags: ['noun', 'politics', 'advanced'] },
  { word: 'mahakama', difficulty: 3, tags: ['noun', 'law', 'advanced'] },
  { word: 'sheria', difficulty: 3, tags: ['noun', 'law', 'advanced'] },
  { word: 'mkataba', difficulty: 3, tags: ['noun', 'law', 'advanced'] },
  { word: 'hukumu', difficulty: 3, tags: ['noun', 'law', 'advanced'] },
  { word: 'kujaribu', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kuendelea', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kubadilika', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kujibu', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kushinda', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kusaidia', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kuelewa', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kujifunza', difficulty: 3, tags: ['verb', 'education', 'advanced'] },
  { word: 'kufundisha', difficulty: 3, tags: ['verb', 'education', 'advanced'] },
  { word: 'kuchangia', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kuzalisha', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kuwasiliana', difficulty: 3, tags: ['verb', 'communication', 'advanced'] },
  { word: 'kushirikiana', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'kipengele', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'mwelekeo', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'tatizo', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'suluhisho', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'changamoto', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'fursa', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'mafanikio', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'kushangaza', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'ajabu', difficulty: 3, tags: ['noun', 'adjective', 'advanced'] },
  { word: 'kubuniwa', difficulty: 3, tags: ['verb', 'advanced'] },
  { word: 'ubunifu', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'mfumo', difficulty: 3, tags: ['noun', 'system', 'advanced'] },
  { word: 'mpango', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'mkakati', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'lengo', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'manufaa', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'thamani', difficulty: 3, tags: ['noun', 'abstract', 'advanced'] },
  { word: 'imara', difficulty: 3, tags: ['adjective', 'advanced'] },
  { word: 'stadi', difficulty: 3, tags: ['noun', 'skill', 'advanced'] },
];
