import type { UiLocale } from '$lib/stores/locale';

export interface DemoScene {
  code: UiLocale;
  script: string;
  languageName: string;
  layout: string;
  rtl: boolean;
  text: string;
  wpm: number;
  accuracy: number;
  accentClass: string;
}

/**
 * One demo per selectable UI locale. The locale switcher is the source of truth,
 * so adding a UI locale requires a matching, native-language demo here.
 */
export const MARKETING_DEMO_SCENES: Record<UiLocale, DemoScene> = {
  en: {
    code: 'en',
    script: 'Latin',
    languageName: 'English',
    layout: 'QWERTY',
    rtl: false,
    text: 'Consistent practice builds speed, accuracy, and confidence on every line you type.',
    wpm: 92,
    accuracy: 98.7,
    accentClass: 'text-primary',
  },
  es: {
    code: 'es',
    script: 'Latin',
    languageName: 'Español',
    layout: 'QWERTY',
    rtl: false,
    text: 'Practicar mecanografía cada día mejora la velocidad, la precisión y la confianza al escribir.',
    wpm: 90,
    accuracy: 98.2,
    accentClass: 'text-primary',
  },
  fr: {
    code: 'fr',
    script: 'Latin',
    languageName: 'Français',
    layout: 'AZERTY',
    rtl: false,
    text: "L'apprentissage de la dactylographie sur un clavier AZERTY nécessite une précision mécanique absolue.",
    wpm: 94,
    accuracy: 98.4,
    accentClass: 'text-primary',
  },
  de: {
    code: 'de',
    script: 'Latin',
    languageName: 'Deutsch',
    layout: 'QWERTZ',
    rtl: false,
    text: 'Regelmäßiges Üben verbessert die Geschwindigkeit, Genauigkeit und Sicherheit beim Tippen.',
    wpm: 88,
    accuracy: 98.1,
    accentClass: 'text-primary',
  },
  pt: {
    code: 'pt',
    script: 'Latin',
    languageName: 'Português',
    layout: 'ABNT2',
    rtl: false,
    text: 'A prática diária de digitação melhora a velocidade, a precisão e a confiança ao escrever.',
    wpm: 89,
    accuracy: 98.3,
    accentClass: 'text-primary',
  },
  ja: {
    code: 'ja',
    script: 'Japanese',
    languageName: '日本語',
    layout: 'Romaji',
    rtl: false,
    text: '日本語のタイピングはローマ字入力とかな入力を選ぶことができます。練習を重ねると速度が上がります。',
    wpm: 55,
    accuracy: 99.1,
    accentClass: 'text-primary',
  },
  ko: {
    code: 'ko',
    script: 'Korean',
    languageName: '한국어',
    layout: 'Dubeolsik',
    rtl: false,
    text: '한글 타자 연습은 정확도와 속도를 동시에 향상시키는 과정입니다. 꾸준한 연습이 핵심입니다.',
    wpm: 70,
    accuracy: 95.8,
    accentClass: 'text-secondary',
  },
  zh: {
    code: 'zh',
    script: 'CJK',
    languageName: '简体中文',
    layout: 'Pinyin',
    rtl: false,
    text: '每天练习打字可以提高速度、准确率和使用键盘时的信心。',
    wpm: 58,
    accuracy: 98.9,
    accentClass: 'text-primary',
  },
  ar: {
    code: 'ar',
    script: 'Arabic',
    languageName: 'العربية',
    layout: 'Arabic',
    rtl: true,
    text: 'تعلم الكتابة على لوحة المفاتيح العربية يحتاج إلى التدريب المستمر والدقة في تحديد الأحرف.',
    wpm: 61,
    accuracy: 97.2,
    accentClass: 'text-tertiary',
  },
  hi: {
    code: 'hi',
    script: 'Devanagari',
    languageName: 'हिन्दी',
    layout: 'Devanagari',
    rtl: false,
    text: 'नियमित टाइपिंग अभ्यास से गति, सटीकता और आत्मविश्वास में सुधार होता है।',
    wpm: 52,
    accuracy: 97.6,
    accentClass: 'text-tertiary',
  },
  tr: {
    code: 'tr',
    script: 'Latin',
    languageName: 'Türkçe',
    layout: 'Turkish Q',
    rtl: false,
    text: 'Düzenli klavye çalışması yazma hızını, doğruluğu ve güveni artırır.',
    wpm: 84,
    accuracy: 98.0,
    accentClass: 'text-primary',
  },
  it: {
    code: 'it',
    script: 'Latin',
    languageName: 'Italiano',
    layout: 'QWERTY',
    rtl: false,
    text: 'Allenarsi ogni giorno migliora la velocità, la precisione e la sicurezza nella digitazione.',
    wpm: 87,
    accuracy: 98.5,
    accentClass: 'text-primary',
  },
  ru: {
    code: 'ru',
    script: 'Cyrillic',
    languageName: 'Русский',
    layout: 'ЙЦУКЕН',
    rtl: false,
    text: 'Учитель быстро печатает на клавиатуре без единой ошибки и удивляет всех своей скоростью.',
    wpm: 78,
    accuracy: 96.1,
    accentClass: 'text-secondary',
  },
  id: {
    code: 'id',
    script: 'Latin',
    languageName: 'Bahasa Indonesia',
    layout: 'QWERTY',
    rtl: false,
    text: 'Latihan mengetik yang rutin meningkatkan kecepatan, ketepatan, dan kepercayaan diri.',
    wpm: 82,
    accuracy: 98.2,
    accentClass: 'text-primary',
  },
  vi: {
    code: 'vi',
    script: 'Latin',
    languageName: 'Tiếng Việt',
    layout: 'Telex / VNI',
    rtl: false,
    text: 'Luyện gõ thường xuyên giúp cải thiện tốc độ, độ chính xác và sự tự tin khi sử dụng bàn phím.',
    wpm: 78,
    accuracy: 98.0,
    accentClass: 'text-primary',
  },
  pl: {
    code: 'pl',
    script: 'Latin',
    languageName: 'Polski',
    layout: 'Polish QWERTY',
    rtl: false,
    text: 'Regularne ćwiczenie pisania zwiększa szybkość, dokładność i pewność podczas korzystania z klawiatury.',
    wpm: 86,
    accuracy: 98.3,
    accentClass: 'text-primary',
  },
};
