/**
 * Arabic RTL Lessons — aligned with lesson-registry Lesson interface
 */

import type { Lesson, LessonChar, Finger } from './lesson-registry.js';

function lc(
  ch: string,
  code: string,
  finger: Finger
): LessonChar {
  return { char: ch, code, expectedFinger: finger };
}

export const arabicLessons: Lesson[] = [
  {
    id: 'ar-alphabet',
    title: 'الحروف العربية (Arabic Alphabet)',
    language: 'ar',
    script: 'arabic',
    difficulty: 1,
    tags: { hand: 'both', finger: 'all', key_bigram: 'alphabet', speed: 'accuracy' },
    content: [
      lc('ض', 'Arabic-letter-dad', 'left_index'),
      lc('ص', 'Arabic-letter-sad', 'left_middle'),
      lc('ث', 'Arabic-letter-tha', 'left_index'),
      lc('ق', 'Arabic-letter-qaf', 'right_index'),
      lc('ف', 'Arabic-letter-fa', 'right_index'),
      lc('غ', 'Arabic-letter-ghayn', 'right_middle'),
      lc('ع', 'Arabic-letter-ayn', 'right_middle'),
      lc('ه', 'Arabic-letter-ha', 'right_index'),
      lc('خ', 'Arabic-letter-kha', 'right_middle'),
      lc('ح', 'Arabic-letter-haa', 'right_index'),
      lc('ج', 'Arabic-letter-jeem', 'right_middle'),
      lc('ش', 'Arabic-letter-she', 'left_index'),
      lc('س', 'Arabic-letter-sin', 'left_index'),
      lc('ي', 'Arabic-letter-ya', 'right_index'),
      lc('ب', 'Arabic-letter-ba', 'left_index'),
      lc('ل', 'Arabic-letter-lam', 'left_middle'),
      lc('ا', 'Arabic-letter-alef', 'left_middle'),
      lc('ت', 'Arabic-letter-ta', 'left_index'),
      lc('ن', 'Arabic-letter-nun', 'left_middle'),
      lc('م', 'Arabic-letter-mim', 'right_index'),
      lc('ك', 'Arabic-letter-kaf', 'right_middle'),
      lc('ئ', 'Arabic-letter-hamza-ya', 'right_index'),
      lc('ء', 'Arabic-letter-hamza', 'left_index'),
      lc('ؤ', 'Arabic-letter-hamza-waw', 'right_middle'),
      lc('ر', 'Arabic-letter-ra', 'right_index'),
      lc('لا', 'Arabic-letter-lam-alef', 'left_middle'),
      lc('ى', 'Arabic-letter-alef-maksura', 'right_index'),
      lc('ة', 'Arabic-letter-ta-marbuta', 'left_index'),
      lc('و', 'Arabic-letter-waw', 'right_middle'),
      lc('ز', 'Arabic-letter-zay', 'left_index'),
      lc('ظ', 'Arabic-letter-dad', 'right_middle'),
    ],
  },
  {
    id: 'ar-harakat',
    title: 'حركات (Short Vowels)',
    language: 'ar',
    script: 'arabic',
    difficulty: 1,
    tags: { hand: 'both', finger: 'all', key_bigram: 'harakat', speed: 'accuracy' },
    content: [
      lc('َ', 'Arabic-fatha', 'left_index'),
      lc('ِ', 'Arabic-kasra', 'left_middle'),
      lc('ُ', 'Arabic-damma', 'right_index'),
      lc('ً', 'Arabic-fathatan', 'left_index'),
      lc('ٍ', 'Arabic-kasratan', 'left_middle'),
      lc('ٌ', 'Arabic-dammatan', 'right_index'),
      lc('ْ', 'Arabic-sukun', 'right_middle'),
    ],
  },
  {
    id: 'ar-simple-words',
    title: 'كلمات بسيطة (Simple Words)',
    language: 'ar',
    script: 'arabic',
    difficulty: 2,
    tags: { hand: 'both', finger: 'all', key_bigram: 'words', speed: 'accuracy' },
    content: [
      lc('م', 'Arabic-letter-mim', 'right_index'),
      lc('ن', 'Arabic-letter-nun', 'left_middle'),
      lc('ف', 'Arabic-letter-fa', 'right_index'),
      lc('ي', 'Arabic-letter-ya', 'right_index'),
      lc('س', 'Arabic-letter-sin', 'left_index'),
      lc('ر', 'Arabic-letter-ra', 'right_index'),
      lc('ب', 'Arabic-letter-ba', 'left_index'),
      lc('ل', 'Arabic-letter-lam', 'left_middle'),
      lc('ك', 'Arabic-letter-kaf', 'right_middle'),
      lc('ت', 'Arabic-letter-ta', 'left_index'),
    ],
  },
  {
    id: 'ar-weak-letters',
    title: 'الألف اللينة (Weak Letters)',
    language: 'ar',
    script: 'arabic',
    difficulty: 2,
    tags: { hand: 'both', finger: 'all', key_bigram: 'weak-letters', speed: 'accuracy' },
    content: [
      lc('ا', 'Arabic-letter-alef', 'left_middle'),
      lc('و', 'Arabic-letter-waw', 'right_middle'),
      lc('ي', 'Arabic-letter-ya', 'right_index'),
      lc('لا', 'Arabic-letter-lam-alef', 'left_middle'),
      lc('لأ', 'Arabic-letter-lam-hamza', 'left_middle'),
    ],
  },
  {
    id: 'ar-sun-moon',
    title: 'الشمسية والقمرية (Sun & Moon Letters)',
    language: 'ar',
    script: 'arabic',
    difficulty: 2,
    tags: { hand: 'both', finger: 'all', key_bigram: 'sun-moon', speed: 'accuracy' },
    content: [
      lc('ت', 'Arabic-letter-ta', 'left_index'),
      lc('ث', 'Arabic-letter-tha', 'left_index'),
      lc('د', 'Arabic-letter-dal', 'right_index'),
      lc('ذ', 'Arabic-letter-dhal', 'right_index'),
      lc('ر', 'Arabic-letter-ra', 'right_index'),
      lc('ز', 'Arabic-letter-zay', 'left_index'),
      lc('س', 'Arabic-letter-sin', 'left_index'),
      lc('ش', 'Arabic-letter-she', 'left_index'),
      lc('ص', 'Arabic-letter-sad', 'left_middle'),
      lc('ض', 'Arabic-letter-dad', 'left_middle'),
      lc('ا', 'Arabic-letter-alef', 'left_middle'),
      lc('ب', 'Arabic-letter-ba', 'left_index'),
      lc('ج', 'Arabic-letter-jeem', 'right_middle'),
      lc('خ', 'Arabic-letter-kha', 'right_middle'),
      lc('ح', 'Arabic-letter-haa', 'right_index'),
      lc('ع', 'Arabic-letter-ayn', 'right_middle'),
    ],
  },
  {
    id: 'ar-numbers',
    title: 'الأرقام (Arabic-Indic Numerals)',
    language: 'ar',
    script: 'arabic',
    difficulty: 1,
    tags: { hand: 'both', finger: 'all', key_bigram: 'numerals', speed: 'speed' },
    content: [
      lc('١', 'Arabic-1', 'left_index'),
      lc('٢', 'Arabic-2', 'left_middle'),
      lc('٣', 'Arabic-3', 'left_ring'),
      lc('٤', 'Arabic-4', 'left_pinky'),
      lc('٥', 'Arabic-5', 'right_pinky'),
      lc('٦', 'Arabic-6', 'right_pinky'),
      lc('٧', 'Arabic-7', 'right_ring'),
      lc('٨', 'Arabic-8', 'right_middle'),
      lc('٩', 'Arabic-9', 'right_index'),
      lc('٠', 'Arabic-0', 'right_index'),
    ],
  },
  {
    id: 'ar-practice-1',
    title: 'تمرين ١ (Practice 1)',
    language: 'ar',
    script: 'arabic',
    difficulty: 3,
    tags: { hand: 'both', finger: 'all', key_bigram: 'mixed', speed: 'speed' },
    content: [
      lc('م', 'Arabic-letter-mim', 'right_index'),
      lc('ن', 'Arabic-letter-nun', 'left_middle'),
      lc('َ', 'Arabic-fatha', 'left_index'),
      lc('ب', 'Arabic-letter-ba', 'left_index'),
      lc('ل', 'Arabic-letter-lam', 'left_middle'),
      lc('ك', 'Arabic-letter-kaf', 'right_middle'),
    ],
  },
  {
    id: 'ar-practice-2',
    title: 'تمرين ٢ (Practice 2)',
    language: 'ar',
    script: 'arabic',
    difficulty: 3,
    tags: { hand: 'both', finger: 'all', key_bigram: 'mixed', speed: 'speed' },
    content: [
      lc('س', 'Arabic-letter-sin', 'left_index'),
      lc('ي', 'Arabic-letter-ya', 'right_index'),
      lc('د', 'Arabic-letter-dal', 'right_index'),
      lc('ِ', 'Arabic-kasra', 'left_middle'),
      lc('ر', 'Arabic-letter-ra', 'right_index'),
      lc('ع', 'Arabic-letter-ayn', 'right_middle'),
    ],
  },
  {
    id: 'ar-common-words',
    title: 'كلمات شائعة (Common Words)',
    language: 'ar',
    script: 'arabic',
    difficulty: 3,
    tags: { hand: 'both', finger: 'all', key_bigram: 'common-words', speed: 'speed' },
    content: [
      lc('ل', 'Arabic-letter-lam', 'left_middle'),
      lc('س', 'Arabic-letter-sin', 'left_index'),
      lc('ي', 'Arabic-letter-ya', 'right_index'),
      lc('د', 'Arabic-letter-dal', 'right_index'),
      lc('ر', 'Arabic-letter-ra', 'right_index'),
    ],
  },
  {
    id: 'ar-speed',
    title: 'تمرين السرعة (Speed Drill)',
    language: 'ar',
    script: 'arabic',
    difficulty: 4,
    tags: { hand: 'both', finger: 'all', key_bigram: 'speed', speed: 'speed' },
    content: [
      lc('م', 'Arabic-letter-mim', 'right_index'),
      lc('ن', 'Arabic-letter-nun', 'left_middle'),
      lc('ف', 'Arabic-letter-fa', 'right_index'),
      lc('ي', 'Arabic-letter-ya', 'right_index'),
      lc('س', 'Arabic-letter-sin', 'left_index'),
      lc('ر', 'Arabic-letter-ra', 'right_index'),
      lc('ب', 'Arabic-letter-ba', 'left_index'),
      lc('ل', 'Arabic-letter-lam', 'left_middle'),
      lc('ك', 'Arabic-letter-kaf', 'right_middle'),
      lc('ت', 'Arabic-letter-ta', 'left_index'),
      lc('و', 'Arabic-letter-waw', 'right_middle'),
      lc('ا', 'Arabic-letter-alef', 'left_middle'),
    ],
  },
];
